### ISSUE TITLE
known problem? networking error when starting pods, after cluster reboot

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#274] opened 2020-07-21 16:05 UTC
Does anyone see similar problems? Any idea what that could be?

**Describe the bug**
After upgrading a beta6 cluster to GA I have problems that quite a number of pods hang when started. Such as this case.

```

Events:
  Type     Reason                  Age        From                             Message
  ----     ------                  ----       ----                             -------
  Normal   Scheduled               <unknown>  default-scheduler                Successfully assigned openshift-cluster-storage-operator/csi-snapshot-controller-7c8446fc96-nxk6v to worker-03.devqs.ars.de
  Normal   AddedInterface          9m30s      multus                           Add eth0 [10.129.2.17/23]
  Normal   Pulled                  9m30s      kubelet, worker-03.devqs.ars.de  Container image "quay.io/openshift/okd-content@sha256:e69949554a71f58b02984e14eecbad4a79812c7295cac1dda1382751b5bf818f" already present on machine
  Normal   Created                 9m30s      kubelet, worker-03.devqs.ars.de  Created container snapshot-controller
  Normal   Started                 9m30s      kubelet, worker-03.devqs.ars.de  Started container snapshot-controller
  Warning  FailedCreatePodSandBox  98s        kubelet, worker-03.devqs.ars.de  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_csi-snapshot-controller-7c8446fc96-nxk6v_openshift-cluster-storage-operator_236d486d-36c5-4417-9164-02ab00ae0b54_0(61ab999cfc2b59d271952d7ebd0a0b7f6d574b2d3708c1869a32d6fb3b2c4fe2): Multus: [openshift-cluster-storage-operator/csi-snapshot-controller-7c8446fc96-nxk6v]: error adding container to network "ovn-kubernetes": delegateAdd: error invoking confAdd - "ovn-k8s-cni-overlay": error in getting result from AddNetwork: CNI request failed with status 400: '[openshift-cluster-storage-operator/csi-snapshot-controller-7c8446fc96-nxk6v] failed to configure pod interface: timed out dumping br-int flow entries for sandbox: timed out waiting for the condition
'
  Warning  FailedCreatePodSandBox  61s  kubelet, worker-03.devqs.ars.de  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_csi-snapshot-controller-7c8446fc96-nxk6v_openshift-cluster-storage-operator_236d486d-36c5-4417-9164-02ab00ae0b54_0(6bb38ecf04068d63c12a0cf781ebb600da9c2c5cd3bcae9d8a9c0069a6068f09): Multus: [openshift-cluster-storage-operator/csi-snapshot-controller-7c8446fc96-nxk6v]: error adding container to network "ovn-kubernetes": delegateAdd: error invoking confAdd - "ovn-k8s-cni-overlay": error in getting result from AddNetwork: CNI request failed with status 400: '[openshift-cluster-storage-operator/csi-snapshot-controller-7c8446fc96-nxk6v] failed to configure pod interface: timed out dumping br-int flow entries for sandbox: timed out waiting for the condition
'
  Warning  FailedCreatePodSandBox  25s  kubelet, worker-03.devqs.ars.de  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_csi-snapshot-controller-7c8446fc96-nxk6v_openshift-cluster-storage-operator_236d486d-36c5-4417-9164-02ab00ae0b54_0(94cf4aa18b2e5226dea11e2c0cae71ff051a7fddb3262c6eae8736cffacb5425): Multus: [openshift-cluster-storage-operator/csi-snapshot-controller-7c8446fc96-nxk6v]: error adding container to network "ovn-kubernetes": delegateAdd: error invoking confAdd - "ovn-k8s-cni-overlay": error in getting result from AddNetwork: CNI request failed with status 400: '[openshift-cluster-storage-operator/csi-snapshot-controller-7c8446fc96-nxk6v] failed to configure pod interface: timed out dumping br-int flow entries for sandbox: timed out waiting for the condition
'

```

I could get down from perhaps 35 to 6 pods that hang by repeatedly rebooting one node or another where I had the impression that pods hang. But the problem persists. I had already installed a GA cluster directly and had no such problem but did not completely reboot that cluster yet.

**Version**
OKD 4.5 beta6 installed on vSphere UPI, then upgraded to OKD 4.5 GA

**How reproducible**
Difficult to say at this time. It happens for several pods.
I struggle with it rebooting one node after another and somehow its getting less pods that hang now ...

**Comment by vrutkovs** [comment] 2020-07-21 16:09
Is it reproducible on GA build? Please attach must-gather

**Comment by kai-uwe-rommel** [comment] 2020-07-21 16:17
I had awaited your reaction. :-)

I did not see this problem on this cluster when it was installed with beta6
I did also not see this when I installed a new GA cluster one of these days.
I did only encounter this now after upgrading the beta6 cluster to GA ..
I'll do a must-gather later.

I first just wanted to see if someone has seen this before.
I'm not sure yet if this is the correct place ... I'd rather like to go to some community support forum where I could ask others ... is there any? I haven't found one yet ...

**Comment by kai-uwe-rommel** [comment] 2020-07-21 16:20
Actually, the bad started when I (after upgrading the cluster) played "chaos monkey" and rebooted the complete cluster at once to simulate a complete outage and see if it comes up properly afterwards.
I have done this to OCP clusters already and had no such problems.
I suspect there is some problem between OKD's networking code and FCOS ...

**Comment by kai-uwe-rommel** [comment] 2020-07-21 16:28
must-gather fails:

```
C:\Work\ARS\devqs>oc adm must-gather
[must-gather      ] OUT Using must-gather plugin-in image: quay.io/openshift/okd-content@sha256:ef4afb2bc8d802294401b3a112b49d4f5b5727498e2a75f2181f612168ba8472
[must-gather      ] OUT namespace/openshift-must-gather-tgrxn created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-tgf9l created
[must-gather      ] OUT pod for plug-in image quay.io/openshift/okd-content@sha256:ef4afb2bc8d802294401b3a112b49d4f5b5727498e2a75f2181f612168ba8472 created
[must-gather-wscpw] OUT gather did not start: timed out waiting for the condition
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-tgf9l deleted
[must-gather      ] OUT namespace/openshift-must-gather-tgrxn deleted
error: gather did not start for pod must-gather-wscpw: timed out waiting for the condition

C:\Work\ARS\devqs>oc adm must-gather
[must-gather      ] OUT Using must-gather plugin-in image: quay.io/openshift/okd-content@sha256:ef4afb2bc8d802294401b3a112b49d4f5b5727498e2a75f2181f612168ba8472
[must-gather      ] OUT namespace/openshift-must-gather-j6kdh created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-6ngxc created
[must-gather      ] OUT pod for plug-in image quay.io/openshift/okd-content@sha256:ef4afb2bc8d802294401b3a112b49d4f5b5727498e2a75f2181f612168ba8472 created
[must-gather-fhz66] OUT gather did not start: Get https://api.devqs.ars.de:6443/api/v1/namespaces/openshift-must-gather-j6kdh/pods/must-gather-fhz66: unexpected EOF
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-6ngxc deleted
[must-gather      ] OUT namespace/openshift-must-gather-j6kdh deleted
error: gather did not start for pod must-gather-fhz66: Get https://api.devqs.ars.de:6443/api/v1/namespaces/openshift-must-gather-j6kdh/pods/must-gather-fhz66: unexpected EOF

C:\Work\ARS\devqs>oc adm must-gather
[must-gather      ] OUT Using must-gather plugin-in image: quay.io/openshift/okd-content@sha256:ef4afb2bc8d802294401b3a112b49d4f5b5727498e2a75f2181f612168ba8472
[must-gather      ] OUT namespace/openshift-must-gather-tg7wh created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-4cgz6 created
[must-gather      ] OUT pod for plug-in image quay.io/openshift/okd-content@sha256:ef4afb2bc8d802294401b3a112b49d4f5b5727498e2a75f2181f612168ba8472 created
[must-gather-rr52h] OUT gather did not start: Get https://api.devqs.ars.de:6443/api/v1/namespaces/openshift-must-gather-tg7wh/pods/must-gather-rr52h: unexpected EOF
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-4cgz6 deleted
error: gather did not start for pod must-gather-rr52h: Get https://api.devqs.ars.de:6443/api/v1/namespaces/openshift-must-gather-tg7wh/pods/must-gather-rr52h: unexpected EOF
[must-gather      ] OUT namespace/openshift-must-gather-tg7wh deleted
```

**Comment by kai-uwe-rommel** [comment] 2020-07-21 16:57
must-gather seems to have a problem generally.
it also fails (although a bit different) even on an fully working OCP cluster.

**Comment by dustymabe** [comment] 2020-07-21 21:20
Seems similar to the error I saw and reported in #271. Rebooting the nodes cleared things up for me. Not sure why.

**Comment by kai-uwe-rommel** [comment] 2020-07-21 21:33
I have already rebooted all nodes a couple of times. And it did not happen before I upgraded the cluster to GA.
I have now given up on this cluster. Will trash and reinstall tomorrow.
Something is going wrong with OKD on FCOS which does not happen with OCP on RHCOS.

**Comment by abaxo** [comment] 2020-07-22 14:01
+1 I've seen the same behavior

**Comment by vrutkovs** [comment] 2020-07-25 08:48
Dupe of #271

**Closed by vrutkovs** 2020-07-25 08:48 UTC
Labels: triage/needs-information

**Comment by kai-uwe-rommel** [comment] 2020-08-03 20:54
After I destroyed and rebuilt the cluster mentioned above with 4.5 GA 2020-07-14 I did just do an upgrade of this cluster to 2020-07-29 and again have the same problem. OKD simply can't successfully upgrade itself without breaking.
Guys, we really have a problem. OKD 4 is not ready for prime time yet, I'd say. Unfortunately.

**Comment by kai-uwe-rommel** [comment] 2020-08-19 11:17
@vrutkovs could perhaps someone from dev look into this?

**Comment by tvanderka** [comment] 2020-08-20 23:47
I also hit this during upgrade to 4.5.0-0.okd-2020-08-12-020541, rebooting nodes does not help. Cluster broke after mco started to reboot the nodes.
Seems different than #271 to me (that one is openshiftsdn), some kind of issue with ovn/ovsdb, maybe openshift/ovn-kubernetes#227 will help. I saw some errors about ovsdb consistency/integrity in ovn logs, but those could be caused by me trying to fix stuff.

I repaired my cluster by deleting ovsdb data in /var/lib/{ovn,openvswitch} on the nodes, deleting ovn-kubernetes pods and all other crash-looping pods. A bit rough, but upgrade finished and cluster seems OK.

Same/similar issue from OKD CI -> https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-okd-installer-e2e-aws-upgrade/1296186724916924416

**Comment by kai-uwe-rommel** [comment] 2020-08-28 14:29
The other day I installed a new cluster with OKD 20200714-ga to then upgrade it and then (when it fails again) test your repair method.
Well, what should I say! After upgrading that cluster, now to 20200812 it works fine!
So it looks like that release 20200812 may have fixed the problem.

**Comment by kai-uwe-rommel** [comment] 2020-09-10 13:30
I just upgraded another cluster from OKD 20200714-ga to current level, 20200904 and it it worked fine, too.
Great!

**Comment by kai-uwe-rommel** [comment] 2020-09-10 14:45
I have now also successfully updated the cluster I mentionen on 08/28 from 20200812 to 20200904.
Looks good. Three upgrades and all were successful now.
