### ISSUE TITLE
Upgrade OKD 4.5 to 4.6 on vSphere UPI failed

### ISSUE THREAD

**Issue by romankspb** [openshift/okd#395] opened 2020-11-29 00:59 UTC
### Description

 After cluster upgrade I cant open openshift console. OAuth service not working. 

In events present message `"APIService check reporeted "oauth.openshift.io.v1" is not ready: 503"`

Some commands stop working:

`$ ./oc get route --all-namespaces
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get routes.route.openshift.io)`

Some operators in DEGRADED state

$ ./oc get co | awk '$5 == "True" || $5 == "DEGRADED"'
NAME                                       VERSION                         AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.6.0-0.okd-2020-12-12-135354   False       True          True       24h
console                                    4.6.0-0.okd-2020-12-12-135354   False       False         True       23h
image-registry                             4.6.0-0.okd-2020-12-12-135354   True        False         True       20h
monitoring      

### Version
4.5.0-0.okd-2020-10-15-235428
upgrade to
4.6.0-0.okd-2020-11-27-200126
4.6.0-0.okd-2020-12-12-135354

### How reproducible
issue is reproducible - 100%

### Log bundle
[must-gather.tgz](https://gofile.io/d/4CNter)

**Comment by vrutkovs** [comment] 2020-11-29 12:05
Looks similar to https://bugzilla.redhat.com/show_bug.cgi?id=1889900.

Try deleting pods in `openshift-apiserver` namespace? The operator would re-create those and the upgrade would proceed

**Comment by romankspb** [comment] 2020-11-29 16:53
After deleting pods in `openshift-apiserver` namespace nothing changed.

$ ./oc describe co authentication
Name:         authentication
Namespace:    
Labels:       <none>
Annotations:  exclude.release.openshift.io/internal-openshift-hosted: true
API Version:  config.openshift.io/v1
Kind:         ClusterOperator
Metadata:
  Creation Timestamp:  2020-11-24T14:36:41Z
  Generation:          1
  Managed Fields:
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:exclude.release.openshift.io/internal-openshift-hosted:
      f:spec:
      f:status:
        .:
        f:extension:
    Manager:      cluster-version-operator
    Operation:    Update
    Time:         2020-11-24T14:36:41Z
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
        f:relatedObjects:
        f:versions:
    Manager:         authentication-operator
    Operation:       Update
    Time:            2020-11-29T16:49:50Z
  Resource Version:  3372780
  Self Link:         /apis/config.openshift.io/v1/clusteroperators/authentication
  UID:               ccbdc696-a3e4-4e14-bd64-85a93e084460
Spec:
Status:
  Conditions:
    Last Transition Time:  2020-11-28T22:27:17Z
    Message:               IngressStateEndpointsDegraded: Unhealthy addresses found: 10.109.0.5:Get "https://10.109.0.5:6443/healthz": dial tcp 10.109.0.5:6443: connect: connection timed out,10.110.0.19:Get "https://10.110.0.19:6443/healthz": dial tcp 10.110.0.19:6443: connect: no route to host
IngressStatePodsDegraded: Unhealthy pods found: error getting pod "oauth-openshift-64f4b89fd5-h2qft": pods "oauth-openshift-64f4b89fd5-h2qft" not found,error getting pod "oauth-openshift-64f4b89fd5-l5z6m": pods "oauth-openshift-64f4b89fd5-l5z6m" not found
OAuthServiceEndpointsCheckEndpointAccessibleControllerDegraded: [Get "https://10.109.0.20:6443/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Get "https://10.108.0.24:6443/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)]
OAuthServiceCheckEndpointAccessibleControllerDegraded: Get "https://172.30.217.51:443/healthz": dial tcp 172.30.217.51:443: i/o timeout (Client.Timeout exceeded while awaiting headers)
OAuthRouteCheckEndpointAccessibleControllerDegraded: Get "https://oauth-openshift.apps.okd4-spb.sigma-it.local/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
RouteDegraded: Unable to get required route openshift-authentication/oauth-openshift: the server is currently unable to handle the request (get routes.route.openshift.io oauth-openshift)
OAuthServerDeploymentDegraded: Unable to get "openshift-browser-client" bootstrapped OAuth client: the server is currently unable to handle the request (post oauthclients.oauth.openshift.io)
    Reason:                IngressStateEndpoints_UnhealthyAddresses::IngressStatePods_UnhealthyPods::OAuthRouteCheckEndpointAccessibleController_SyncError::OAuthServerDeployment_GetFailed::OAuthServiceCheckEndpointAccessibleController_SyncError::OAuthServiceEndpointsCheckEndpointAccessibleController_SyncError::Route_FailedGet
    Status:                True
    Type:                  Degraded
    Last Transition Time:  2020-11-28T22:42:29Z
    Message:               OAuthVersionRouteProgressing: Request to "https://oauth-openshift.apps.okd4-spb.sigma-it.local/healthz" not successfull yet
    Reason:                OAuthVersionRoute_WaitingForRoute
    Status:                True
    Type:                  Progressing
    Last Transition Time:  2020-11-28T22:37:11Z
    Message:               OAuthRouteCheckEndpointAccessibleControllerAvailable: Get "https://oauth-openshift.apps.okd4-spb.sigma-it.local/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
OAuthServiceEndpointsCheckEndpointAccessibleControllerAvailable: [Get "https://10.109.0.20:6443/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Get "https://10.108.0.24:6443/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)]
OAuthVersionRouteAvailable: HTTP request to "https://oauth-openshift.apps.okd4-spb.sigma-it.local/healthz" failed: dial tcp: lookup oauth-openshift.apps.okd4-spb.sigma-it.local: no such host
OAuthServiceCheckEndpointAccessibleControllerAvailable: Get "https://172.30.217.51:443/healthz": dial tcp 172.30.217.51:443: i/o timeout (Client.Timeout exceeded while awaiting headers)
    Reason:                OAuthRouteCheckEndpointAccessibleController_EndpointUnavailable::OAuthServiceCheckEndpointAccessibleController_EndpointUnavailable::OAuthServiceEndpointsCheckEndpointAccessibleController_EndpointUnavailable::OAuthVersionRoute_RequestFailed
    Status:                False
    Type:                  Available
    Last Transition Time:  2020-11-24T14:38:56Z
    Reason:                AsExpected
    Status:                True
    Type:                  Upgradeable
  Extension:               <nil>
  Related Objects:
    Group:      operator.openshift.io
    Name:       cluster
    Resource:   authentications
    Group:      config.openshift.io
    Name:       cluster
    Resource:   authentications
    Group:      config.openshift.io
    Name:       cluster
    Resource:   infrastructures
    Group:      config.openshift.io
    Name:       cluster
    Resource:   oauths
    Group:      route.openshift.io
    Name:       oauth-openshift
    Namespace:  openshift-authentication
    Resource:   routes
    Group:      
    Name:       oauth-openshift
    Namespace:  openshift-authentication
    Resource:   services
    Group:      
    Name:       openshift-config
    Resource:   namespaces
    Group:      
    Name:       openshift-config-managed
    Resource:   namespaces
    Group:      
    Name:       openshift-authentication
    Resource:   namespaces
    Group:      
    Name:       openshift-authentication-operator
    Resource:   namespaces
    Group:      
    Name:       openshift-ingress
    Resource:   namespaces
    Group:      
    Name:       openshift-oauth-apiserver
    Resource:   namespaces
  Versions:
    Name:     operator
    Version:  4.6.0-0.okd-2020-11-27-200126
    Name:     oauth-openshift
    Version:  4.6.0-0.okd-2020-11-27-200126_openshift
    Name:     oauth-apiserver
    Version:  4.6.0-0.okd-2020-11-27-200126
Events:       <none>

**Comment by vrutkovs** [comment] 2020-11-29 22:05
>dial tcp: lookup oauth-openshift.apps.okd4-spb.sigma-it.local: no such host

looks like external DNS is not setup / redirecting to *.apps correctly?

**Comment by romankspb** [comment] 2020-11-30 08:49
External DNS works correctly.

$ for i in {1..3}; do ssh -n core@okd4-spb-master$i.sigma-it.local host oauth-openshift.apps.okd4-spb.sigma-it.local; done
oauth-openshift.apps.okd4-spb.sigma-it.local is an alias for okd4-spb-lb2-vip.sigma-it.local.
okd4-spb-lb2-vip.sigma-it.local has address 10.197.0.104
oauth-openshift.apps.okd4-spb.sigma-it.local is an alias for okd4-spb-lb2-vip.sigma-it.local.
okd4-spb-lb2-vip.sigma-it.local has address 10.197.0.104
oauth-openshift.apps.okd4-spb.sigma-it.local is an alias for okd4-spb-lb2-vip.sigma-it.local.
okd4-spb-lb2-vip.sigma-it.local has address 10.197.0.104

$ for i in {1..3}; do ssh -n core@okd4-spb-infra$i.sigma-it.local host oauth-openshift.apps.okd4-spb.sigma-it.local; done
oauth-openshift.apps.okd4-spb.sigma-it.local is an alias for okd4-spb-lb2-vip.sigma-it.local.
okd4-spb-lb2-vip.sigma-it.local has address 10.197.0.104
oauth-openshift.apps.okd4-spb.sigma-it.local is an alias for okd4-spb-lb2-vip.sigma-it.local.
okd4-spb-lb2-vip.sigma-it.local has address 10.197.0.104
oauth-openshift.apps.okd4-spb.sigma-it.local is an alias for okd4-spb-lb2-vip.sigma-it.local.
okd4-spb-lb2-vip.sigma-it.local has address 10.197.0.104

but with internal DNS something wrong. I can to resolve host from internal DNS pod 

$ ./oc exec -it dns-default-4bx5c -n openshift-dns -c dns -- host oauth-openshift.apps.okd4-spb.sigma-it.local
oauth-openshift.apps.okd4-spb.sigma-it.local is an alias for okd4-spb-lb2-vip.sigma-it.local.
okd4-spb-lb2-vip.sigma-it.local has address 10.197.0.104

but i can't do the same from any pod in `openshift-apiserver` namespace

$ ./oc exec -it apiserver-59c565cd87-9zqvm -c openshift-apiserver -n openshift-apiserver -- host oauth-openshift.apps.okd4-spb.sigma-it.local
;; connection timed out; no servers could be reached
command terminated with exit code 1

$ ./oc exec -it apiserver-59c565cd87-9zqvm -c openshift-apiserver -n openshift-apiserver -- cat /etc/resolv.conf
search openshift-apiserver.svc.cluster.local svc.cluster.local cluster.local sigma-it.local
nameserver 172.30.0.10
options ndots:5

**Comment by vrutkovs** [comment] 2020-12-01 16:27
Looks similar to #401 (still nto sure what's causing it)

**Comment by alexanderniebuhr** [comment] 2020-12-03 15:05
@romankspb @vrutkovs same issue for me 👍

**Comment by romankspb** [comment] 2020-12-15 15:45
@vrutkovs Today I tried to update freshly installed 4.5.0-0.okd-2020-10-15-235428 to a new version 4.6.0-0.okd-2020-12-12-135354. The result are the same as before. All services in service network are unavailable. Also I cant gather debugging information, `oc adm must-gather` stuck in a terminated state. I can provide any additional information if required.

`$ oc exec -it authentication-operator-586b6f8f7-4g6gp -n openshift-authentication-operator -- curl -k https://172.30.120.96:443/healthz
curl: (7) Failed to connect to 172.30.120.96 port 443: Connection timed out
command terminated with exit code 7
`

`
$ oc exec -it authentication-operator-586b6f8f7-4g6gp -n openshift-authentication-operator -- host oauth-openshift.apps.okd4-spb.sigma-it.local
;; connection timed out; no servers could be reached
command terminated with exit code 1
`

**Comment by vrutkovs** [comment] 2020-12-15 16:30
Lets start with comments in https://bugzilla.redhat.com/show_bug.cgi?id=1889900, so that apiserver team would be aware of this

**Comment by bdlink** [comment] 2020-12-15 21:00
Upgraded 4.5 => 4..6 (4.6.0-0.okd-2020-12-12-135354)

One worker node failed to upgrade:
$ oc get nodes
NAME              STATUS                     ROLES    AGE    VERSION
compute-1         Ready                      worker   143d   v1.19.2+7070803-1008
compute-2         Ready                      worker   143d   v1.19.2+7070803-1008
compute-3         Ready,SchedulingDisabled   worker   143d   v1.18.3
compute-4         Ready                      worker   143d   v1.19.2+7070803-1008
compute-5         Ready                      worker   143d   v1.19.2+7070803-1008
control-plane-1   Ready                      master   143d   v1.19.2+7070803-1008
control-plane-2   Ready                      master   143d   v1.19.2+7070803-1008
control-plane-3   Ready                      master   143d   v1.19.2+7070803-1008

All operators were upgraded to 4.6, and were available.  Further in the update the console became unavailable as well as remote cli access.  From a server on the OKD local network, using original KUBECONFIG authorization, several cluster operators were unavailable: openshift-apiserver, authentication, console, image-registry, monitoring, operator-lifecycle-manager-packageserver

Must-gather report available at private repository https://gitlab.infoteach.ca/bdlink/okd-maintenance.git 
Access given to maintainers, as desirec.

**Comment by bdlink** [comment] 2020-12-16 01:00
Attached is openshift-apiserver log from must-gather, it is not too big,
[current.log.gz](https://github.com/openshift/okd/files/5699616/current.log.gz)

**Comment by romankspb** [comment] 2020-12-16 07:39
@alexanderniebuhr Please comment in https://bugzilla.redhat.com/show_bug.cgi?id=1889900

**Comment by bdlink** [comment] 2020-12-16 17:13
In my case, one of the nodes, running rook-ceph failed to upgrade, _may_ be different failure case than https://bugzilla.redhat.com/show_bug.cgi?id=1889900 .  Node has scheduliing disabled, but after clean shutdown/startup is still running several pods: 
```kubectl get pods --all-namespaces -o wide --field-selector spec.nodeName=compute-3
NAMESPACE                                NAME                           READY   STATUS    RESTARTS   AGE   IP              NODE        NOMINATED NODE   READINESS GATES
openshift-cluster-node-tuning-operator   tuned-5wfpz                    1/1     Running   0          43h   192.168.3.206   compute-3   <none>           <none>
openshift-dns                            dns-default-rdpzn              3/3     Running   0          41h   10.130.2.4      compute-3   <none>           <none>
openshift-image-registry                 node-ca-4n8rh                  1/1     Running   0          43h   192.168.3.206   compute-3   <none>           <none>
openshift-machine-config-operator        machine-config-daemon-wg7g8    2/2     Running   0          41h   192.168.3.206   compute-3   <none>           <none>
openshift-monitoring                     node-exporter-gpgkf            2/2     Running   0          43h   192.168.3.206   compute-3   <none>           <none>
openshift-multus                         multus-wz7z2                   1/1     Running   0          43h   192.168.3.206   compute-3   <none>           <none>
openshift-multus                         network-metrics-daemon-rl6nd   2/2     Running   0          43h   10.130.2.2      compute-3   <none>           <none>
openshift-must-gather-k97w9              must-gather-dwgfn              1/1     Running   0          24h   10.130.2.3      compute-3   <none>           <none>
openshift-sdn                            ovs-k2cgk                      1/1     Running   0          43h   192.168.3.206   compute-3   <none>           <none>
openshift-sdn                            sdn-qm822                      2/2     Running   1          43h   192.168.3.206   compute-3   <none>           <none>
rook-ceph                                csi-cephfsplugin-wf467         3/3     Running   0          59d   192.168.3.206   compute-3   <none>           <none>
rook-ceph                                csi-rbdplugin-jjjx7            3/3     Running   0          59d   192.168.3.206   compute-3   <none>           <none>
rook-ceph                                rook-discover-m5gx8            1/1     Running   0          59d   10.130.2.5      compute-3   <none>           <none>`

**Comment by vrutkovs** [comment] 2020-12-23 22:34
Dupe of #430 - openshiftSDN is preventing ingress from working in 4.6

**Closed by vrutkovs** 2020-12-23 22:34 UTC
