### ISSUE TITLE
"okd" cluster name

### ISSUE THREAD

**Issue by baturorkun** [openshift/okd#637] opened 2021-05-13 08:55 UTC
I think that when I gave cluster name to "okd", have some problems.  Insights-operator is not running properly and I could not upgrade my cluster version. (4.6 to 4.7) and now I have a problem with the Storage service about SSL like Insights. Is it possible?

I found this issue: https://github.com/openshift/okd/issues/71 and I think It is similar.

**Comment by vrutkovs** [comment] 2021-05-13 09:07
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive.

**Comment by vrutkovs** [comment] 2021-05-13 09:07
Also, is this a dupe of https://github.com/openshift/okd/discussions/626?

**Comment by baturorkun** [comment] 2021-05-19 19:26
hi @vrutkovs. yes sorry. At first, I created it there and I could not delete it.  
I deleted my cluster and I am planing with a different cluster name. In my opinion, the problem is my cluster name "okd"

**Closed** 2021-05-20 17:00 UTC
