### ISSUE TITLE
"thin" storage class hangs after new 4.5 beta6 vSphere UPI deployment

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#240] opened 2020-07-02 07:25 UTC
**Describe the bug**
I installed a 4.5 beta6 OKD cluster und vSphere UPI exactly like I did before with 4.4 beta5.

The (auto) provisioning of volumes for the automatically predefined storage class "thin" now fails. This has worked in 4.4 beta5 before. The error message I see is:

![grafik](https://user-images.githubusercontent.com/26381804/86287083-e0b4b480-bbe7-11ea-99a1-5f3f5e629cb0.png)

The folder path is not correct. The /Test is the vSphere datacenter and /Test/vm is the base VM folder, right? And the subfolder where the cluster VMs are is named "kur-test" (same like the cluster name). No idea why the vSphere storage provisioner now tries to append this "-2pjrl" suffix. But it is the same like in the machineset above. In any case, it is wrong.  I can see it in /etc/kubernetes/cloud.conf now. In my previous 4.4 beta5 deployments, it was just "kur-test", without the prefix path and without the random suffix.
**Version**
OKD 4.5 beta6

**How reproducible**
Always.

**Log bundle**
n/a

**Comment by kai-uwe-rommel** [comment] 2020-07-02 07:27
I learned here:
https://github.com/openshift/okd/issues/149#issuecomment-652673364
that it is a documentation issue.
The VM folder for the cluster's UPI VMs must be named exactly like the infraID.
The OKD latest documentation has not been updated (yet?).

Once I rename the VM folder, the storage class immediately starts working.

**Comment by vrutkovs** [comment] 2020-07-02 07:36
Please attach must-gather archive

**Comment by vrutkovs** [comment] 2020-07-02 07:37
>The VM folder for the cluster's UPI VMs must be named exactly like the infraID.

[Documentation](https://docs.okd.io/latest/installing/installing_vsphere/installing-vsphere.html) has this:

>In the window that is displayed, enter the folder name. The folder name must match the cluster name that you specified in the install-config.yaml file.

Is it correct? What is missing?

**Comment by kai-uwe-rommel** [comment] 2020-07-02 07:52
In my sample (first 4.5 beta6 installation yesterday) I defined the cluster name as "kur-test" in install-config.yaml and named the VM folder the same (that is how it is still documented).

But apparently, the folder name must rather match the "infraID" which is "kur-test-2pjrl" and which I can find in the metadata.json file after running the openshift-installer to create the ignition files for my UPI installation, which creates this random suffix.

This is different from how it was in 4.4 beta5 where indeed the folder name must match just the cluster name.

**Comment by kai-uwe-rommel** [comment] 2020-07-02 11:56
The next question is what will happen if I upgrade a cluster from OKD 4.4 to 4.5 ...
If the folder name/path is changed and I need to rename the folder, the upgrade may fail because I do not know at which point in the upgrade process I need to rename it.
A failure can happen if a node is rebooted and the pods need to be evicted and mounted kubevols must be moved to a different node.

**Comment by vrutkovs** [comment] 2020-07-02 12:32
Update to OKD 4.5 would require updating the folder iiuc - https://github.com/openshift/installer/blob/master/docs/user/vsphere/install_upi.md#check-folder-name-in-cloud-provider-manifest.

I think its best to file a bug for OCP - cloud-config should be able to keep the folder reference if possible

**Comment by kai-uwe-rommel** [comment] 2020-07-02 12:56
I'll first try an upgrade to have more details to report.

**Comment by kai-uwe-rommel** [comment] 2020-07-02 19:00
I just deployed (... let my tools deploy) a 4.4 beta5 OKD cluster and then upgraded it to 4.5 beta6.
The upgrade did not change the folder name in /etc/kubernetes/cloud.conf to how it looks like in new 4.5 clusters.
I assume this is intentional and the "new style" is default for new clusters, but not mandatory for existing ones.

**Comment by kai-uwe-rommel** [comment] 2020-07-09 16:24
Important: to use the new optional "folder" property for vSphere if not creating the cluster folder in the root of the VM tree.

**Comment by vrutkovs** [comment] 2020-09-19 09:41
Marking as dupe of #284 as it has more info about thin provisioning

**Closed by vrutkovs** 2020-09-19 09:41 UTC
Labels: kind/documentation, platform/vsphere
