### ISSUE TITLE
Node provisioning failing in 4.7.0-0.okd-2021-06-13-090745

### ISSUE THREAD

**Issue by aelbarkani** [openshift/okd#702] opened 2021-06-18 14:23 UTC
**Describe the bug**

Machines stuck at "Provisioned" state instead of progressing to "Provisioned as node"

**Version**

 4.7.0-0.okd-2021-06-13-090745
AWS IPI. Tested with GCP IPI too, same issue.

**How reproducible**

100%

**Log bundle**

In one of the non-provisioned nodes:
```
[core@ip-172-31-57-154 ~]$ systemctl status machine-config-daemon-firstboot.service
● machine-config-daemon-firstboot.service - Machine Config Daemon Firstboot
     Loaded: loaded (/etc/systemd/system/machine-config-daemon-firstboot.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2021-06-18 13:57:51 UTC; 21min ago
    Process: 1344 ExecStartPre=/usr/bin/sh -c sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/*.repo (code=exited, status=0/SUCCESS)
    Process: 1345 ExecStart=/run/bin/machine-config-daemon firstboot-complete-machineconfig (code=exited, status=1/FAILURE)
   Main PID: 1345 (code=exited, status=1/FAILURE)
        CPU: 32.475s

Jun 18 13:57:47 ip-172-31-57-154 machine-config-daemon[1345]: : exit status 1
Jun 18 13:57:47 ip-172-31-57-154 machine-config-daemon[1345]: I0618 13:57:47.419246    1345 rpm-ostree.go:261] Running captured: rpm-ostree cleanup -p
Jun 18 13:57:51 ip-172-31-57-154 machine-config-daemon[1345]: I0618 13:57:51.223653    1345 update.go:1221] Updating files
Jun 18 13:57:51 ip-172-31-57-154 machine-config-daemon[1345]: I0618 13:57:51.224596    1345 update.go:1299] Deleting stale data
Jun 18 13:57:51 ip-172-31-57-154 machine-config-daemon[1345]: error: error running rpm-ostree update --install glusterfs --install glusterfs-fuse --install qemu-guest-agent --install NetworkManager-ovs: error: "glusterfs" is already provided by: glusterfs-9.2-1.fc34.x86_64. Use --allow-inactive to explicitly require it.
Jun 18 13:57:51 ip-172-31-57-154 machine-config-daemon[1345]: : exit status 1
Jun 18 13:57:51 ip-172-31-57-154 systemd[1]: machine-config-daemon-firstboot.service: Main process exited, code=exited, status=1/FAILURE
Jun 18 13:57:51 ip-172-31-57-154 systemd[1]: machine-config-daemon-firstboot.service: Failed with result 'exit-code'.
Jun 18 13:57:51 ip-172-31-57-154 systemd[1]: Failed to start Machine Config Daemon Firstboot.
Jun 18 13:57:51 ip-172-31-57-154 systemd[1]: machine-config-daemon-firstboot.service: Consumed 32.475s CPU time.
```

**Comment by vrutkovs** [comment] 2021-06-18 14:40
Dupe of #699

**Closed by vrutkovs** 2021-06-18 14:40 UTC
