### ISSUE TITLE
image-pruner job failed

### ISSUE THREAD

**Issue by tuan1nguyen** [openshift/okd#478] opened 2021-01-24 10:59 UTC
**Describe the bug**

  containerStatuses:
    - restartCount: 0
      started: false
      ready: false
      name: image-pruner
      state:
        terminated:
          exitCode: 1
          reason: Error
          message: >
            error: failed to ping registry
            image-registry.openshift-image-registry.svc:5000: Get
            "https://image-registry.openshift-image-registry.svc:5000/": dial
            tcp 172.30.35.22:5000: i/o timeout
          startedAt: '2021-01-24T00:00:54Z'
          finishedAt: '2021-01-24T00:01:24Z'
          containerID: >-
            cri-o://1fe2b535dfce8e2b34aeda4dcddb170d2993fddbed7774baa3ada439e083f28e

**Version**

4.6.0-0.okd-2021-01-17-185703

**How reproducible**

**Log bundle**

https://drive.google.com/file/d/1icyxsigULy8tKa31fHrJXnUbPh6udi11/view?usp=sharing

**Comment by vrutkovs** [comment] 2021-01-24 11:15
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by tuan1nguyen** [comment] 2021-01-24 12:11
https://drive.google.com/file/d/1icyxsigULy8tKa31fHrJXnUbPh6udi11/view?usp=sharing

**Comment by vrutkovs** [comment] 2021-01-24 14:38
Imagepruner pod can't reach the registry:
```
error: failed to ping registry image-registry.openshift-image-registry.svc:5000: Get "https://image-registry.openshift-image-registry.svc:5000/": dial tcp 172.30.35.22:5000: i/o timeout
```

caused by `networkType: OpenShiftSDN`. Dupe of #430

**Closed by vrutkovs** 2021-01-24 14:38 UTC
