### ISSUE TITLE
4.7 2021-03-21 UPI does not finish cluster installation

### ISSUE THREAD

**Issue by bretm** [openshift/okd#571] opened 2021-03-22 23:27 UTC
**Describe the bug**

Installing the most recent 4.7 stable does not yield a working cluster.  Several cluster operators are non-functional, with errors preventing forward progress.  Here is the debug output of the installer:

> openshift-install --dir=install_dir/ wait-for install-complete --log-level=debug
DEBUG OpenShift Installer 4.7.0-0.okd-2021-03-21-094146
DEBUG Built from commit 7695204e842218d2deea4b115924e6967c90d72f
DEBUG Loading Install Config...
DEBUG   Loading SSH Key...
DEBUG   Loading Base Domain...
DEBUG     Loading Platform...
DEBUG   Loading Cluster Name...
DEBUG     Loading Base Domain...
DEBUG     Loading Platform...
DEBUG   Loading Networking...
DEBUG     Loading Platform...
DEBUG   Loading Pull Secret...
DEBUG   Loading Platform...
DEBUG Using Install Config loaded from state file
INFO Waiting up to 40m0s for the cluster at https://api.okd4.rdu.bretm.net:6443 to initialize...
DEBUG Still waiting for the cluster to initialize: Could not update oauthclient "console" (406 of 671)
DEBUG Still waiting for the cluster to initialize: Multiple errors are preventing progress:
DEBUG * Could not update credentialsrequest "openshift-cloud-credential-operator/openshift-machine-api-ovirt" (134 of 671)
DEBUG * Could not update credentialsrequest "openshift-cloud-credential-operator/ovirt-csi-driver-operator" (395 of 671)
DEBUG * Could not update featuregate "cluster" (22 of 671)
DEBUG * Could not update oauthclient "console" (406 of 671)
DEBUG * Could not update prometheusrule "openshift-image-registry/image-registry-operator-alerts" (291 of 671)
DEBUG Still waiting for the cluster to initialize: Working towards 4.7.0-0.okd-2021-03-21-094146: 547 of 671 done (81% complete)
DEBUG Still waiting for the cluster to initialize: Working towards 4.7.0-0.okd-2021-03-21-094146: 631 of 671 done (94% complete)
DEBUG Still waiting for the cluster to initialize: Could not update deployment "openshift-console-operator/console-operator" (444 of 671)
DEBUG Still waiting for the cluster to initialize: Multiple errors are preventing progress:
DEBUG * Could not update machinehealthcheck "openshift-machine-api/machine-api-termination-handler" (168 of 671)
DEBUG * Could not update route "openshift-console/downloads" (442 of 671)
DEBUG Still waiting for the cluster to initialize: Could not update oauthclient "console" (406 of 671)
DEBUG Still waiting for the cluster to initialize: Working towards 4.7.0-0.okd-2021-03-21-094146: 632 of 671 done (94% complete)
DEBUG Still waiting for the cluster to initialize: Could not update route "openshift-console/downloads" (442 of 671)
DEBUG Still waiting for the cluster to initialize: Could not update oauthclient "console" (406 of 671): the server does not recognize this resource, check extension API servers
ERROR Cluster operator authentication Degraded is True with IngressStateEndpoints_UnhealthyAddresses::OAuthRouteCheckEndpointAccessibleController_SyncError::OAuthServerDeployment_GetFailed::OAuthServiceCheckEndpointAccessibleController_SyncError::OAuthServiceEndpointsCheckEndpointAccessibleController_SyncError::Route_FailedGet: OAuthServiceEndpointsCheckEndpointAccessibleControllerDegraded: [Get "https://10.130.0.33:6443/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Get "https://10.129.0.44:6443/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)]
ERROR OAuthServiceCheckEndpointAccessibleControllerDegraded: Get "https://172.30.1.131:443/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
ERROR IngressStateEndpointsDegraded: Unhealthy addresses found: 10.129.0.44:Get "https://10.129.0.44:6443/healthz": dial tcp 10.129.0.44:6443: connect: connection timed out,10.130.0.33:Get "https://10.130.0.33:6443/healthz": dial tcp 10.130.0.33:6443: connect: connection timed out
ERROR OAuthRouteCheckEndpointAccessibleControllerDegraded: Get "https://oauth-openshift.apps.okd4.rdu.bretm.net/healthz": EOF
ERROR OAuthServerDeploymentDegraded: Unable to get "openshift-browser-client" bootstrapped OAuth client: the server is currently unable to handle the request (get oauthclients.oauth.openshift.io openshift-browser-client)
ERROR RouteDegraded: Unable to get required route openshift-authentication/oauth-openshift: the server is currently unable to handle the request (get routes.route.openshift.io oauth-openshift)
INFO Cluster operator authentication Progressing is True with OAuthVersionRoute_WaitingForRoute: OAuthVersionRouteProgressing: Request to "https://oauth-openshift.apps.okd4.rdu.bretm.net/healthz" not successful yet
INFO Cluster operator authentication Available is False with APIServices_Error::OAuthRouteCheckEndpointAccessibleController_EndpointUnavailable::OAuthServiceCheckEndpointAccessibleController_EndpointUnavailable::OAuthServiceEndpointsCheckEndpointAccessibleController_EndpointUnavailable::OAuthVersionRoute_RequestFailed: OAuthServiceEndpointsCheckEndpointAccessibleControllerAvailable: [Get "https://10.130.0.33:6443/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Get "https://10.129.0.44:6443/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)]
INFO APIServicesAvailable: "oauth.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
INFO OAuthServiceCheckEndpointAccessibleControllerAvailable: Get "https://172.30.1.131:443/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
INFO OAuthVersionRouteAvailable: HTTP request to "https://oauth-openshift.apps.okd4.rdu.bretm.net/healthz" failed: EOF
INFO OAuthRouteCheckEndpointAccessibleControllerAvailable: Get "https://oauth-openshift.apps.okd4.rdu.bretm.net/healthz": EOF
INFO Cluster operator baremetal Disabled is True with UnsupportedPlatform: Nothing to do on this Platform
INFO Cluster operator insights Disabled is True with Disabled: Health reporting is disabled
INFO Cluster operator monitoring Available is False with :
INFO Cluster operator monitoring Progressing is True with RollOutInProgress: Rolling out the stack.
ERROR Cluster operator monitoring Degraded is True with UpdatingUserWorkloadThanosRulerFailed: Failed to rollout the stack. Error: running task Updating User Workload Thanos Ruler failed: deleting Thanos Ruler Route failed: the server is currently unable to handle the request (delete routes.route.openshift.io thanos-ruler)
INFO Cluster operator network ManagementStateDegraded is False with :
INFO Cluster operator openshift-apiserver Available is False with APIServices_Error: APIServicesAvailable: "apps.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
INFO APIServicesAvailable: "build.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
INFO APIServicesAvailable: "image.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
INFO APIServicesAvailable: "project.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
INFO APIServicesAvailable: "quota.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
INFO APIServicesAvailable: "route.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
INFO APIServicesAvailable: "security.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
INFO APIServicesAvailable: "template.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
INFO Cluster operator openshift-samples Available is False with :
INFO Cluster operator operator-lifecycle-manager-packageserver Available is False with :
INFO Cluster operator operator-lifecycle-manager-packageserver Progressing is True with : Working toward 0.17.0
ERROR Cluster initialization failed because one or more operators are not functioning properly.
ERROR The cluster should be accessible for troubleshooting as detailed in the documentation linked below,
ERROR https://docs.openshift.com/container-platform/latest/support/troubleshooting/troubleshooting-installations.html
ERROR The 'wait-for install-complete' subcommand can then be used to continue the installation
FATAL failed to initialize the cluster: Could not update oauthclient "console" (406 of 671): the server does not recognize this resource, check extension API servers

**Version**

Version:  4.7.0-0.okd-2021-03-21-094146

**How reproducible**

Have not tried again, but similar to errors experienced w/ 4.6 & 4.7 RC's

**Log bundle**

https://drive.google.com/file/d/1rrSYbUTBtOnN7K1FMEmDOZuhS4DKDjKw/view?usp=sharing

**Comment by vrutkovs** [comment] 2021-03-23 08:50
Looks similar to https://bugzilla.redhat.com/show_bug.cgi?id=1935539#c21 - are those vSphere VMs with HW version > 13?

**Comment by bretm** [comment] 2021-03-23 11:03
Yes, iiuc, they're HW level 18.

Reading the bug, this bit makes me wonder:

> Cross-node pod-to-pod or host-to-pod connections fail because packets are being dropped by vSphere between the nodes (apparently because of checksum errors, apparently because of a kernel change between 4.6 and 4.7).

In my use case, everyone's running the same bits; they're all using the same FCOS image, so what would be causing the checksum errors?

**Comment by vrutkovs** [comment] 2021-03-23 11:18
Right, its a dupe of #430. Lets continue there or in bugzilla

**Closed by vrutkovs** 2021-03-23 11:18 UTC
