### ISSUE TITLE
4.6.0-0.okd-2020-12-21-142926 clean bare metal installation, incomplete clusteroperators installation

### ISSUE THREAD

**Issue by myg0v** [openshift/okd#448] opened 2020-12-27 17:32 UTC
**Describe the bug**
The clusteroperators will not install properly with 4.6.0-0.okd-2020-12-21-142926 and FCOS 33.20201214.2.0.

```
./oc get co
NAME                                       VERSION                         AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.6.0-0.okd-2020-12-21-142926   False       True          True       11h
cloud-credential                           4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
cluster-autoscaler                         4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
config-operator                            4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
console                                    4.6.0-0.okd-2020-12-21-142926   Unknown     False         True       3h30m
csi-snapshot-controller                    4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
dns                                        4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
etcd                                       4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
image-registry                             4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
ingress                                    4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
insights                                   4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
kube-apiserver                             4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
kube-controller-manager                    4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
kube-scheduler                             4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
kube-storage-version-migrator              4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
machine-api                                4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
machine-approver                           4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
machine-config                             4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
marketplace                                4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
monitoring                                                                 False       False         True       11h
network                                    4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
node-tuning                                4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
openshift-apiserver                        4.6.0-0.okd-2020-12-21-142926   False       False         False      11h
openshift-controller-manager               4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
openshift-samples                                                          False       False         False      11h
operator-lifecycle-manager                 4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
operator-lifecycle-manager-catalog         4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
operator-lifecycle-manager-packageserver   4.6.0-0.okd-2020-12-21-142926   False       True          False      11h
service-ca                                 4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
storage                                    4.6.0-0.okd-2020-12-21-142926   True        False         False      11h
```

**Version**
4.6.0-0.okd-2020-12-21-142926 with FCOS 33.20201214.2.0 (bate metal installation with VMs within VMware ESXi 6.7)

**How reproducible**
1. oc adm release extract --tools registry.svc.ci.openshift.org/origin/release@sha256:068a04c84d0ef8d6325a37497da3d69152104ea357db29498378ad44760042f5

2. Create install-config.yaml in install_dir
```
apiVersion: v1
baseDomain: basedomain.com
proxy:
  httpProxy: http://proxy-01.***:3128
  httpsProxy: http://proxy-01.***:3128
  noProxy: localhost,127.0.0.0/8,::1/128,***,basedomain.com,okd.basedomain.com,10.1.232.0/24
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
***
  -----END CERTIFICATE-----
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: okd
networking:
  clusterNetwork:
  - cidr: 10.200.0.0/16
    hostPrefix: 21
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: '{"auths":{"fake":{"auth": "bar"}}}'
sshKey: 'ssh-ed25519 AAAA***
```
3. Create ignition files and upload them after to a HTTP server
./openshift-install create manifests --dir=install_dir/
./openshift-install create ignition-configs --dir=install_dir/
4. Create new VMs (1x bootstrap, 3x master) and boot from .iso https://builds.coreos.fedoraproject.org/prod/streams/testing/builds/33.20201214.2.0/x86_64/fedora-coreos-33.20201214.2.0-live.x86_64.iso
5. Verify that all the DNS records are created and the required ips from the bootstrap and master are added the related load balancer pools for the required ports (bootstrap and master for Port 22623 and 6443; master for Port 443 and 80. 
api-int.okd.basedomain.com > LB-IP
api.okd.basedomain.com > CNAME to api-int.okd.basedomain.com (LB)
*.apps.okd.basedomain.com > CNAME to api-int.okd.basedomain.com (LB)
6. Start the coreos-installer with the following parameter (I added append-karg to bypass the issue #394)
sudo coreos-installer install /dev/sda --insecure-ignition --copy-network --ignition-url http://httpserverdomain.com/bootstrap.ign --append-karg="ip=10.1.232.57::10.1.232.1:255.255.255.0:k8s-bootstrap-1-01.okd.basedomain.com:ens160:none:10.1.231.85:10.1.231.5"
sudo coreos-installer install /dev/sda --insecure-ignition --copy-network --ignition-url http://httpserverdomain.com/master.ign --append-karg="ip=10.1.232.191::10.1.232.1:255.255.255.0:k8s-master-1-01.okd.basedomain.com:ens160:none:10.1.231.85:10.1.231.5"
sudo coreos-installer install /dev/sda --insecure-ignition --copy-network --ignition-url http://httpserverdomain.com/master.ign --append-karg="ip=10.1.232.13::10.1.232.1:255.255.255.0:k8s-master-2-01.okd.basedomain.com:ens160:none:10.1.231.85:10.1.231.5"
sudo coreos-installer install /dev/sda --insecure-ignition --copy-network --ignition-url http://httpserverdomain.com/master.ign --append-karg="ip=10.1.232.158::10.1.232.1:255.255.255.0:k8s-master-3-01.okd.basedomain.com:ens160:none:10.1.231.85:10.1.231.5"
7. Wait some hours after ./openshift-install --dir=install_dir/ wait-for bootstrap-complete --log-level=info is successful. Some cluster operators remain in unavailable state. The nodes show the status ready:
```
./oc get nodes
NAME                                STATUS   ROLES           AGE   VERSION
k8s-master-1-01-okd.basedomain.com   Ready    master,worker   11h   v1.19.2+9c69bdc-1012
k8s-master-2-01.okd.basedomain.com   Ready    master,worker   11h   v1.19.2+9c69bdc-1012
k8s-master-3-01.okd.basedomain.com   Ready    master,worker   11h   v1.19.2+9c69bdc-1012
```

**Log bundle**
must-gather and ./openshift-install gather bootstrap can be downloaded here: https://we.tl/t-kL4XLyHGTY

**Comment by vrutkovs** [comment] 2020-12-28 08:46
Dupe of #430

**Closed by vrutkovs** 2020-12-28 08:47 UTC
