### ISSUE TITLE
can not mirror images / upgrade to 4.6 with air-gapped installation

### ISSUE THREAD

**Issue by philipp1992** [openshift/okd#409] opened 2020-12-03 08:10 UTC
Hi,

we are operating OKD4 in an air-gapped enviornment behind proxy with an internal docker registry.
To install openshift, we have used the mirror utility to pull and push all images into our private docker registry.

This has worked perfectly so far.

Now we want to do a upgrade to 4.6 and therefore have issued the following command:

```
+ oc adm release mirror --from registry.svc.ci.openshift.org/origin/release:4.6.0-0.okd-2020-12-01-234901 --to docker.xxx.net/rs_ruscloud-dit-public/quay.io/openshift/okd-content/version-4.6.0-0.okd-2020-12-01-234901 --to-release-image docker.xxx.net/rs_ruscloud-dit-public/quay.io/openshift/okd-content:4.6.0-0.okd-2020-12-01-234901
I1202 13:50:31.067742   80981 verify.go:472] not found
I1202 13:50:31.653797   80981 verify.go:472] not found
warning: An image was retrieved that failed verification: unable to locate a valid signature for one or more sources
info: Mirroring 125 images to docker.xxx.net/rs_ruscloud-dit-public/quay.io/openshift/okd-content/version-4.6.0-0.okd-2020-12-01-234901 ...
...
info: Mirroring completed in 4m35.74s (23.25MB/s)

Success
Update image:  docker.xxx.net/rs_ruscloud-dit-public/quay.io/openshift/okd-content:4.6.0-0.okd-2020-12-01-234901
Mirror prefix: docker.xxx.net/rs_ruscloud-dit-public/quay.io/openshift/okd-content/version-4.6.0-0.okd-2020-12-01-234901
```

Unfortunatly, when we want to do a cluster upgrade, the images can not be pulled. 
We have tested it with the stable 4.6 release and also with a nightly release.

Images can not be pulled  and the docker client says: manifest not found.
I suspect it has something to do with the error right after issueing the mirroring command.

```
I1202 13:50:31.067742   80981 verify.go:472] not found
I1202 13:50:31.653797   80981 verify.go:472] not found
warning: An image was retrieved that failed verification: unable to locate a valid signature for one or more sources
```

**Comment by vrutkovs** [comment] 2020-12-03 08:22
Dupe of #402?

**Closed** 2020-12-03 08:41 UTC
