### ISSUE TITLE
CRC fails to start with 'Failed to renew TLS certificates'

### ISSUE THREAD

**Issue by everflux** [openshift/okd#1124] opened 2022-02-26 21:55 UTC
**Describe the bug**
CRC fails to setup cluster on linux kvm

**Version**
CodeReady Containers version: 1.31.2-OKD+24595e3e
OpenShift version: 4.8.0-0.okd-2021-10-24-061736 (embedded in executable)

**How reproducible**
100%

**Log bundle**

```
INFO Checking if running as non-root              
INFO Checking if running inside WSL2              
INFO Checking if crc-admin-helper executable is cached 
INFO Checking for obsolete admin-helper executable 
INFO Checking if running on a supported CPU architecture 
INFO Checking minimum RAM requirements            
INFO Checking if crc executable symlink exists    
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if active user/process is currently part of the libvirt group 
INFO Checking if libvirt daemon is running        
INFO Checking if a supported libvirt version is installed 
INFO Checking if crc-driver-libvirt is installed  
INFO Checking crc daemon systemd socket units     
INFO Checking if AppArmor is configured           
INFO Checking if systemd-networkd is running      
INFO Checking if NetworkManager is installed      
INFO Checking if NetworkManager service is running 
INFO Checking if dnsmasq configurations file exist for NetworkManager 
INFO Checking if the systemd-resolved service is running 
INFO Checking if /etc/NetworkManager/dispatcher.d/99-crc.sh exists 
INFO Checking if libvirt 'crc' network is available 
INFO Checking if libvirt 'crc' network is active  
INFO Loading bundle: crc_libvirt_4.8.0-0.okd-2021-10-24-061736... 
INFO Creating CodeReady Containers VM for OpenShift 4.8.0-0.okd-2021-10-24-061736... 
INFO Generating new SSH Key pair...               
INFO Generating new password for the kubeadmin user 
INFO Starting CodeReady Containers VM for OpenShift 4.8.0-0.okd-2021-10-24-061736... 
INFO CodeReady Containers instance is running with IP 192.168.130.11 
INFO CodeReady Containers VM is running           
INFO Updating authorized keys...                  
INFO Check internal and public DNS query...       
INFO Check DNS query from host...                 
INFO Verifying validity of the kubelet certificates... 
INFO Starting OpenShift kubelet service           
INFO Kubelet client certificate has expired, renewing it... [will take up to 8 minutes] 
INFO Kubelet serving certificate has expired, waiting for automatic renewal... [will take up to 8 minutes] 
Failed to renew TLS certificates: please check if a newer CodeReady Containers release is available: Temporary error: certificate /var/lib/kubelet/pki/kubelet-server-current.pem still expired (x59)
$ crc status
CRC VM:          Running
OpenShift:       Unreachable (v4.8.0-0.okd-2021-10-24-061736)
Disk Usage:      14.59GB of 32.74GB (Inside the CRC VM)
Cache Usage:     17.9GB
```

**Comment by vrutkovs** [comment] 2022-02-27 06:49
Dupe of #1123

**Closed by vrutkovs** 2022-02-27 06:49 UTC
