### ISSUE TITLE
Tried one more time to upgrade 4.5 > 4.6

### ISSUE THREAD

**Issue by johnlongo** [openshift/okd#414] opened 2020-12-05 23:02 UTC
**Tried one more time to upgrade 7.5 > 7.6.**

**The Nodes have been upgraded (see attached).**

**But after waiting for hour and half authentication, console , monitoring & operator-lifecycle-manager-packageserver operators seem stalled (see below)**

**I generated a log bundle and took snapshots (oc get nodes & oc get operators) of the cluster state.
The site didn't allow me to upload the full tar bundle, so I broke it up into individual zip file**

**NOTE: operator-lifecycle-manager-packageserver seems to keep restarting every few seconds** 

<img width="1173" alt="Upgrade_snapshot_2" src="https://user-images.githubusercontent.com/23619505/101267053-deb8c980-3722-11eb-9867-13433f81c15c.png">

<img width="1173" alt="Upgrade_snapshot_1" src="https://user-images.githubusercontent.com/23619505/101267055-e2e4e700-3722-11eb-88b2-73111ebd2d97.png">

[bootstrap.zip](https://github.com/openshift/okd/files/5647992/bootstrap.zip)

[okd4-control-plane-0.okd4-2.apptecinc.com.zip](https://github.com/openshift/okd/files/5647994/okd4-control-plane-0.okd4-2.apptecinc.com.zip)

[okd4-control-plane-1.okd4-2.apptecinc.com.zip](https://github.com/openshift/okd/files/5647995/okd4-control-plane-1.okd4-2.apptecinc.com.zip)

[okd4-control-plane-3.okd4-2.apptecinc.com.zip](https://github.com/openshift/okd/files/5647996/okd4-control-plane-3.okd4-2.apptecinc.com.zip)

[failed-units.zip](https://github.com/openshift/okd/files/5647999/failed-units.zip)
[rendered-assets.zip](https://github.com/openshift/okd/files/5648001/rendered-assets.zip)

[resources.zip](https://github.com/openshift/okd/files/5648002/resources.zip)
[unit-status.zip](https://github.com/openshift/okd/files/5648003/unit-status.zip)

**Comment by johnlongo** [comment] 2020-12-05 23:07
HAPROXY Reporting everything is running

<img width="1102" alt="Upgrade_snapshot_3" src="https://user-images.githubusercontent.com/23619505/101267259-b29e4800-3724-11eb-83a3-a5035c5ec06c.png">

**Comment by johnlongo** [comment] 2020-12-06 00:10
Nothing has changed in over three hours

<img width="1173" alt="Upgrade_snapshot_4" src="https://user-images.githubusercontent.com/23619505/101268087-820edc00-372d-11eb-9b66-2cba95350a14.png">

**Comment by johnlongo** [comment] 2020-12-06 01:29
**After 4 Plus Hours, no change to Operator status.**
**Going to shutdown the cluster and restart and see what happens**

<img width="1173" alt="Upgrade_snapshot_5" src="https://user-images.githubusercontent.com/23619505/101269077-96a4a180-3738-11eb-8ac2-561f04beadbe.png">

**Comment by johnlongo** [comment] 2020-12-06 04:12
**ShutDown & Restarted The Cluster without any difference.**

**All the nodes come up and are in the ready state.**
**But the same operators are stalled.**
**I created another log bundle and like before needed to break it up to upload**
**Going to restore my cluster back to 7.5 and wait for a solution**

<img width="1239" alt="Upgrade_snapshot_6" src="https://user-images.githubusercontent.com/23619505/101271207-bba40f00-374e-11eb-8726-d034768fc045.png">

<img width="1101" alt="Upgrade_snapshot_7" src="https://user-images.githubusercontent.com/23619505/101271211-c068c300-374e-11eb-8226-bda46de1f1f1.png">

[bootstrap.tar.gz](https://github.com/openshift/okd/files/5648259/bootstrap.tar.gz)

[okd4-control-plane-0.okd4-2.apptecinc.com.tar.gz](https://github.com/openshift/okd/files/5648260/okd4-control-plane-0.okd4-2.apptecinc.com.tar.gz)

[okd4-control-plane-1.okd4-2.apptecinc.com.tar.gz](https://github.com/openshift/okd/files/5648261/okd4-control-plane-1.okd4-2.apptecinc.com.tar.gz)

[okd4-control-plane-3.okd4-2.apptecinc.com.tar.gz](https://github.com/openshift/okd/files/5648262/okd4-control-plane-3.okd4-2.apptecinc.com.tar.gz)

[rendered-assets.tar.gz](https://github.com/openshift/okd/files/5648263/rendered-assets.tar.gz)

[resources.tar.gz](https://github.com/openshift/okd/files/5648264/resources.tar.gz)

[unit-status.tar.gz](https://github.com/openshift/okd/files/5648265/unit-status.tar.gz)

[failed-units.txt](https://github.com/openshift/okd/files/5648267/failed-units.txt)

**Comment by jomeier** [comment] 2020-12-09 13:09
I guess you mean you tried to upgrade from OKD 4.5 > OKD 4.6 ?

**Comment by johnlongo** [comment] 2020-12-10 00:14
I tried and restored and then tried again and restored, this was my last shot at it.

**Comment by grmhay** [comment] 2020-12-12 03:21
I had the exact same behavior as described here multiple times with fresh installs of 4.6.0-0.okd-2020-11-27-200126 on bare metal. Exact behavior as above each time.

**Comment by johnlongo** [comment] 2020-12-15 06:36
Tried the newest release (see below), same issue authentication, console , monitoring never comes up

oc adm upgrade --force --to=4.5.0-0.okd-2020-10-15-235428 --allow-upgrade-with-warnings

**Comment by narcoticfresh** [comment] 2020-12-23 10:09
I was stupid to start this update on our cluster without doing an etcd backup.. is there anyway to recover from this without re-setup'ing the cluster? if a new release comes out? or is there any workaround?

**Comment by johnlongo** [comment] 2020-12-23 11:49
I backup the whole cluster, it was pretty easy to get back to 4.5. Went through this exercise at least 4 times. I also have two clusters running. one where I have my code running (cluster-1) and the other where I do stupid stuff like click the upgrade button.

**Comment by narcoticfresh** [comment] 2020-12-23 12:30
@johnlongo 
> and the other where I do stupid stuff like click the upgrade button.

indeed a stupid thing to do it seems - sadly i'm not in the position to have a second "try it out first" cluster ;-/

you think it's "safe" to go from this broken state (update `Unable to apply 4.6.0-0.okd-2020-12-12-135354` and not progressing) and force a downgrade back to my previous release (`4.5.0-0.okd-2020-10-15-235428`) without having any backup?

well, i can at least back up this broken state now and restore that back i guess..

when you say "backup the whole cluster" - you mean the etcd backup or what is your procedure?

**Comment by johnlongo** [comment] 2020-12-23 13:27
I'm really not the person to ask, I don't have that much background when it comes to OKD I don't want to give you the wrong info. I would open up a new thread and ask that question and see what comes out of that.

**Comment by vrutkovs** [comment] 2020-12-23 22:33
Dupe of https://github.com/openshift/okd/issues/430 - 4.5 -> 4.6 upgrade with OpenshiftSDN is currently broken

**Closed by vrutkovs** 2020-12-23 22:33 UTC
