### ISSUE TITLE
Bootstrap Node is not serving ignition files.  HTTP 500 error.  OKD 4.5 UPI & FCOS 32

### ISSUE THREAD

**Issue by cgruver** [openshift/okd#239] opened 2020-07-01 17:30 UTC
OKD Version: 4.5.0-0.okd-2020-06-29-110348
FCOS Version: 32.20200615.3.0 (stable)

BootKube logs stop at:

```
Jul 01 17:11:14 okd4-bootstrap.deadpool.od4apps.com bootkube.sh[6440]: "99_openshift-machineconfig_99-worker-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-worker-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"
Jul 01 17:11:15 okd4-bootstrap.deadpool.od4apps.com bootkube.sh[6440]: Created "99_openshift-machineconfig_99-master-disable-mitigations.yaml" machineconfigs.v1.machineconfiguration.openshift.io/99-master-disable-mitigations -n
Jul 01 17:11:15 okd4-bootstrap.deadpool.od4apps.com bootkube.sh[6440]: Created "99_openshift-machineconfig_99-master-ssh.yaml" machineconfigs.v1.machineconfiguration.openshift.io/99-master-ssh -n
Jul 01 17:11:15 okd4-bootstrap.deadpool.od4apps.com bootkube.sh[6440]: Created "99_openshift-machineconfig_99-worker-disable-mitigations.yaml" machineconfigs.v1.machineconfiguration.openshift.io/99-worker-disable-mitigations -n
Jul 01 17:11:15 okd4-bootstrap.deadpool.od4apps.com bootkube.sh[6440]: Created "99_openshift-machineconfig_99-worker-ssh.yaml" machineconfigs.v1.machineconfiguration.openshift.io/99-worker-ssh -n
```

Master is waiting for ignition:

```
[   ***] A start job is running for Ignition (fetch) (14min 9s / no limit)
[***   ] A start job is running for Ignition (fetch) (14min 12s / no limit)
[***   ] A start job is running for Ignition (fetch) (14min 17s / no limit)
[  *** ] A start job is running for Ignition (fetch) (14min 20s / no limit)
[***   ] A start job is running for Ignition (fetch) (14min 24s / no limit)
```

HTTP 500 error from Bootstrap Node

```
curl --insecure -v https://api-int.okd4-lab.deadpool.od4apps.com:22623/config/master
* About to connect() to api-int.okd4-lab.deadpool.od4apps.com port 22623 (#0)
*   Trying 10.250.220.110...
* Connected to api-int.okd4-lab.deadpool.od4apps.com (10.250.220.110) port 22623 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=api-int.okd4-lab.deadpool.od4apps.com
* 	start date: Jul 01 16:46:52 2020 GMT
* 	expire date: Jun 29 16:46:54 2030 GMT
* 	common name: api-int.okd4-lab.deadpool.od4apps.com
* 	issuer: CN=root-ca,OU=openshift
> GET /config/master HTTP/1.1
> User-Agent: curl/7.29.0
> Host: api-int.okd4-lab.deadpool.od4apps.com:22623
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Length: 0
< Date: Wed, 01 Jul 2020 17:15:58 GMT
< 
* Connection #0 to host api-int.okd4-lab.deadpool.od4apps.com left intact
```

[log-bundle-20200701131851.tar.gz](https://github.com/openshift/okd/files/4859395/log-bundle-20200701131851.tar.gz)

**Comment by vrutkovs** [comment] 2020-07-01 17:40
```
E0701 17:14:48.888053       1 api.go:131] failed to translate {master} config: failed to convert Ignition config spec v2 to v3: unable to convert Ignition spec v2 config to v3: Config has conflicting inodes: "File: /etc/containers/registries.conf" and "File: /etc/containers/registries.conf".  All files, directories and links must specify a unique `path`.
```

That's a dupe of #237, should be fixed by https://github.com/openshift/machine-config-operator/pull/1889

**Closed** 2020-07-01 17:43 UTC

**Comment by imunic** [comment] 2020-07-29 15:35
Not sure if it's the same issue, but it's the same error I'm still getting, and can't fetch the ignition file from the bootstrap node.

```
[core@bootstrap ~]$ curl --insecure -I https://api-int.dokd.ag04.io:22623/config/master
HTTP/2 500
content-length: 0
date: Wed, 29 Jul 2020 15:28:47 GMT
```

Was it resolved for the GA release?

Tried with both:
4.5.0-0.okd-2020-07-14-153706-ga

**Comment by vrutkovs** [comment] 2020-07-29 15:42
```
I0729 15:28:43.836646       1 bootstrap_server.go:64] reading file "/etc/mcs/bootstrap/machine-pools/master.yaml"
I0729 15:28:43.840066       1 bootstrap_server.go:84] reading file "/etc/mcs/bootstrap/machine-configs/rendered-master-c0a8758d72533a2c5cd1373e7f9a3124.yaml"
E0729 15:28:47.648191       1 api.go:133] failed to prepare {master} config: config version not supported: 7.69.1
I0729 15:28:57.187681       1 api.go:111] Pool master requested by address:"95.217.153.188:45434" User-Agent:"curl/7.69.1"
```

You'd need to set a different user-agent so that it would contain Ignition version, e.g. `Ignition/3.1.0`

**Comment by LorbusChris** [comment] 2020-07-29 18:03
`Ignition/2.3.0` will work (3.1.0 is the config spec version, not the Ignition binary version that's in the User Agent).

**Comment by imunic** [comment] 2020-07-30 11:22
Thanks, that did the trick! I was using curl in a wrong way to debug a seemingly broken bootstrap node, turns out the cloud providers load balancer was broken.
