### ISSUE TITLE
OKD 4.6  FCOS 33.20210104.3.0 Update failed

### ISSUE THREAD

**Issue by AleftinaT** [openshift/okd#582] opened 2021-04-05 09:06 UTC
**Describe the bug**
I tried to update  to 4.6.0-0.okd-2021-01-23-132511. Two masters were updated OK, one master and worker became stuck on FCOS upgrade with error:
`Rolling back applied changes to OS due to error: failed to execute rpm-ostree ["update" "--install" "qemu-guest-agent" "--uninstall" "open-vm-tools"] : exit status 1`
I uninstalled the open-vm-tools package, and the worker got at desired config state, which included the old FCOS version. After reboot the node was in Ready state, FCOS version was not changed. Then I manually changed the  desired config annotation of worker to the new one.
Now in machine-config-daemon logs i see
`Marking Degraded due to: unexpected on-disk state validating against rendered-worker-e323ab3a4c42f03007753a7ab3248b20: expected target osImageURL "quay.io/openshift/okd-content@sha256:64f1cc9663a57d3bb9cc413502c9ccc04097be2033cf726aaf535e0e7ad5b5c4", have "quay.io/openshift/okd-content@sha256:880f0e1cfb4a5c8c22dd9cbb54c2294bcbbcfef30b126d5c04d3160f84438c6a"`

**Version**
Update 4.6.0-0.okd-2020-11-27-200126 to 4.6.0-0.okd-2021-01-23-132511 

**Log bundle**
https://drive.google.com/file/d/1vAYmVqo1gr4GmUAvIOvmZ993M3LEVwxE/view?usp=sharing

**Comment by AleftinaT** [comment] 2021-04-05 11:31
```
sed -i 's;enabled=0;enabled=1;g' /etc/yum.repos.d/fedora{,-updates,-modular,-cisco-openh264,-updates-modular,-updates-archive}.repo
systemctl reboot
/run/bin/machine-config-daemon pivot quay.io/openshift/okd-content@sha256:64f1cc9663a57d3bb9cc413502c9ccc04097be2033cf726aaf535e0e7ad5b5c4
```
helped

**Comment by vrutkovs** [comment] 2021-04-06 07:51
Probably a dupe of #398

**Closed by vrutkovs** 2021-04-06 07:51 UTC
