### ISSUE TITLE
Which okd version is LTS?

### ISSUE THREAD

**Issue by kkk25641463** [openshift/okd#592] opened 2021-04-13 09:45 UTC
Why not provide an LTS version for the production environment such as OKD 4.6.

I think OKD’s current stable version management should add support for branches.At present, the components for OKD 4.6 have entered the official version,k8s is 1.19.4,coreos is 33.20210314.3,and no stable version was submitted for long-term support in the bug update after February 14.OKD 4.7,there are still problems in production as a stable version.

**Comment by vrutkovs** [comment] 2021-04-13 09:46
>Why not provide an LTS version

Sure, who's going to maintain it?

**Comment by LorbusChris** [comment] 2021-04-13 15:25
OKD is based on Fedora CoreOS, which only has one stable stream. Although the OS can be treated almost like an implementation detail, there are still adjustments needed for the cluster and the base OS to work together seamlessly for each version. Due to this, providing multiple supported release streams for OKD is not possible without a significant amount of additional work if it is intended to not regress on the level of testing that is done for the current version today (this includes the (re-)building and testing of both the OS and all cluster components individually, as well as a release payload bundle tested in e2e tests on target platforms).

Until someone steps up and shows sincere interest in providing this work, I'm going to close this issue.

**Closed by LorbusChris** 2021-04-13 15:25 UTC

**Comment by aelbarkani** [comment] 2021-04-22 20:01
The question would be rather: is OKD stable enough to run in production ? I love Openshift, but to be honest, at each upgrade I cross fingers and pray to all gods of the universe to not have any issues. Unfortunately, my prays are not always listened I must say... I hope that will change in the foreseeable future, because I think honestly that OKD has good potential.

**Comment by nate-duke** [comment] 2021-04-23 12:12
At the risk of this comment being marked as off-topic as well. I'll say that I echo my colleague @aelbarkani's thoughts above. I have great hopes for the production use of OKD at my organization. Having stable upgrades is part of that. I'd hope that the powers that be who manage the OKD project as it exists today share that hope even if they cannot voice that hope.

**Comment by vrutkovs** [comment] 2021-04-23 13:00
1. This whole ticket is not a bug report, but a discussion topic. Using issue tracker for that is not a great idea. See https://github.com/openshift/okd/blob/master/FAQ.md#where-do-i-seek-support
2. Questions like "Is OKD stable enough" or "Why not add LTS stream" are very subjective and don't really benefit the project unless its "I'm ready to help maintaining LTS / providing guarantees for OKD stability"
