### ISSUE TITLE
Unable to retrieve available updates for OKD 4.6 

### ISSUE THREAD

**Issue by bohdan-udovenko-cognite** [openshift/okd#675] opened 2021-06-09 11:38 UTC
**Describe the bug**
OKD can't fetch recent versions since Jun 8, 7:11 pm
DNS name is not resolved either from my laptop https://origin-release.svc.ci.openshift.org/ 
 
 Unable to retrieve available updates: Get "https://origin-release.svc.ci.openshift.org/graph?arch=amd64&channel=stable-4&id=3f448bee-b287-43ae-a418-bc5a2598b733&version=4.6.0-0.okd-2021-02-14-205305": dial tcp: lookup origin-release.svc.ci.openshift.org on 169.254.169.254:53: no such host

**Version**
4.6.0-0.okd-2021-02-14-205305

**How reproducible**
Always

**Log bundle**

**Comment by vrutkovs** [comment] 2021-06-09 12:14
Dupe of #674

**Closed by vrutkovs** 2021-06-09 12:14 UTC
