### ISSUE TITLE
Image signature verifying error when upgrading to 4.7.0-0.okd-2021-04-24-103438 and laters

### ISSUE THREAD

**Issue by lukasz-e** [openshift/okd#667] opened 2021-06-07 16:14 UTC
**Describe the bug**

Starting upgrade (from 4.7.0-0.okd-2021-04-24-103438) to latest okd versions (4.7.0-0.okd-2021-04-24-103438, 4.7.0-0.okd-2021-05-22-050008, 4.7.0-0.okd-2021-05-22-050008) results image signature verification error.
When I forced upgrade (tried for 4.7.0-0.okd-2021-04-24-103438, next versions - not yet), upgrade succeeds.
Upgrades up to 4.7.0-0.okd-2021-04-11-124433 went without this problem.

**Version**

Bare metal installation.
Original installation was some 4.5 version, upgraded several times, currently 4.7.0-0.okd-2021-04-24-103438, but the same problem I had when upgrading to 4.7.0-0.okd-2021-04-24-103438 from 4.7.0-0.okd-2021-04-11-124433

**How reproducible**

Always

**Log bundle**
I am attaching cluster version operator log and clusterVersion resource with upgrade history.

[clusterversion.txt](https://github.com/openshift/okd/files/6610522/clusterversion.txt)
[cluster_version_operator.log](https://github.com/openshift/okd/files/6610531/cluster_version_operator.log)

**Comment by vrutkovs** [comment] 2021-06-08 07:44
Dupe of https://github.com/openshift/okd/issues/605

See https://github.com/openshift/okd/blob/master/KNOWN_ISSUES.md#invalid-signature-error-when-attempting-cluster-updates

**Closed by vrutkovs** 2021-06-08 07:44 UTC
