### ISSUE TITLE
openshift installer missing libs (openshift-install-linux-4.7.0-0.okd-2021-06-13-090745.tar.gz)

### ISSUE THREAD

**Issue by fortinj66** [openshift/okd#689] opened 2021-06-13 20:14 UTC
**Describe the bug**
When I run the openshift installer it fails with the following:

```
./openshift-install --help
./openshift-install: error while loading shared libraries: libvirt-lxc.so.0: cannot open shared object file: No such file or directory

This is for a vSphere IPI Initial install

```

**Version**
openshift-install-linux-4.7.0-0.okd-2021-06-13-090745.tar.gz

**How reproducible**
100%

**Details**

```
# cat /etc/fedora-release
Fedora release 33 (Thirty Three)

# ldd ././openshift-install
        linux-vdso.so.1 (0x00007ffce70a3000)
        libvirt-lxc.so.0 => not found
        libvirt-qemu.so.0 => not found
        libvirt.so.0 => not found
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f66e3ab0000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f66e3aa9000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f66e38de000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f66e3adf000)
```

**Comment by vrutkovs** [comment] 2021-06-13 20:56
Dupe of https://github.com/openshift/okd/issues/535

See https://github.com/openshift/okd/pull/633 for workaround

**Closed by vrutkovs** 2021-06-13 20:56 UTC

**Comment by fortinj66** [comment] 2021-06-13 20:59
Thanks @vrutkovs !

**Comment by fengzhigu2000** [comment] 2022-05-17 06:38
how to deal with it
