### ISSUE TITLE
[okd 4.4] Update Cluster Failure, Update Status:  Error retrieving

### ISSUE THREAD

**Issue by klzsysy** [openshift/okd#83] opened 2020-02-13 15:30 UTC
hi:

I successfully installed before the cluster #59 ，But you can't update.

https://origin-release.svc.ci.openshift.org/  see:
```
oc patch clusterversion/version --patch '{"spec":{"upstream":"https://origin-release.svc.ci.openshift.org/graph"}}' --type=merge
```

![image](https://user-images.githubusercontent.com/3226923/74449611-c2a81b00-4eb7-11ea-81c1-84f2b5a98e65.png)

but no wrok

![image](https://user-images.githubusercontent.com/3226923/74449725-ed926f00-4eb7-11ea-9833-b9c224338f6f.png)

---
I want to know how to update to the latest version？  In addition to reinstall

thanks！

---
> additional : developer UI why do you want to change this, instead of 3.x before style, can you tell me why? Really not used to

**Comment by vrutkovs** [comment] 2020-02-13 17:01
Duplicate of #23

**Closed by vrutkovs** 2020-02-13 17:01 UTC
