### ISSUE TITLE
4.9 IPI VMware Installation Failure, Cluster operator machine-config Degraded. 

### ISSUE THREAD

**Issue by molupini** [openshift/okd#1076] opened 2022-01-25 21:02 UTC
**Describe the bug**

Installation of OKD 4.9.0-0.okd-2022-01-14-230113 IPI Cluster Failing on multiple attempts
```
ERROR Cluster operator machine-config Degraded is True with RequiredPoolsFailed: 
Unable to apply 4.9.0-0.okd-2022-01-14-230113: timed out waiting for the condition during syncRequiredMachineConfigPools: 
error pool master is not ready, retrying. Status: (pool degraded: true total: 3, ready 0, updated: 0, unavailable: 3)
```
Similar to UPI open issue https://github.com/openshift/okd/issues/963

**Version**

Version
4.9.0-0.okd-2022-01-14-230113
IPI
VMWARE

**How reproducible**

100%

**Log bundle**

https://drive.google.com/file/d/15aPZyE2gSCY0DHda7KoAl_zP1ZJP6uTS/view?usp=sharing

**Comment by molupini** [comment] 2022-01-25 21:09
Ruling out the possibility of this being environmental as the latest release of openshift "ipi, vmware" is deployed successfully.

**Comment by vrutkovs** [comment] 2022-01-25 22:00
Dupe of #963 maybe?

**Comment by vrutkovs** [comment] 2022-01-26 08:54
No valid hostname used - bootstrap's hostname is `localhost`

**Closed by vrutkovs** 2022-01-26 08:54 UTC
