### ISSUE TITLE
AWS installation fails with OKD 4.3 versions

### ISSUE THREAD

**Issue by parthakom2** [openshift/okd#132] opened 2020-04-07 15:03 UTC
Tried the okd installer on AWS with following 4.3 versions. 

4.3.0-0.okd-2020-04-07-001422
4.3.0-0.okd-2020-04-06-000504
4.3.0-0.okd-2020-04-03-020948
4.3.0-0.okd-2019-11-15-182656

./oc adm release extract --tools <okd release versions>

openshift-install create cluster - all parameters supplied with the dummy pull secret - `{"auths":{"fake":{"auth": "bar"}}}` 

This is the error encountered

```
INFO Creating infrastructure resources...         
INFO Waiting up to 30m0s for the Kubernetes API at https://<hostname redacted>:6443... 
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get https://<hostname redacted>:6443/apis/config.openshift.io/v1/clusteroperators: dial tcp <redacted>:6443: connect: connection refused 
INFO Pulling debug logs from the bootstrap machine 
INFO Bootstrap gather logs captured here "log-bundle-20200407133204.tar.gz" 
FATAL Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded 
````

**Comment by vrutkovs** [comment] 2020-04-07 15:08
Duplicate of #42

**Closed by vrutkovs** 2020-04-07 15:08 UTC
