### ISSUE TITLE
Just in stalled a fresh 4.7 cluster on vsphere 6.7 but have an odd problem

### ISSUE THREAD

**Issue by johnlongo** [openshift/okd#768] opened 2021-07-15 03:17 UTC
Just installed a fresh 4.7 (4.7.0-0.okd-2021-07-03-190901) cluster on vSphere 6.7 but have an odd problem I never had before. when I create an application deployment and it tries to ping the registry it's using an external dns host 192.168.1.40 (see error below) and not the internal okd dns service. I never added a dns entry in the external host before, did something change since the last time a created a cluster.
Please advise.

Failed to pull image "image-registry.openshift-image-registry.svc:5000/openshift-alertmanager/openshift-alertmanager@sha256:4e4d4f60936edcf15cc978fa1f72cfa939ae37adbbb14e1dc99cc6e98b7a4759": rpc error: code = Unknown desc = error pinging docker registry image-registry.openshift-image-registry.svc:5000: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": dial tcp: lookup image-registry.openshift-image-registry.svc on 192.168.1.40:53: no such host

**Comment by vrutkovs** [comment] 2021-07-15 07:10
Dupe of #648?

**Closed by vrutkovs** 2021-07-15 07:10 UTC
