### ISSUE TITLE
[Azure] Installer terminates with "The source blob ... is not a page blob"

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#169] opened 2020-05-06 15:23 UTC
Hi,

I installed the openshift-installer from beta4 

```
oc adm release extract --tools quay.io/openshift/okd:4.4.0-0.okd-2020-04-21-163702-beta4
```

I started the openshift-install process in an Azure VM. I always get an error message.

```
ERROR
ERROR Warning: "resource_group_name": [DEPRECATED] This field has been deprecated and is no longer used - will be removed in 2.0 of the Azure Provider
ERROR
ERROR   on ../../../tmp/openshift-install-529145828/main.tf line 163, in resource "azurerm_storage_container" "vhd":
ERROR  163: resource "azurerm_storage_container" "vhd" {
ERROR
ERROR (and 3 more similar warnings elsewhere)
ERROR
ERROR
ERROR Error: compute.ImagesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The source blob https://clusters033b.blob.core.windows.net/vhd/rhcoss033b.vhd is not a page blob." Target="disks"
ERROR
ERROR   on ../../../tmp/openshift-install-529145828/main.tf line 179, in resource "azurerm_image" "cluster":
ERROR  179: resource "azurerm_image" "cluster" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform
```

Greetings,

Josef

**Version**
Beta 4

**How reproducible**
100%

**Comment by vrutkovs** [comment] 2020-05-06 15:53
dupe of https://github.com/openshift/okd/issues/48?

**Comment by vrutkovs** [comment] 2020-05-06 16:06
Oops, I see, a wrong link. There's a typo in rhcos.json

**Comment by jomeier** [comment] 2020-05-06 20:42
https://github.com/openshift/installer/pull/3563

**Closed** 2020-05-08 15:06 UTC
Labels: platform/azure

**Comment by emersonramos** [comment] 2020-07-27 15:01
I had the same problem. I tried others OKD versions too.

Anybody know how to correct?
