### ISSUE TITLE
Cannot create new worker node after upgrade from 4.7.0-0.okd-2021-06-04-191031 - VMWare IPI

### ISSUE THREAD

**Issue by aalgera** [openshift/okd#699] opened 2021-06-17 21:27 UTC
After upgrading  from 4.7.0-0.okd-2021-06-04-191031 to 4.7.0-0.okd-2021-06-13-090745, I am not able to create new worker nodes. I do manage to acess the machine and find that the configuration of this machine halts due to an error in _machine-config-daemon-firstboot.service_.

In the logs of this service I found the following error:
`jun 17 20:54:35 localhost machine-config-daemon[2363]: I0617 20:54:35.639020    2363 rpm-ostree.go:261] Running captured: rpm-ostree update --install NetworkManager-ovs --install glusterfs --install glusterfs-fuse --install qemu-guest-agent
jun 17 20:54:36 localhost machine-config-daemon[2363]: I0617 20:54:36.370100    2363 update.go:439] Rolling back applied changes to OS due to error: error running rpm-ostree update --install NetworkManager-ovs --install glusterfs --install glusterfs-fuse --install qemu-guest-agent: error: "NetworkManager-ovs" is already provided by: NetworkManager-ovs-1:1.30.4-1.fc34.x86_64. Use --allow-inactive to explicitly require it.
jun 17 20:54:36 localhost machine-config-daemon[2363]: : exit status 1
`
I did a clean install starting with 4.7.0-0.okd-2021-05-22-050008, updating to 4.7.0-0.okd-2021-06-04-191031 and then to  4.7.0-0.okd-2021-06-13-090745. I didn't see this problem in 4.7.0-0.okd-2021-05-22-050008 and 4.7.0-0.okd-2021-06-04-191031

**Version**
4.7.0-0.okd-2021-06-13-090745 -IPI VMWare

**How reproducible**
100% reproducible, I did a clean install of

**Log bundle**

**Comment by vrutkovs** [comment] 2021-06-17 21:29
Relevant Slack thread: https://kubernetes.slack.com/archives/C6BRQSH2S/p1623781138240100

Interestingly enough, I can't reproduce it on clean install.

**Comment by aalgera** [comment] 2021-06-17 21:41
I started with 4.7.0-0.okd-2021-05-22-050008 which still uses FCOS-33.

**Comment by Udbv** [comment] 2021-06-18 07:59
@aalgera you could check MachineConfigs/99-worker-okd-extensions, and if  `NetworkManager-ovs` is present there - remove

**Comment by vrutkovs** [comment] 2021-06-18 11:22
This should be resolved by https://github.com/openshift/okd-machine-os/pull/145

**Comment by uselessidbr** [comment] 2021-06-18 22:16
> @aalgera you could check MachineConfigs/99-worker-okd-extensions, and if `NetworkManager-ovs` is present there - remove

I've removed all extensions and then MCO turned into DEGRATED STATE because of the existing nodes not being able to uninstall the packages as it wasn't requested. As the node Isn't in production yet I just removed the node and then MCO reconciliated. Although I think there's a RedHat KB that provides a workaround to bypass it without removing the node.

After that I just scaled up new nodes with success.

**Comment by vrutkovs** [comment] 2021-06-19 20:54
Verified the scale up works again, installed 06-04, upgraded to 06-13 and then to 2021-06-19-191547 nightly. Upgrade worked correctly with 99-okd-master/worker-extensions and machineset can be scaled up.

**Comment by vrutkovs** [comment] 2021-06-20 07:17
Fixed in https://amd64.origin.releases.ci.openshift.org/releasestream/4-stable/release/4.7.0-0.okd-2021-06-19-191547, please reopen if this still happens

**Closed by vrutkovs** 2021-06-20 07:17 UTC

**Comment by yaroslavkasatikov** [comment] 2021-07-14 09:50
Hi @vrutkovs 

we have this sissue again in https://github.com/openshift/okd/issues/441
