### ISSUE TITLE
The OC binary downloaded via the web console is very old

### ISSUE THREAD

**Issue by Reamer** [openshift/okd#731] opened 2021-07-01 14:14 UTC
**Describe the bug**
You can download the OC binary via the web console. The downloaded version is very old.
Step-by-Step:
-> Login to your web console
-> `?` (right corner) -> `Command Line Tools`
-> `Download oc for Linux for x86_64`
-> Untar the downloaded tar file
-> run `./oc version`
Example Output
```
./oc version
Client Version: v4.2.0-alpha.0-996-g9b9f77a
Server Version: 4.7.0-0.okd-2021-06-19-191547
Kubernetes Version: v1.20.0-1079+87cc9a4ade7ebe-dirty
```

**Version**
4.7.0-0.okd-2021-06-19-191547 vSphere UPI

**How reproducible**
100%

**Log bundle**
This should not be necessary.

**Comment by vrutkovs** [comment] 2021-07-01 14:29
Dupe of #447

`oc` itself is [fresh](https://github.com/openshift/oc/commits/9b9f77a), but it has a wrong version set. It uses latest tag, which is 4.2 instead of hardcoded release version in our CI

**Closed by vrutkovs** 2021-07-01 14:29 UTC
