### ISSUE TITLE
UPI on vsphere: Machine-Autoscaler does not work because of missing tag

### ISSUE THREAD

**Issue by philipp1992** [openshift/okd#364] opened 2020-10-23 06:59 UTC
OKD 4.5
vsphere 7.0

When scaling machines with the machineset, the machine gets created, but the  machine operator fails with the following error message:

„E1020 10:08:37.628961       1 actuator.go:50] chmuw-default-n9wrf error: failed to reconcile tags: GET https://vc4.domain.net/rest/com/vmware/cis/tagging/tag/id:c5: 404 Not Found
E1020 10:08:37.629002       1 controller.go:279] chmuw-default-n9wrf: error updating machine: failed to reconcile tags: GET https://vc4.domain.net/rest/com/vmware/cis/tagging/tag/id:c5: 404 Not Found”

The reason for this is, that the vsphere tag "c5 " (cluster_id), in the category "id", which is used by the operator, gets never created by the UPI installer.
We had to manually create the tag with terraform and then the machine-set is able to create nodes properly.

kind regards
Philipp

**Comment by vrutkovs** [comment] 2020-10-23 07:57
This seems to be a dupe of https://bugzilla.redhat.com/show_bug.cgi?id=1877281 in 4.6. Please clone it to 4.5 so that machine-api would be updated in 4.5 as well - and paste the bug number here.

Keeping it open to have a reference to bugzilla

**Comment by HaehnleinMar** [comment] 2020-12-09 13:02
I have this issue with IPI on vSphere. Should I open another issue?

**Comment by vrutkovs** [comment] 2021-02-03 14:10
Could you check if its resolved in OKD 4.6?

**Comment by HaehnleinMar** [comment] 2021-02-23 17:01
For me it's still logging `Failed to get tag`, but machines can be created again.

**Closed** 2021-07-25 02:05 UTC
Labels: lifecycle/rotten, platform/vsphere, triage/needs-verification
