### ISSUE TITLE
Problem with cluster update from version version   4.5.0-0.okd-2020-10-15-235428

### ISSUE THREAD

**Issue by Francua** [openshift/okd#459] opened 2021-01-07 08:21 UTC
Hello, I have got problem with cluster upgrade from wersion 4.5 to 4.6 stuck in 97%. All cluster operator were update without one ( machine-config)

```
oc get clusterversion
NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.5.0-0.okd-2020-10-15-235428   True        True          43h     Unable to apply 4.6.0-0.okd-2020-11-27-200126: the cluster operator machine-config has not yet successfully rolled out___
```

```
oc get co
NAME                                       VERSION                         AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.6.0-0.okd-2020-11-27-200126   True        False         False      41m
cloud-credential                           4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
cluster-autoscaler                         4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
config-operator                            4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
console                                    4.6.0-0.okd-2020-11-27-200126   True        False         False      11h
csi-snapshot-controller                    4.6.0-0.okd-2020-11-27-200126   True        False         False      41h
dns                                        4.6.0-0.okd-2020-11-27-200126   True        False         False      41h
etcd                                       4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
image-registry                             4.6.0-0.okd-2020-11-27-200126   True        False         False      46h
ingress                                    4.6.0-0.okd-2020-11-27-200126   True        False         False      42h
insights                                   4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
kube-apiserver                             4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
kube-controller-manager                    4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
kube-scheduler                             4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
kube-storage-version-migrator              4.6.0-0.okd-2020-11-27-200126   True        False         False      46h
machine-api                                4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
machine-approver                           4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
machine-config                             4.5.0-0.okd-2020-10-15-235428   False       True          True       41h
marketplace                                4.6.0-0.okd-2020-11-27-200126   True        False         False      41h
monitoring                                 4.6.0-0.okd-2020-11-27-200126   True        False         False      83m
network                                    4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
node-tuning                                4.6.0-0.okd-2020-11-27-200126   True        False         False      42h
openshift-apiserver                        4.6.0-0.okd-2020-11-27-200126   True        False         False      42h
openshift-controller-manager               4.6.0-0.okd-2020-11-27-200126   True        False         False      42h
openshift-samples                          4.6.0-0.okd-2020-11-27-200126   True        False         False      42h
operator-lifecycle-manager                 4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
operator-lifecycle-manager-catalog         4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
operator-lifecycle-manager-packageserver   4.6.0-0.okd-2020-11-27-200126   True        False         False      41h
service-ca                                 4.6.0-0.okd-2020-11-27-200126   True        False         False      8d
storage                                    4.6.0-0.okd-2020-11-27-200126   True        False         False      42h
```

```
oc describe co machine-config
Name:         machine-config
Namespace:    
Labels:       <none>
Annotations:  exclude.release.openshift.io/internal-openshift-hosted: true
API Version:  config.openshift.io/v1
Kind:         ClusterOperator
Metadata:
  Creation Timestamp:  2020-12-29T10:41:00Z
  Generation:          1
  Managed Fields:
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:exclude.release.openshift.io/internal-openshift-hosted:
      f:spec:
      f:status:
    Manager:      cluster-version-operator
    Operation:    Update
    Time:         2020-12-29T10:41:00Z
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
        f:extension:
          .:
          f:lastSyncError:
          f:master:
          f:worker:
        f:relatedObjects:
        f:versions:
    Manager:         machine-config-operator
    Operation:       Update
    Time:            2021-01-07T07:46:47Z
  Resource Version:  16854035
  Self Link:         /apis/config.openshift.io/v1/clusteroperators/machine-config
  UID:               aa3fb671-d9db-4a66-bd3a-08528af48bc4
Spec:
Status:
  Conditions:
    Last Transition Time:  2021-01-05T13:53:23Z
    Message:               Working towards 4.6.0-0.okd-2020-11-27-200126
    Status:                True
    Type:                  Progressing
    Last Transition Time:  2021-01-05T14:18:58Z
    Message:               Unable to apply 4.6.0-0.okd-2020-11-27-200126: timed out waiting for the condition during syncRequiredMachineConfigPools: pool master has not progressed to latest configuration: controller version mismatch for rendered-master-af023939b490b7090608e2581d5b9dc1 expected 5a9e6b4eedaf72ecc2534355173843e011f19765 has 57d3c165737944e8236ee6202391202e89e59aba: pool is degraded because nodes fail with "1 nodes are reporting degraded status on sync": "Node ocmasterc8-dev51.fortisbank.com.pl is reporting: \"failed to execute rpm-ostree [\\\"update\\\" \\\"--install\\\" \\\"glusterfs\\\" \\\"--install\\\" \\\"glusterfs-fuse\\\" \\\"--install\\\" \\\"open-vm-tools\\\" \\\"--install\\\" \\\"NetworkManager-ovs\\\"] : exit status 1\"", retrying
    Reason:                RequiredPoolsFailed
    Status:                True
    Type:                  Degraded
    Last Transition Time:  2021-01-05T13:51:15Z
    Message:               Cluster not available for 4.6.0-0.okd-2020-11-27-200126
    Status:                False
    Type:                  Available
    Last Transition Time:  2020-12-29T10:48:24Z
    Reason:                AsExpected
    Status:                True
    Type:                  Upgradeable
  Extension:
    Last Sync Error:  pool master has not progressed to latest configuration: controller version mismatch for rendered-master-af023939b490b7090608e2581d5b9dc1 expected 5a9e6b4eedaf72ecc2534355173843e011f19765 has 57d3c165737944e8236ee6202391202e89e59aba: pool is degraded because nodes fail with "1 nodes are reporting degraded status on sync": "Node ocmasterc8-dev51.fortisbank.com.pl is reporting: \"failed to execute rpm-ostree [\\\"update\\\" \\\"--install\\\" \\\"glusterfs\\\" \\\"--install\\\" \\\"glusterfs-fuse\\\" \\\"--install\\\" \\\"open-vm-tools\\\" \\\"--install\\\" \\\"NetworkManager-ovs\\\"] : exit status 1\"", retrying
    Master:           pool is degraded because nodes fail with "1 nodes are reporting degraded status on sync": "Node ocmasterc8-dev51.fortisbank.com.pl is reporting: \"failed to execute rpm-ostree [\\\"update\\\" \\\"--install\\\" \\\"glusterfs\\\" \\\"--install\\\" \\\"glusterfs-fuse\\\" \\\"--install\\\" \\\"open-vm-tools\\\" \\\"--install\\\" \\\"NetworkManager-ovs\\\"] : exit status 1\""
    Worker:           pool is degraded because nodes fail with "1 nodes are reporting degraded status on sync": "Node ocworkerc8-dev04.fortisbank.com.pl is reporting: \"failed to execute rpm-ostree [\\\"update\\\" \\\"--install\\\" \\\"glusterfs\\\" \\\"--install\\\" \\\"glusterfs-fuse\\\" \\\"--install\\\" \\\"open-vm-tools\\\" \\\"--install\\\" \\\"NetworkManager-ovs\\\"] : exit status 1\""
  Related Objects:
    Group:     
    Name:      openshift-machine-config-operator
    Resource:  namespaces
    Group:     machineconfiguration.openshift.io
    Name:      
    Resource:  machineconfigpools
    Group:     machineconfiguration.openshift.io
    Name:      
    Resource:  controllerconfigs
    Group:     machineconfiguration.openshift.io
    Name:      
    Resource:  kubeletconfigs
    Group:     machineconfiguration.openshift.io
    Name:      
    Resource:  containerruntimeconfigs
    Group:     machineconfiguration.openshift.io
    Name:      
    Resource:  machineconfigs
    Group:     
    Name:      
    Resource:  nodes
  Versions:
    Name:     operator
    Version:  4.5.0-0.okd-2020-10-15-235428
Events:       <none>_
```

One master and worker were in status NotReady,SchedulingDisabled. 

```
oc get nodes
NAME                                 STATUS                        ROLES    AGE   VERSION`
ocmasterc8-dev01.fortisbank.com.pl   Ready                         master   8d    v1.18.3
ocmasterc8-dev02.fortisbank.com.pl   Ready                         master   8d    v1.18.3
ocmasterc8-dev51.fortisbank.com.pl   NotReady,SchedulingDisabled   master   8d    v1.18.3
ocworkerc8-dev02.fortisbank.com.pl   Ready                         worker   8d    v1.18.3
ocworkerc8-dev03.fortisbank.com.pl   Ready                         worker   8d    v1.18.3
ocworkerc8-dev04.fortisbank.com.pl   Ready,SchedulingDisabled      worker   8d    v1.18.3
ocworkerc8-dev05.fortisbank.com.pl   Ready                         worker   8d    v1.18.3
ocworkerc8-dev06.fortisbank.com.pl   Ready                         worker   8d    v1.18.3
ocworkerc8-dev51.fortisbank.com.pl   Ready                         worker   8d    v1.18.3
ocworkerc8-dev52.fortisbank.com.pl   Ready                         worker   8d    v1.18.3
ocworkerc8-dev53.fortisbank.com.pl   Ready                         worker   8d    v1.18.3
ocworkerc8-dev54.fortisbank.com.pl   Ready                         worker   8d    v1.18.3
ocworkerc8-dev55.fortisbank.com.pl   Ready                         worker   8d    v1.18.3
ocworkerc8-dev56.fortisbank.com.pl   Ready                         worker   8d    v1.18.3
```

After "Mark as scheduable" they look fine.

```
oc get nodes
NAME                                 STATUS   ROLES    AGE   VERSION
ocmasterc8-dev01.fortisbank.com.pl   Ready    master   8d    v1.18.3 
ocmasterc8-dev02.fortisbank.com.pl   Ready    master   8d    v1.18.3
ocmasterc8-dev51.fortisbank.com.pl   Ready    master   8d    v1.18.3
ocworkerc8-dev02.fortisbank.com.pl   Ready    worker   8d    v1.18.3
ocworkerc8-dev03.fortisbank.com.pl   Ready    worker   8d    v1.18.3
ocworkerc8-dev04.fortisbank.com.pl   Ready    worker   8d    v1.18.3
ocworkerc8-dev05.fortisbank.com.pl   Ready    worker   8d    v1.18.3
ocworkerc8-dev06.fortisbank.com.pl   Ready    worker   8d    v1.18.3
ocworkerc8-dev51.fortisbank.com.pl   Ready    worker   8d    v1.18.3
ocworkerc8-dev52.fortisbank.com.pl   Ready    worker   8d    v1.18.3
ocworkerc8-dev53.fortisbank.com.pl   Ready    worker   8d    v1.18.3
ocworkerc8-dev54.fortisbank.com.pl   Ready    worker   8d    v1.18.3
ocworkerc8-dev55.fortisbank.com.pl   Ready    worker   8d    v1.18.3
ocworkerc8-dev56.fortisbank.com.pl   Ready    worker   8d    v1.18.3
```

**Version**
`version   4.5.0-0.okd-2020-10-15-235428 `

**Comment by vrutkovs** [comment] 2021-01-07 08:28
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by acsecengtesting** [comment] 2021-01-07 08:55
I am having the same symptoms apart from the upgrade not proceeding when I marked the nodes as schedulable.     Unable to apply 4.6.0-0.okd-2020-12-12-135354: timed out waiting for the condition during syncRequiredMachineConfigPools: pool master has not progressed to latest configuration: controller version mismatch for rendered-master-5a032982847665a0a7261dbf1ad27372 expected eb9778355a9020673e8ce9aee092cb98d80cde5e has 5a9e6b4eedaf72ecc2534355173843e011f19765: 0 (ready 0) out of 3 nodes are updating to latest configuration rendered-master-be834a6a05b0b65e63a1725d4dc447c2, retrying

I have tried rebuilding my cluster and retrying the upgrade - but end up in the same position. 

Must Gather here
https://easyupload.io/7h3yvn

Thanks!

**Comment by Francua** [comment] 2021-01-07 09:06
[https://drive.google.com/file/d/17XSmSh4UOcZgq0V-D-LnLITABfDFx--0/view?usp=sharing](url)

**Comment by vrutkovs** [comment] 2021-01-07 09:30
Since you're using a proxy I suppose its a dupe of #398. Check that existing repos are disabled and/or have proxy configuration set?

**Comment by acsecengtesting** [comment] 2021-01-07 09:37
Just to note I'm not using a proxy. Should I raise a separate ticket ?

**Comment by vrutkovs** [comment] 2021-01-07 09:51
>Should I raise a separate ticket ?

yes

**Comment by Francua** [comment] 2021-01-07 11:52
On all master/worker nodes bellow repos are enabled. Disable them ? Restart is nessesary ?? 

```
 grep enabled=1 /etc/yum.repos.d/* 
/etc/yum.repos.d/fedora-cisco-openh264.repo:enabled=1
/etc/yum.repos.d/fedora-updates.repo:enabled=1
/etc/yum.repos.d/fedora.repo:enabled=1

```

**Comment by vrutkovs** [comment] 2021-01-07 12:26
Right, since you have repos enabled `rpm-ostree` uses them - but it fails as the repo definition don't have proxy config. Feel free to disable those (if you're not planning to install additional RPMs) or add proxy config there. Restart is not necessary afaik

**Comment by Francua** [comment] 2021-01-08 07:46
Repo disabled on all nodes. Is there any way to resume the cluster upgrade ??

```
oc get co
NAME                                       VERSION                         AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.6.0-0.okd-2020-12-12-135354   True        False         False      100m
cloud-credential                           4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
cluster-autoscaler                         4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
config-operator                            4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
console                                    4.6.0-0.okd-2020-12-12-135354   True        False         False      108m
csi-snapshot-controller                    4.6.0-0.okd-2020-12-12-135354   True        False         False      16h
dns                                        4.6.0-0.okd-2020-12-12-135354   True        False         False      2d17h
etcd                                       4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
image-registry                             4.6.0-0.okd-2020-12-12-135354   True        False         False      2d22h
ingress                                    4.6.0-0.okd-2020-12-12-135354   True        False         False      2d18h
insights                                   4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
kube-apiserver                             4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
kube-controller-manager                    4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
kube-scheduler                             4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
kube-storage-version-migrator              4.6.0-0.okd-2020-12-12-135354   True        False         False      2d22h
machine-api                                4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
machine-approver                           4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
machine-config                             4.5.0-0.okd-2020-10-15-235428   False       True          True       2d17h
marketplace                                4.6.0-0.okd-2020-12-12-135354   True        False         False      16h
monitoring                                 4.6.0-0.okd-2020-12-12-135354   True        False         False      16h
network                                    4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
node-tuning                                4.6.0-0.okd-2020-12-12-135354   True        False         False      16h
openshift-apiserver                        4.6.0-0.okd-2020-12-12-135354   True        False         False      16h
openshift-controller-manager               4.6.0-0.okd-2020-12-12-135354   True        False         False      2d18h
openshift-samples                          4.6.0-0.okd-2020-12-12-135354   True        False         False      16h
operator-lifecycle-manager                 4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
operator-lifecycle-manager-catalog         4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
operator-lifecycle-manager-packageserver   4.6.0-0.okd-2020-12-12-135354   True        False         False      109m
service-ca                                 4.6.0-0.okd-2020-12-12-135354   True        False         False      9d
storage                                    4.6.0-0.okd-2020-12-12-135354   True        False         False      2d18h


oc describe co machine-config
Name:         machine-config
Namespace:    
Labels:       <none>
Annotations:  exclude.release.openshift.io/internal-openshift-hosted: true
API Version:  config.openshift.io/v1
Kind:         ClusterOperator
Metadata:
  Creation Timestamp:  2020-12-29T10:41:00Z
  Generation:          1
  Managed Fields:
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:exclude.release.openshift.io/internal-openshift-hosted:
      f:spec:
      f:status:
    Manager:      cluster-version-operator
    Operation:    Update
    Time:         2020-12-29T10:41:00Z
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
        f:extension:
          .:
          f:lastSyncError:
          f:master:
          f:worker:
        f:relatedObjects:
        f:versions:
    Manager:         machine-config-operator
    Operation:       Update
    Time:            2021-01-08T07:39:24Z
  Resource Version:  18981167
  Self Link:         /apis/config.openshift.io/v1/clusteroperators/machine-config
  UID:               aa3fb671-d9db-4a66-bd3a-08528af48bc4
Spec:
Status:
  Conditions:
    Last Transition Time:  2021-01-05T13:53:23Z
    Message:               Working towards 4.6.0-0.okd-2020-12-12-135354
    Status:                True
    Type:                  Progressing
    Last Transition Time:  2021-01-07T16:09:14Z
    Message:               Unable to apply 4.6.0-0.okd-2020-12-12-135354: timed out waiting for the condition during syncRequiredMachineConfigPools: pool master has not progressed to latest configuration: controller version mismatch for rendered-master-af023939b490b7090608e2581d5b9dc1 expected eb9778355a9020673e8ce9aee092cb98d80cde5e has 57d3c165737944e8236ee6202391202e89e59aba: pool is degraded because nodes fail with "2 nodes are reporting degraded status on sync": "Node ocmasterc8-dev01.fortisbank.com.pl is reporting: \"failed to execute rpm-ostree [\\\"update\\\" \\\"--install\\\" \\\"glusterfs\\\" \\\"--install\\\" \\\"glusterfs-fuse\\\" \\\"--install\\\" \\\"open-vm-tools\\\" \\\"--install\\\" \\\"qemu-guest-agent\\\" \\\"--install\\\" \\\"NetworkManager-ovs\\\"] : exit status 1\", Node ocmasterc8-dev51.fortisbank.com.pl is reporting: \"unexpected on-disk state validating against rendered-master-851a98b01f6173969b7aacb3f29aafd2: expected target osImageURL \\\"quay.io/openshift/okd-content@sha256:880f0e1cfb4a5c8c22dd9cbb54c2294bcbbcfef30b126d5c04d3160f84438c6a\\\", have \\\"quay.io/openshift/okd-content@sha256:8cf7e06dd4095f2cd54e13fdb6fd313abbeb6e03d568f17956d97433623093c2\\\"\"", retrying
    Reason:                RequiredPoolsFailed
    Status:                True
    Type:                  Degraded
    Last Transition Time:  2021-01-05T13:51:15Z
    Message:               Cluster not available for 4.6.0-0.okd-2020-12-12-135354
    Status:                False
    Type:                  Available
    Last Transition Time:  2020-12-29T10:48:24Z
    Reason:                AsExpected
    Status:                True
    Type:                  Upgradeable
  Extension:
    Last Sync Error:  pool master has not progressed to latest configuration: controller version mismatch for rendered-master-af023939b490b7090608e2581d5b9dc1 expected eb9778355a9020673e8ce9aee092cb98d80cde5e has 57d3c165737944e8236ee6202391202e89e59aba: pool is degraded because nodes fail with "2 nodes are reporting degraded status on sync": "Node ocmasterc8-dev01.fortisbank.com.pl is reporting: \"failed to execute rpm-ostree [\\\"update\\\" \\\"--install\\\" \\\"glusterfs\\\" \\\"--install\\\" \\\"glusterfs-fuse\\\" \\\"--install\\\" \\\"open-vm-tools\\\" \\\"--install\\\" \\\"qemu-guest-agent\\\" \\\"--install\\\" \\\"NetworkManager-ovs\\\"] : exit status 1\", Node ocmasterc8-dev51.fortisbank.com.pl is reporting: \"unexpected on-disk state validating against rendered-master-851a98b01f6173969b7aacb3f29aafd2: expected target osImageURL \\\"quay.io/openshift/okd-content@sha256:880f0e1cfb4a5c8c22dd9cbb54c2294bcbbcfef30b126d5c04d3160f84438c6a\\\", have \\\"quay.io/openshift/okd-content@sha256:8cf7e06dd4095f2cd54e13fdb6fd313abbeb6e03d568f17956d97433623093c2\\\"\"", retrying
    Master:           pool is degraded because nodes fail with "2 nodes are reporting degraded status on sync": "Node ocmasterc8-dev01.fortisbank.com.pl is reporting: \"failed to execute rpm-ostree [\\\"update\\\" \\\"--install\\\" \\\"glusterfs\\\" \\\"--install\\\" \\\"glusterfs-fuse\\\" \\\"--install\\\" \\\"open-vm-tools\\\" \\\"--install\\\" \\\"qemu-guest-agent\\\" \\\"--install\\\" \\\"NetworkManager-ovs\\\"] : exit status 1\", Node ocmasterc8-dev51.fortisbank.com.pl is reporting: \"unexpected on-disk state validating against rendered-master-851a98b01f6173969b7aacb3f29aafd2: expected target osImageURL \\\"quay.io/openshift/okd-content@sha256:880f0e1cfb4a5c8c22dd9cbb54c2294bcbbcfef30b126d5c04d3160f84438c6a\\\", have \\\"quay.io/openshift/okd-content@sha256:8cf7e06dd4095f2cd54e13fdb6fd313abbeb6e03d568f17956d97433623093c2\\\"\""
    Worker:           pool is degraded because nodes fail with "2 nodes are reporting degraded status on sync": "Node ocworkerc8-dev04.fortisbank.com.pl is reporting: \"unexpected on-disk state validating against rendered-worker-24ed3eecba1fc93a9060178b075a3dab: expected target osImageURL \\\"quay.io/openshift/okd-content@sha256:880f0e1cfb4a5c8c22dd9cbb54c2294bcbbcfef30b126d5c04d3160f84438c6a\\\", have \\\"quay.io/openshift/okd-content@sha256:8cf7e06dd4095f2cd54e13fdb6fd313abbeb6e03d568f17956d97433623093c2\\\"\", Node ocworkerc8-dev54.fortisbank.com.pl is reporting: \"failed to execute rpm-ostree [\\\"update\\\" \\\"--install\\\" \\\"glusterfs\\\" \\\"--install\\\" \\\"glusterfs-fuse\\\" \\\"--install\\\" \\\"open-vm-tools\\\" \\\"--install\\\" \\\"qemu-guest-agent\\\" \\\"--install\\\" \\\"NetworkManager-ovs\\\"] : exit status 1\""
  Related Objects:
    Group:     
    Name:      openshift-machine-config-operator
    Resource:  namespaces
    Group:     machineconfiguration.openshift.io
    Name:      
    Resource:  machineconfigpools
    Group:     machineconfiguration.openshift.io
    Name:      
    Resource:  controllerconfigs
    Group:     machineconfiguration.openshift.io
    Name:      
    Resource:  kubeletconfigs
    Group:     machineconfiguration.openshift.io
    Name:      
    Resource:  containerruntimeconfigs
    Group:     machineconfiguration.openshift.io
    Name:      
    Resource:  machineconfigs
    Group:     
    Name:      
    Resource:  nodes
  Versions:
    Name:     operator
    Version:  4.5.0-0.okd-2020-10-15-235428
Events:       <none>
```
```

**Comment by bohdan-udovenko-cognite** [comment] 2021-02-25 19:55
+1 to this bug.
Solution: on all master nodes do `sed -i 's/enabled=1/enabled=0/g' /etc/yum.repos.d/*`.
It can be done via ssh or `oc debug node/master-node-0` and chroot to host.

**Comment by dubbrian** [comment] 2021-02-26 15:21
Thanks for this solution it resolved for me too.

**Comment by jkassis** [comment] 2021-04-28 21:17
thanks likewise

**Comment by vrutkovs** [comment] 2021-07-02 09:18
dupe of #398

**Closed by vrutkovs** 2021-07-02 09:18 UTC
