### ISSUE TITLE
how to upgrade a cluster from beta6 to GA?

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#270] opened 2020-07-19 18:09 UTC
**Describe the bug**
I don't seem to be able to upgrade from beta6 to GA:

```
> oc adm upgrade --to=4.5.0-0.okd-2020-07-14-153706-ga --force=true --allow-upgrade-with-warnings                                      
error: Can't look up image for version 4.5.0-0.okd-2020-07-14-153706-ga. Unable to retrieve available updates: currently installed version 4.5.0-0.okd-2020-06-29-110348-beta6 not found in the "stable-4.5" channel       

>oc adm upgrade
Cluster version is 4.5.0-0.okd-2020-06-29-110348-beta6
warning: Cannot display available updates:
  Reason: VersionNotFound
  Message: Unable to retrieve available updates: currently installed version 4.5.0-0.okd-2020-06-29-110348-beta6 not found in the "stable-4.5" channel
                
```                                                                                                          

I have already tried setting the channel to stable-4, too but same result.

I have searched here for other reports or hints ...
Have I overlooked something?
Is upgrading a beta cluster supported at all?

**Version**
Currently 4.5 beta 6 on vSphere UPI

**How reproducible**
100%

**Comment by vrutkovs** [comment] 2020-07-20 06:18
Dupe of https://github.com/openshift/okd/issues/241

**Closed by vrutkovs** 2020-07-20 06:18 UTC

**Comment by kai-uwe-rommel** [comment] 2020-07-20 08:01
Thanks. Somehow I did not find this other issue when searching ...
