### ISSUE TITLE
README: Add reference to OKD resource requirements

### ISSUE THREAD

**Issue by viniciusferrao** [openshift/okd#152] opened 2020-04-16 17:16 UTC
Hello, I started a lab to test OKD 4.4 with RHV ([the new deployment model](https://access.redhat.com/sites/default/files/attachments/quickstart_guide_for_installing_ocp_on_rhv_1.4.pdf)) and was really shocked with the system requirements:

- Confirm that the hosts have a combined total of at least 24 CPU cores available exclusively for the RHOCP cluster. These CPUs must be distributed so that each of the 6 virtual machines created during installation can have 4 CPU cores.
- Confirm that, all together, the hosts have 64 GiB free memory for the following RHOCP nodes:
- ○ 8 GiB required (16 GiB recommended) for the Bootstrap node, which provides the temporary control plane
-  ○ 8 GiB required (16 GiB recommended) for each of the three master nodes which provide the control plane
- ○ 16 GiB for each of the two worker nodes, which run the application workloads

I don't have this resources. I do have a good pool, with 36 CPU cores and 192GB of RAM distributed between three nodes. But there's other things running on those machines and I can't eat the entire cluster just with management VMs.

Is this requirements really correct? The CPU requirements appear to be exaggerated, and the RAM requirements too.

**Comment by LorbusChris** [comment] 2020-04-16 19:37
Yes, these are indeed the requirements at this time.
It's a stretch goal to lower them, but this is not in scope for this repository at this time.

**Comment by viniciusferrao** [comment] 2020-04-18 22:08
Thanks for confirming @LorbusChris 
This info is unavailable on the README here on GitHub.

I still have one question: I can understand the RAM requirements, but I can't understand the CPU requirements. Why we need 24 *dedicated* cores? Why they can't be shared? The ratio CPU/RAM is extremely disproportional.

**Comment by LorbusChris** [comment] 2020-04-18 22:20
You're absolutely right, we should add a section or at least a link to refer to that!
The usual minimal setup that I've seen consists of 6 dedicated machines (3 masters, 3 workers), with a 4 core CPU each. I cannot speak to details of how that requirement is assessed exactly, though. I'll try to find somebody who is able to give you a more informed answer at the start of next week.

Let me re-open and re-name this issue for tracking.

Also, and I should've said that as a first thing, thank you for your interest in OKD! :)

**Comment by LorbusChris** [comment] 2020-04-18 22:33
@viniciusferrao one more thing: Even though it's not recommended, you _can_ mark your masters as schedulable for workload containers (you would probably use `openshift-install create install-config` to create the manifests and then edit them before proceeding with the installation) and thus get away with a 3 machine setup. I would expect your resources to be sufficient, but there's no guarantee - quite a lot things run by design to ensure high availability and stability, e.g. two monitoring stacks (aka one HA monitoring stack..)

**Comment by cgruver** [comment] 2020-04-19 00:11
@viniciusferrao Since you are sitting on top of KVM, you can oversubscribe the CPUs.  As long as you're not running extreme load, the guest VMs won't know or care that they are sharing CPU with other work loads.

I'm running 2 to 2.5X oversubscription in my lab setup.  RAM is really more critical than CPU for a lightly loaded cluster.

If you do a UPI install and use a value of 0 for worker nodes in your install-config.yaml, then your master nodes will automatically be labeled as worker nodes as well.

With that configuration, you only need 3 VMs for your cluster + a temporary bootstrap node.

If you do that, I highly recommend more RAM for the masters.  16 to 24 GB of RAM for the three master nodes.

**Comment by cgruver** [comment] 2020-04-19 00:14
If you already have master nodes running, and want to make them schedulable after the fact, this should work:

`oc patch scheduler cluster --patch '{"spec":{"mastersSchedulable":true}}' --type=merge`

**Comment by vrutkovs** [comment] 2020-07-24 07:50
Requirements may change and should be tracked in [official documentation](https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html#minimum-resource-requirements_installing-bare-metal).

Slimming down those requirements is really a different topic, so I'll close this ticket

**Closed by vrutkovs** 2020-07-24 07:50 UTC
Labels: kind/documentation
