### ISSUE TITLE
AWS: Error launching source instance: timeout while waiting for state to become 'success'

### ISSUE THREAD

**Issue by sapkra** [openshift/okd#32] opened 2020-01-14 03:13 UTC
# Version

```console
$ openshift-install version
openshift-install unreleased-master-2025-g23f40299a6ab4f4f9bfbfd1ec1d15dfab90a6ecf-dirty
built from commit 23f40299a6ab4f4f9bfbfd1ec1d15dfab90a6ecf
release image quay.io/openshift/okd@sha256:5d2e42d555d24bb1a60d20eb03ae7e288f4347cad6a68c5428d00598c5816678
```

# Platform:

aws

# What happened?

When installing OKD on AWS this error always occurs. Just 1/15 times this part succeeded but it run into a different error.
```bash
ERROR                                              
ERROR Error: Error launching source instance: timeout while waiting for state to become 'success' (timeout: 30s) 
ERROR                                              
ERROR   on ../../../../../private/var/folders/b2/n35kbcsx1296ys4z6ndjsq4m0000gn/T/openshift-install-085413156/master/main.tf line 93, in resource "aws_instance" "master": 
ERROR   93: resource "aws_instance" "master" {     
ERROR                                              
ERROR                                              
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform
```

# What you expected to happen?
Should install cluster on AWS without errors.

# How to reproduce it?
I just tried to install OKD to AWS using the openshift-installer build of the okd repository. But I also tried to deploy it with the current version of this repository with a modified release-image.

```console
$ openshift-install create cluster --log-level debug
```

**Comment by vrutkovs** [comment] 2020-01-21 11:19
Is this reproducible if a 4.4 release from https://origin-release.svc.ci.openshift.org/ is used?

**Comment by sapkra** [comment] 2020-01-21 11:23
I will try it. I've only tried one of the 4.3 releases yet and it didn't work.

**Comment by sapkra** [comment] 2020-01-21 13:41
Ok, the first time I run it with the new version it seems to work (maybe it's fixed or it will crash within the next run).

```console
$ openshift-install version
openshift-install unreleased-master-2054-g7e1413f19c0af31bd7919d3067080a9ec787e135-dirty
built from commit 7e1413f19c0af31bd7919d3067080a9ec787e135
release image registry.svc.ci.openshift.org/origin/release@sha256:3b68e0f037c0ef3359ba3707d623a00402d0467d5ebafa8fea34ad326a27ed30
```

My new console output with the next error:
```console
$ openshift-install create cluster
INFO Consuming Install Config from target directory 
INFO Creating infrastructure resources...         
INFO Waiting up to 30m0s for the Kubernetes API at https://api.dev.example.com:6443... 
INFO API v1.17.0 up                               
INFO Waiting up to 30m0s for bootstrapping to complete... 
INFO Destroying the bootstrap resources...        
ERROR                                              
ERROR Warning: Resource targeting is in effect     
ERROR                                              
ERROR You are creating a plan with the -target option, which means that the result 
ERROR of this plan may not represent all of the changes requested by the current 
ERROR configuration.                               
ERROR                                                      
ERROR The -target option is not for routine use, and is provided only for 
ERROR exceptional situations such as recovering from errors or mistakes, or when 
ERROR Terraform specifically suggests to use it as part of an error message. 
ERROR                                              
ERROR                                              
ERROR Warning: Applied changes may be incomplete   
ERROR                                              
ERROR The plan was created with the -target option in effect, so some changes 
ERROR requested in the configuration may have been ignored and the output values may 
ERROR not be fully updated. Run the following command to verify that no other 
ERROR changes are pending:                         
ERROR     terraform plan                           
ERROR                                               
ERROR Note that the -target option is not suitable for routine use, and is provided 
ERROR only for exceptional situations such as recovering from errors or mistakes, or 
ERROR when Terraform specifically suggests to use it as part of an error message. 
ERROR
INFO Waiting up to 30m0s for the cluster at https://api.dev.example.com:6443 to initialize... 
E0121 14:09:10.603015   29692 reflector.go:280] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: Get https://api.dev.example.com:6443/apis/config.openshift.io/v1/clusterversions?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dversion&resourceVersion=6227&timeoutSeconds=434&watch=true: dial tcp 3.125.232.148:6443: connect: connection refused
E0121 14:09:11.670914   29692 reflector.go:280] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: Get https://api.dev.example.com:6443/apis/config.openshift.io/v1/clusterversions?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dversion&resourceVersion=6227&timeoutSeconds=501&watch=true: dial tcp 3.125.227.80:6443: connect: connection refused
E0121 14:23:19.657660   29692 reflector.go:280] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: Get https://api.dev.example.com:6443/apis/config.openshift.io/v1/clusterversions?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dversion&resourceVersion=12851&timeoutSeconds=428&watch=true: dial tcp 3.124.42.151:6443: connect: connection refused
E0121 14:23:26.410308   29692 reflector.go:280] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: the server is currently unable to handle the request (get clusterversions.config.openshift.io)
I0121 14:23:37.751957   29692 trace.go:116] Trace[1562460260]: "Reflector ListAndWatch" name:k8s.io/client-go/tools/watch/informerwatcher.go:146 (started: 2020-01-21 14:23:27.411104 +0100 CET m=+2282.244719334) (total time: 10.340616233s):
Trace[1562460260]: [10.340594715s] [10.340594715s] Objects listed
E0121 14:25:45.974279   29692 reflector.go:280] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: Get https://api.dev.example.com:6443/apis/config.openshift.io/v1/clusterversions?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dversion&resourceVersion=12958&timeoutSeconds=453&watch=true: dial tcp 3.125.232.148:6443: connect: connection refused
E0121 14:25:47.045923   29692 reflector.go:280] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: Get https://api.dev.example.com:6443/apis/config.openshift.io/v1/clusterversions?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dversion&resourceVersion=12958&timeoutSeconds=563&watch=true: dial tcp 3.124.42.151:6443: connect: connection refused
E0121 14:25:48.109525   29692 reflector.go:280] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: Get https://api.dev.example.com:6443/apis/config.openshift.io/v1/clusterversions?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dversion&resourceVersion=12958&timeoutSeconds=549&watch=true: dial tcp 3.125.232.148:6443: connect: connection refused
E0121 14:25:55.373676   29692 reflector.go:280] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ClusterVersion: the server is currently unable to handle the request (get clusterversions.config.openshift.io)
I0121 14:26:12.074432   29692 trace.go:116] Trace[1614350600]: "Reflector ListAndWatch" name:k8s.io/client-go/tools/watch/informerwatcher.go:146 (started: 2020-01-21 14:25:56.37865 +0100 CET m=+2431.209468384) (total time: 15.695454553s):
Trace[1614350600]: [15.695429463s] [15.695429463s] Objects listed
ERROR Cluster operator authentication Degraded is True with IngressStateEndpoints_MissingSubsets::RouteStatus_FailedHost: IngressStateEndpointsDegraded: No subsets found for the endpoints of oauth-server
RouteStatusDegraded: route is not available at canonical host oauth-openshift.apps.dev.example.com: [] 
INFO Cluster operator authentication Progressing is Unknown with NoData:  
INFO Cluster operator authentication Available is Unknown with NoData:  
INFO Cluster operator console Progressing is True with RouteSyncProgressingFailedHost: RouteSyncProgressing: route is not available at canonical host [] 
INFO Cluster operator console Available is Unknown with NoData:  
INFO Cluster operator image-registry Available is False with NoReplicasAvailable: The deployment does not have available replicas 
INFO Cluster operator image-registry Progressing is True with DeploymentNotCompleted: The deployment has not completed 
ERROR Cluster operator ingress Degraded is True with IngressControllersDegraded: Some ingresscontrollers are degraded: default 
INFO Cluster operator ingress Progressing is True with Reconciling: Not all ingress controllers are available.
Moving to release version "4.4.0-0.okd-2020-01-20-231545".
Moving to ingress-controller image version "registry.svc.ci.openshift.org/origin/4.4-2020-01-20-231545@sha256:c5aa779b80bf6b7f9e98a4f85a3fec5a17543ce89376fc13e924deedcd7298cf". 
INFO Cluster operator ingress Available is False with IngressUnavailable: Not all ingress controllers are available. 
INFO Cluster operator insights Disabled is True with Disabled: Health reporting is disabled 
INFO Cluster operator kube-storage-version-migrator Available is False with _NoMigratorPod: Available: deployment/migrator.openshift-kube-storage-version-migrator: no replicas are available 
INFO Cluster operator monitoring Progressing is True with RollOutInProgress: Rolling out the stack. 
ERROR Cluster operator monitoring Degraded is True with UpdatingAlertmanagerFailed: Failed to rollout the stack. Error: running task Updating Alertmanager failed: waiting for Alertmanager Route to become ready failed: waiting for RouteReady of alertmanager-main: no status available for alertmanager-main 
INFO Cluster operator monitoring Available is False with :  
INFO Cluster operator support Disabled is True with : Health reporting is disabled 
FATAL failed to initialize the cluster: Working towards 4.4.0-0.okd-2020-01-20-231545: 99% complete
```

**Comment by vrutkovs** [comment] 2020-01-21 13:46
Lets file a new bug for that. Use `oc adm must-gather` to collect necessary info, compress it and upload to some location (e.g. GDrive).

I'll close this issue since it appears to be resolved

**Closed by vrutkovs** 2020-01-21 13:46 UTC
Labels: platform/aws, triage/needs-information

**Comment by sapkra** [comment] 2020-01-21 14:12
I was wondering how to access the cluster so I found out that I had to run to following in the install directory. Maybe it will help someone.

```bash
oc --config=auth/kubeconfig adm must-gather
```

I will create a new issue. If I will get the same problem again I will comment this issue again so that it can be reopened.

**Comment by woland7** [comment] 2021-11-23 14:14
oc --config=auth/kubeconfig adm must-gather in newer version is --kubeconfig
