### ISSUE TITLE
IPI baremetal: Error: missing provider "ironic"

### ISSUE THREAD

**Issue by OleksandrShtepa** [openshift/okd#583] opened 2021-04-05 13:34 UTC
**Describe the bug**
```console
# openshift-baremetal-install --log-level debug create cluster
...
INFO Creating infrastructure resources...
DEBUG Symlinking plugin terraform-provider-aws src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-aws"
DEBUG Symlinking plugin terraform-provider-azureprivatedns src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-azureprivatedns"
DEBUG Symlinking plugin terraform-provider-libvirt src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-libvirt"
DEBUG Symlinking plugin terraform-provider-vsphereprivate src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-vsphereprivate"
DEBUG Symlinking plugin terraform-provider-google src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-google"
DEBUG Symlinking plugin terraform-provider-local src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-local"
DEBUG Symlinking plugin terraform-provider-vsphere src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-vsphere"
DEBUG Symlinking plugin terraform-provider-openstack src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-openstack"
DEBUG Symlinking plugin terraform-provider-ovirt src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-ovirt"
DEBUG Symlinking plugin terraform-provider-random src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-random"
DEBUG Symlinking plugin terraform-provider-azurerm src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-azurerm"
DEBUG Symlinking plugin terraform-provider-ignition src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-ignition"
DEBUG Symlinking plugin terraform-provider-kubernetes src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-kubernetes"
DEBUG Symlinking plugin terraform-provider-kubevirt src: "/root/bin/openshift-baremetal-install" dst: "/tmp/openshift-install-863457276/plugins/terraform-provider-kubevirt"
DEBUG Initializing modules...
DEBUG - bootstrap in ../../tmp/openshift-install-863457276/bootstrap
DEBUG - masters in ../../tmp/openshift-install-863457276/masters
DEBUG
DEBUG Initializing the backend...
DEBUG
DEBUG Initializing provider plugins...
ERROR
ERROR Missing required providers.
ERROR
ERROR The following provider constraints are not met by the currently-installed
ERROR provider plugins:
ERROR
ERROR * ironic (any version)
ERROR
ERROR Terraform can automatically download and install plugins to meet the given
ERROR constraints, but this step was skipped due to the use of -get-plugins=false
ERROR and/or -plugin-dir on the command line.
ERROR
ERROR If automatic installation is not possible or desirable in your environment,
ERROR you may manually install plugins by downloading a suitable distribution package
ERROR and placing the plugin's executable file in one of the directories given in
ERROR by -plugin-dir on the command line, or in the following directory if custom
ERROR plugin directories are not set:
ERROR     terraform.d/plugins/linux_amd64
ERROR
ERROR
ERROR Error: missing provider "ironic"
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to initialize Terraform
```

**Version**
4.7.0-0.okd-2021-03-28-152009
IPI baremetal

**How reproducible**
```console
$ openshift-baremetal-install --log-level debug create cluster
```

**Comment by cgruver** [comment] 2021-04-05 18:52
This may be related to: https://github.com/openshift/okd/issues/197

I don't think it is resolved yet.

**Comment by OleksandrShtepa** [comment] 2021-04-06 06:18
So baremetal IPI never worked in OKD?
No https://docs.okd.io/, no Known Issues about this...

**Comment by vrutkovs** [comment] 2021-04-06 07:53
Dupe of #197, no baremetal IPI yet

**Closed by vrutkovs** 2021-04-06 07:53 UTC
