### ISSUE TITLE
[baremetal] Failure to update coreos to 4.6.0-0.okd-2021-01-17-185703

### ISSUE THREAD

**Issue by RyuunoAelia** [openshift/okd#476] opened 2021-01-20 18:13 UTC
**Describe the bug**

When updating from 4.6.0-0.okd-2020-12-12-135354 to 4.6.0-0.okd-2021-01-17-185703 the update process gets stuck when trying to update Fedora CoreOS.

**Version**

UPI BareMetal 4.6.0-0.okd-2021-01-17-185703

**How reproducible**

Try to update from 4.6.0-0.okd-2020-12-12-135354 to 4.6.0-0.okd-2021-01-17-185703

**Log bundle**
Relevant logs:
```
$ oc get clusterversion
NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.6.0-0.okd-2020-12-12-135354   True        True          24h     Working towards 4.6.0-0.okd-2021-01-17-185703: 29% complete
```
```
$ oc get nodes
NAME               STATUS                     ROLES    AGE    VERSION
okd4-compute-200   Ready                      worker   245d   v1.19.2+7070803-1008
okd4-compute-201   Ready,SchedulingDisabled   worker   245d   v1.19.2+7070803-1008
okd4-compute-202   Ready                      worker   245d   v1.19.2+7070803-1008
okd4-master-25     Ready                      master   249d   v1.19.2+7070803-1008
okd4-master-26     Ready,SchedulingDisabled   master   249d   v1.19.2+7070803-1008
okd4-master-27     Ready                      master   249d   v1.19.2+7070803-1008
```

```
$ oc describe node okd4-compute-201
Name:               okd4-compute-201
Roles:              worker
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=okd4-compute-201
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/worker=
                    node.openshift.io/os_id=fedora
Annotations:        csi.volume.kubernetes.io/nodeid: {"rook-ceph.cephfs.csi.ceph.com":"okd4-compute-201","rook-ceph.rbd.csi.ceph.com":"okd4-compute-201"}
                    machineconfiguration.openshift.io/currentConfig: rendered-worker-a2377a2d2079aa9c46ff5b7ca40879d1
                    machineconfiguration.openshift.io/desiredConfig: rendered-worker-09f39a0170ba389b7c7db5dabd7415f5
                    machineconfiguration.openshift.io/reason:
                      failed to update OS to quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c : with stdout...
                      Checking out tree 14eea52...done
                      Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora coreos-extensions updates-archive
                      rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2020-08-25T19:10:34Z
                      rpm-md repo 'updates' (cached); generated: 2021-01-20T01:19:08Z
                      rpm-md repo 'fedora' (cached); generated: 2020-10-19T23:27:19Z
                      rpm-md repo 'coreos-extensions' (cached); generated: 2021-01-17T11:40:41Z
                      rpm-md repo 'updates-archive' (cached); generated: 2021-01-19T03:51:30Z
                      Importing rpm-md...done
                      Resolving dependencies...done
                      Checking out packages...done
                      : exit status 1
                    machineconfiguration.openshift.io/ssh: accessed
                    machineconfiguration.openshift.io/state: Degraded
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 20 May 2020 15:42:27 +0200
Taints:             node.kubernetes.io/unschedulable:NoSchedule
Unschedulable:      true
Lease:
  HolderIdentity:  okd4-compute-201
  AcquireTime:     <unset>
  RenewTime:       Wed, 20 Jan 2021 19:06:38 +0100
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Wed, 20 Jan 2021 19:05:09 +0100   Tue, 15 Dec 2020 21:23:57 +0100   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Wed, 20 Jan 2021 19:05:09 +0100   Tue, 15 Dec 2020 21:23:57 +0100   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Wed, 20 Jan 2021 19:05:09 +0100   Tue, 15 Dec 2020 21:23:57 +0100   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Wed, 20 Jan 2021 19:05:09 +0100   Tue, 15 Dec 2020 21:23:58 +0100   KubeletReady                 kubelet is posting ready status
```

Note that here the annotation from MCO specifically contains only stdout... and the error message is not there... it is in stderr as shown by the research I made manually.

```
[root@okd4-compute-201 core]# mkdir -p /run/mco-machine-os-content/os-content-175265935
[root@okd4-compute-201 core]# oc image extract --path /:/run/mco-machine-os-content/os-content-175265935 --registry-config /var/lib/kubelet/config.json quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c
[root@okd4-compute-201 core]# rpm-ostree rebase --experimental /run/mco-machine-os-content/os-content-175265935/srv/repo:14eea5296ffb7a28aff80a70c03434e8034422b0d11b47475b29530b93ab4682 --custom-origin-url pivot://quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c --custom-origin-description 'Manual'
0 metadata, 0 content objects imported; 0 bytes content written
Checking out tree 14eea52... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora updates-archive
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2020-08-25T19:10:34Z
rpm-md repo 'updates' (cached); generated: 2021-01-20T01:19:08Z
rpm-md repo 'fedora' (cached); generated: 2020-10-19T23:27:19Z
rpm-md repo 'updates-archive' (cached); generated: 2021-01-19T03:51:30Z
Importing rpm-md... done
Resolving dependencies... done
Checking out packages... done
error: Checkout open-vm-tools-11.2.5-1.fc33.x86_64: Hardlinking 57/2d1e0a8b85be28856aa9655c6ef42462a8aabdc30868f3a7a910bfa0f8dd3d.file to VGAuthService: File exists
```
Now I am a bit perplexed by my UPI BareMetal update failing because some open-vm-tools executable already exists. And I don't know enough about how this whole process works to actually fix it manually.

**Comment by kai-uwe-rommel** [comment] 2021-01-20 19:00
You may want to check this: https://github.com/openshift/okd/issues/471

**Comment by vrutkovs** [comment] 2021-01-20 19:45
Dupe of #471

**Closed by vrutkovs** 2021-01-20 19:45 UTC
