### ISSUE TITLE
Support Operator Degraded

### ISSUE THREAD

**Issue by jdhirst1** [openshift/okd#71] opened 2020-02-05 16:21 UTC
Version: 4.4.0-0.okd-2020-02-04-174205

The support operator becomes degraded as it attempts to post to cloud.redhat.com but is seeing the ingress certificate:

```
Unable to report: Post https://cloud.redhat.com/api/ingress/v1/upload: x509: certificate is valid for *.apps.okd.example.net, not cloud.redhat.com
```

**Comment by vrutkovs** [comment] 2020-02-05 16:38
Right, installer should deploy a config which disables it

**Comment by jdhirst1** [comment] 2020-02-05 16:41
Which config is (supposed to be) being applied by installer? I can apply it to re-enable upgrades as a temporary solution.

**Comment by vrutkovs** [comment] 2020-02-05 16:53
Interesting, the operator should have switch to disabled (if the pull secret doesn't have cloud.redhat.com part). Could you attach must-gather, so that @iNecas  would have a look?

**Comment by jdhirst1** [comment] 2020-02-05 17:03
My pull secret does have cloud.redhat.com; so it should have been enabled? Why is it seeing the ingress certificate and failing at that point?
must-gather: https://drive.google.com/open?id=1lURmQqcNqPFjFXTtBsrmbtaPi8YDf-sd

**Comment by vrutkovs** [comment] 2020-02-05 17:16
No, that's an insights bug then - the idea is that telemetry / insights would be disabled if the pull secret doesn't have `cloud.redhat.com` part. Instead support operator goes degraded.

Mind filing the same bug in https://github.com/openshift/insights-operator (and keep this one for tracking)

**Comment by jdhirst1** [comment] 2020-02-05 17:32
Filed under https://github.com/openshift/insights-operator/issues/74

**Comment by iNecas** [comment] 2020-02-05 20:07
What I see @jdhirst1 is saying is the pull secret *has* the `cloud.redhat.com` credentials. Can you confirm the failure happens when you follow this procedure? https://docs.openshift.com/container-platform/4.2/support/remote_health_monitoring/opting-out-of-remote-health-reporting.html

**Comment by jdhirst1** [comment] 2020-02-05 20:09
I attempted to remove cloud.redhat.com from the pull secret it broke MCO due to existing known issue. I am testing with a new cluster now (removed cloud.redhat.com creds from install-config pull secret).

However, if I had the credentials in there, that seems to imply that there is a bug in insights operator as it shouldn't be giving that SSL error, right?

**Comment by iNecas** [comment] 2020-02-06 06:41
I'm not seeing this behavior with my installations. From the error, it looks like it tries to reach to cloud.redhat.com, but it seems like it's hitting some local end-point. Any proxy configured in the setup or something else that could be contributing to this issue?

@vrutkovs are you able to replicate this issue?

**Comment by vrutkovs** [comment] 2020-02-06 09:34
Can't reproduce that on AWS IPI using both OCP pull secret and the fake one, so it must be some specific network config?

Do you run any kind of proxies / custom DNS which replace the address? I don't see any other reason why would a request to `cloud.redhat.com` would go to `*.okd.hirstgroup.net` instead

**Comment by jdhirst1** [comment] 2020-02-06 17:29
No, the DNS servers that are accessible from the nodes are able to lookup cloud.redhat.com without issue. Not sure why it redirects; I have removed the *.okd record as it wasn't needed, and re-tested. 

Things seem to be working now, could be a weird issue with the local DNS server.

**Comment by LorbusChris** [comment] 2020-02-07 00:41
Closing this as it seems to work now. Feel free to reopen.

**Closed by LorbusChris** 2020-02-07 00:41 UTC
