### ISSUE TITLE
Internal Network or HaProxy Bug

### ISSUE THREAD

**Issue by alexanderniebuhr** [openshift/okd#500] opened 2021-02-04 09:57 UTC
**Describe the bug**

We do observe some issues with multiple default ingress router. If we do have the default replica count of 2, some of our services (if deployed with 4 replicas) have only 1 or 2 shown as up in Ingress. This means that we get the application not available error page even if internal all health checks are successful. If we do scale the router down to one, alle service are always shown as up, my guess was that multiple replicas are splitting the services and pods. However, every ingress router should be route to every pod from all service (if we do not activate shading) right? Do we miss something in configuration?

**Version**

4.6.0-0.okd-2020-12-12-135354 

**How reproducible**

deploy more than one ingress router and catch all routes with them (we see this also with newest update)

**Log bundle**

https://drive.google.com/file/d/1Q9q-b5PTVBSyYvgBgAFfDgawKny1vLIf/view?usp=sharing

**Comment by vrutkovs** [comment] 2021-02-05 10:10
You only have one router pod and it shows that SDN is not stable:
>request.go:1001] Unexpected error when reading response body: read tcp 10.129.0.33:43430->172.30.0.1:443: read: connection reset by peer

ovn-controller logs are filled with
>2021-01-24T22:40:15.461166190Z 2021-01-24T22:40:15Z|280472|poll_loop|INFO|wakeup due to [POLLIN] on fd 13 (<->/var/run/openvswitch/db.sock) at lib/stream-fd.c:157 (56% CPU usage)

So its a dupe of #405

**Closed by vrutkovs** 2021-02-05 10:10 UTC
