### ISSUE TITLE
Not able to bootstrap  control plane in UPI  

### ISSUE THREAD

**Issue by sredd128** [openshift/okd#249] opened 2020-07-07 15:40 UTC
**Describe the bug**

Boot Strap of the control plane is failing/timing out. Look like no activity is going on the masters while bootstrapping

# openshift-install --dir=. wait-for bootstrap-complete --log-level=debug
DEBUG OpenShift Installer 4.4.0-0.okd-2020-05-23-055148-beta5 
DEBUG Built from commit 0f0142e7261349b93c3dd3dd02a9ce164dfd2d4f 
INFO Waiting up to 20m0s for the Kubernetes API at https://api.origindev.company.com:6443... 
INFO API v1.17.1 up                               
INFO Waiting up to 40m0s for bootstrapping to complete... 
W0707 08:04:12.561956   22006 reflector.go:326] k8s.io/client-go/tools/watch/informerwatcher.go:146: watch of *v1.ConfigMap ended with: very short watch: k8s.io/client-go/tools/watch/informerwatcher.go:146: Unexpected watch close - watch lasted less than a second and no items received
W0707 08:24:31.118969   22006 reflector.go:326] k8s.io/client-go/tools/watch/informerwatcher.go:146: watch of *v1.ConfigMap ended with: very short watch: k8s.io/client-go/tools/watch/informerwatcher.go:146: Unexpected watch close - watch lasted less than a second and no items received
INFO Use the following commands to gather logs from the cluster 
INFO openshift-install gather bootstrap --help    
FATAL failed to wait for bootstrapping to complete: timed out waiting for the condition 

**Version**
 OpenShift Installer 4.4.0-0.okd-2020-05-23-055148-beta5  UPI 

**How reproducible**
 100%  

**Log bundle**

**Comment by sabarish196** [comment] 2020-07-08 20:25
[log-bundle.tar.gz](https://github.com/openshift/okd/files/4893077/log-bundle.tar.gz)

**Comment by sabarish196** [comment] 2020-07-08 20:26
We see that Master nodes failed to start kubelet. and also attached the log-bundle 

Jul 07 15:34:51 master1.origindev.gbt.gbtad.com systemd[1]: Starting Kubernetes Kubelet...
Jul 07 15:34:51 master1.origindev.gbt.gbtad.com systemd[22114]: kubelet.service: Failed to execute command: No such file or directory
Jul 07 15:34:51 master1.origindev.gbt.gbtad.com systemd[22114]: kubelet.service: Failed at step EXEC spawning /usr/bin/hyperkube: No such file or directory
Jul 07 15:34:51 master1.origindev.gbt.gbtad.com systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
Jul 07 15:34:51 master1.origindev.gbt.gbtad.com systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jul 07 15:34:51 master1.origindev.gbt.gbtad.com systemd[1]: Failed to start Kubernetes Kubelet.
Jul 07 15:35:02 master1.origindev.gbt.gbtad.com systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 6029.
Jul 07 15:35:02 master1.origindev.gbt.gbtad.com systemd[1]: Stopped Kubernetes Kubelet.

**Comment by vrutkovs** [comment] 2020-07-08 20:55
@sabarish196 @sredd128 is it reproducible on beta6 and latest stable FCOS image?

**Comment by sredd128** [comment] 2020-07-09 15:14
Our FCOS image is latest.

but we haven't tried beta 6. is this some issue in beta 5 ?  we tried running bootstrap multiple time and we see the same issue all the time.

**Comment by vrutkovs** [comment] 2020-07-09 17:01
log-bundle would tell us more, but generally its pointless to fix bugs in beta5 if its not reproducible in beta6

**Comment by sredd128** [comment] 2020-07-10 14:42
We tried with Beta6 and we see a new issue. 

we are not sure why it is calling https://api-int.origindev.gbt.gbtad.com:6443/apis/operator.openshift.io/v1/etcds?
Api-int on 6443 , 

Jul 10 14:36:32 bootstrap.origindev.gbt.gbtad.com bootkube.sh[508253]: E0710 14:36:32.839435       1 reflector.go:178] k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Etcd: Get https://api-int.origindev.gbt.gbtad.com:6443/apis/operator.openshift.io/v1/etcds?fieldSelector=metadata.name%3Dcluster&limit=500&resourceVersion=0: dial tcp 10.156.202.176:6443: connect: connection refused
Jul 10 14:37:11 bootstrap.origindev.gbt.gbtad.com bootkube.sh[508253]: E0710 14:37:11.529687       1 reflector.go:178] k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Etcd: Get https://api-int.origindev.gbt.gbtad.com:6443/apis/operator.openshift.io/v1/etcds?fieldSelector=metadata.name%3Dcluster&limit=500&resourceVersion=0: dial tcp 10.156.202.176:6443: connect: connection refused
Jul 10 14:37:56 bootstrap.origindev.gbt.gbtad.com bootkube.sh[508253]: E0710 14:37:56.942882       1 reflector.go:178] k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Etcd: Get https://api-int.origindev.gbt.gbtad.com:6443/apis/operator.openshift.io/v1/etcds?fieldSelector=metadata.name%3Dcluster&limit=500&resourceVersion=0: dial tcp 10.156.202.176:6443: connect: connection refused
Jul 10 14:38:31 bootstrap.origindev.gbt.gbtad.com bootkube.sh[508253]: E0710 14:38:31.788165       1 reflector.go:178] k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Etcd: Get https://api-int.origindev.gbt.gbtad.com:6443/apis/operator.openshift.io/v1/etcds?fieldSelector=metadata.name%3Dcluster&limit=500&resourceVersion=0: dial tcp 10.156.202.176:6443: connect: connection refused
Jul 10 14:39:20 bootstrap.origindev.gbt.gbtad.com bootkube.sh[508253]: E0710 14:39:20.994766       1 reflector.go:178] k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Etcd: Get https://api-int.origindev.gbt.gbtad.c




All master were up but in not ready state. 


NAME                              STATUS     ROLES           AGE   VERSION
master1.origindev.gbt.gbtad.com   NotReady   master,worker   61m   v1.18.3
master2.origindev.gbt.gbtad.com   NotReady   master,worker   54m   v1.18.3
master3.origindev.gbt.gbtad.com   NotReady   master,worker   53m   v1.18.3

**Comment by sredd128** [comment] 2020-07-10 14:57
And boot strap fails with 

 openshift-install wait-for bootstrap-complete  --log-level=debug
DEBUG OpenShift Installer 4.5.0-0.okd-2020-06-29-110348-beta6 
DEBUG Built from commit 8aef4e30b79652038fbff0ae73184177401d56dc 
INFO Waiting up to 20m0s for the Kubernetes API at https://api.origindev.gbt.gbtad.com:6443... 
INFO API v1.18.3 up                               
INFO Waiting up to 40m0s for bootstrapping to complete... 
W0710 07:44:33.369612    3128 reflector.go:326] k8s.io/client-go/tools/watch/informerwatcher.go:146: watch of *v1.ConfigMap ended with: very short watch: k8s.io/client-go/tools/watch/informerwatcher.go:146: Unexpected watch close - watch lasted less than a second and no items received
ERROR Cluster operator authentication Degraded is True with ConfigObservation_Error::IngressStateEndpoints_MissingEndpoints::RouterCerts_NoRouterCertSecret: RouterCertsDegraded: secret/v4-0-config-system-router-certs -n openshift-authentication: could not be retrieved: secret "v4-0-config-system-router-certs" not found
ConfigObservationDegraded: secret "v4-0-config-system-router-certs" not found
IngressStateEndpointsDegraded: No endpoints found for oauth-server 
INFO Cluster operator authentication Progressing is Unknown with NoData:  
INFO Cluster operator authentication Available is Unknown with NoData:  
INFO Cluster operator csi-snapshot-controller Progressing is True with _AsExpected: Progressing: Waiting for Deployment to deploy csi-snapshot-controller pods 
INFO Cluster operator csi-snapshot-controller Available is False with _AsExpected: Available: Waiting for Deployment to deploy csi-snapshot-controller pods 
ERROR Cluster operator dns Degraded is True with NotAllDNSesAvailable: Not all desired DNS DaemonSets available 
INFO Cluster operator dns Progressing is True with Reconciling: At least 1 DNS DaemonSet is progressing. 
INFO Cluster operator dns Available is False with DNSUnavailable: No DNS DaemonSets available 
ERROR Cluster operator etcd Degraded is True with NodeController_MasterNodesReady::StaticPods_Error: NodeControllerDegraded: The master nodes not ready: node "master1.origindev.gbt.gbtad.com" not ready since 2020-07-10 13:55:50 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.), node "master2.origindev.gbt.gbtad.com" not ready since 2020-07-10 13:55:52 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.), node "master3.origindev.gbt.gbtad.com" not ready since 2020-07-10 13:55:50 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.)
StaticPodsDegraded: pod/etcd-master2.origindev.gbt.gbtad.com container "etcd" is not ready: PodInitializing: 
StaticPodsDegraded: pod/etcd-master2.origindev.gbt.gbtad.com container "etcd-metrics" is not ready: PodInitializing: 
StaticPodsDegraded: pod/etcd-master2.origindev.gbt.gbtad.com container "etcdctl" is not ready: PodInitializing: 
StaticPodsDegraded: pod/etcd-master2.origindev.gbt.gbtad.com container "rollbackcopier" is not ready: PodInitializing: 
StaticPodsDegraded: pods "etcd-master3.origindev.gbt.gbtad.com" not found 
INFO Cluster operator etcd Progressing is True with NodeInstaller: NodeInstallerProgressing: 2 nodes are at revision 0; 1 nodes are at revision 2 
ERROR Cluster operator kube-apiserver Degraded is True with InstallerPodContainerWaiting_ContainerCreating::NodeController_MasterNodesReady::NodeInstaller_InstallerPodFailed::StaticPods_Error: NodeInstallerDegraded: 1 nodes are failing on revision 2:
NodeInstallerDegraded: static pod of revision 2 has been installed, but is not ready while new revision 3 is pending; 1 nodes are failing on revision 3:
NodeInstallerDegraded: static pod of revision 3 has been installed, but is not ready while new revision 5 is pending
StaticPodsDegraded: pod/kube-apiserver-master2.origindev.gbt.gbtad.com container "kube-apiserver" is not ready: PodInitializing: 
StaticPodsDegraded: pod/kube-apiserver-master2.origindev.gbt.gbtad.com container "kube-apiserver-cert-regeneration-controller" is not ready: PodInitializing: 
StaticPodsDegraded: pod/kube-apiserver-master2.origindev.gbt.gbtad.com container "kube-apiserver-cert-syncer" is not ready: PodInitializing: 
StaticPodsDegraded: pod/kube-apiserver-master2.origindev.gbt.gbtad.com container "kube-apiserver-insecure-readyz" is not ready: PodInitializing: 
StaticPodsDegraded: pods "kube-apiserver-master3.origindev.gbt.gbtad.com" not found
NodeControllerDegraded: The master nodes not ready: node "master2.origindev.gbt.gbtad.com" not ready since 2020-07-10 13:55:52 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.), node "master1.origindev.gbt.gbtad.com" not ready since 2020-07-10 13:55:50 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.), node "master3.origindev.gbt.gbtad.com" not ready since 2020-07-10 13:55:50 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.)
InstallerPodContainerWaitingDegraded: Pod "installer-5-master3.origindev.gbt.gbtad.com" on node "master3.origindev.gbt.gbtad.com" container "installer" is waiting for 16m37.968728493s because "" 
INFO Cluster operator kube-apiserver Progressing is True with NodeInstaller: NodeInstallerProgressing: 3 nodes are at revision 0; 0 nodes have achieved new revision 6 
INFO Cluster operator kube-apiserver Available is False with StaticPods_ZeroNodesActive: StaticPodsAvailable: 0 nodes are active; 3 nodes are at revision 0; 0 nodes have achieved new revision 6 
ERROR Cluster operator kube-controller-manager Degraded is True with InstallerPodContainerWaiting_ContainerCreating::NodeController_MasterNodesReady::NodeInstaller_InstallerPodFailed::StaticPods_Error: NodeInstallerDegraded: 1 nodes are failing on revision 3:
NodeInstallerDegraded: static pod of revision 3 has been installed, but is not ready while new revision 4 is pending; 1 nodes are failing on revision 4:
NodeInstallerDegraded: static pod of revision 4 has been installed, but is not ready while new revision 5 is pending
StaticPodsDegraded: pod/kube-controller-manager-master2.origindev.gbt.gbtad.com container "cluster-policy-controller" is not ready: PodInitializing: 
StaticPodsDegraded: pod/kube-controller-manager-master2.origindev.gbt.gbtad.com container "kube-controller-manager" is not ready: PodInitializing: 
StaticPodsDegraded: pod/kube-controller-manager-master2.origindev.gbt.gbtad.com container "kube-controller-manager-cert-syncer" is not ready: PodInitializing: 
StaticPodsDegraded: pod/kube-controller-manager-master2.origindev.gbt.gbtad.com container "kube-controller-manager-recovery-controller" is not ready: PodInitializing: 
StaticPodsDegraded: pods "kube-controller-manager-master3.origindev.gbt.gbtad.com" not found
NodeControllerDegraded: The master nodes not ready: node "master2.origindev.gbt.gbtad.com" not ready since 2020-07-10 13:55:52 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.), node "master3.origindev.gbt.gbtad.com" not ready since 2020-07-10 13:55:50 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.), node "master1.origindev.gbt.gbtad.com" not ready since 2020-07-10 13:55:50 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.)
InstallerPodContainerWaitingDegraded: Pod "installer-5-master3.origindev.gbt.gbtad.com" on node "master3.origindev.gbt.gbtad.com" container "installer" is waiting for 16m50.314070929s because "" 
INFO Cluster operator kube-controller-manager Progressing is True with NodeInstaller: NodeInstallerProgressing: 3 nodes are at revision 0; 0 nodes have achieved new revision 7 
INFO Cluster operator kube-controller-manager Available is False with StaticPods_ZeroNodesActive: StaticPodsAvailable: 0 nodes are active; 3 nodes are at revision 0; 0 nodes have achieved new revision 7 
ERROR Cluster operator kube-scheduler Degraded is True with InstallerPodContainerWaiting_ContainerCreating::NodeController_MasterNodesReady::NodeInstaller_InstallerPodFailed::StaticPods_Error: NodeInstallerDegraded: 1 nodes are failing on revision 3:
NodeInstallerDegraded: static pod of revision 3 has been installed, but is not ready while new revision 4 is pending; 1 nodes are failing on revision 4:
NodeInstallerDegraded: static pod of revision 4 has been installed, but is not ready while new revision 5 is pending
StaticPodsDegraded: pod/openshift-kube-scheduler-master2.origindev.gbt.gbtad.com container "kube-scheduler" is not ready: PodInitializing: 
StaticPodsDegraded: pod/openshift-kube-scheduler-master2.origindev.gbt.gbtad.com container "kube-scheduler-cert-syncer" is not ready: PodInitializing: 
StaticPodsDegraded: pods "openshift-kube-scheduler-master3.origindev.gbt.gbtad.com" not found
NodeControllerDegraded: The master nodes not ready: node "master1.origindev.gbt.gbtad.com" not ready since 2020-07-10 13:55:50 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.), node "master2.origindev.gbt.gbtad.com" not ready since 2020-07-10 13:55:52 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.), node "master3.origindev.gbt.gbtad.com" not ready since 2020-07-10 13:55:50 +0000 UTC because NodeStatusUnknown (Kubelet stopped posting node status.)
InstallerPodContainerWaitingDegraded: Pod "installer-5-master3.origindev.gbt.gbtad.com" on node "master3.origindev.gbt.gbtad.com" container "installer" is waiting for 16m39.168760349s because "" 
INFO Cluster operator kube-scheduler Progressing is True with NodeInstaller: NodeInstallerProgressing: 3 nodes are at revision 0; 0 nodes have achieved new revision 6 
INFO Cluster operator kube-scheduler Available is False with StaticPods_ZeroNodesActive: StaticPodsAvailable: 0 nodes are active; 3 nodes are at revision 0; 0 nodes have achieved new revision 6 
INFO Cluster operator kube-storage-version-migrator Available is False with _NoMigratorPod: Available: deployment/migrator.openshift-kube-storage-version-migrator: no replicas are available 
INFO Cluster operator machine-config Progressing is True with : Working towards 4.5.0-0.okd-2020-06-29-110348-beta6 
ERROR Cluster operator machine-config Degraded is True with MachineConfigDaemonFailed: Unable to apply 4.5.0-0.okd-2020-06-29-110348-beta6: timed out waiting for the condition during waitForDaemonsetRollout: Daemonset machine-config-daemon is not ready. status: (desired: 3, updated: 3, ready: 0, unavailable: 3) 
INFO Cluster operator machine-config Available is False with : Cluster not available for 4.5.0-0.okd-2020-06-29-110348-beta6 
ERROR Cluster operator network Degraded is True with RolloutHung: DaemonSet "openshift-multus/multus" rollout is not making progress - last change 2020-07-10T13:55:52Z
DaemonSet "openshift-sdn/sdn-controller" rollout is not making progress - last change 2020-07-10T13:55:51Z 
INFO Cluster operator network Progressing is True with Deploying: DaemonSet "openshift-multus/multus" is not available (awaiting 3 nodes)
DaemonSet "openshift-multus/multus-admission-controller" is waiting for other operators to become ready
DaemonSet "openshift-sdn/sdn-controller" is not yet scheduled on any nodes
DaemonSet "openshift-sdn/ovs" is not available (awaiting 3 nodes)
DaemonSet "openshift-sdn/sdn" is not available (awaiting 3 nodes) 
INFO Cluster operator node-tuning Available is False with TunedUnavailable: DaemonSet "tuned" has no available Pod(s). 
INFO Cluster operator openshift-apiserver Available is False with APIServices_PreconditionNotReady: APIServicesAvailable: PreconditionNotReady 
INFO Cluster operator openshift-controller-manager Progressing is True with :  
INFO Cluster operator openshift-controller-manager Available is False with :  
INFO Cluster operator operator-lifecycle-manager-packageserver Available is False with :  
INFO Cluster operator operator-lifecycle-manager-packageserver Progressing is True with : Working toward 0.15.1 
INFO Cluster operator service-ca Progressing is True with _ManagedDeploymentsAvailable: Progressing: 
Progressing: service-ca does not have available replicas 
INFO Use the following commands to gather logs from the cluster 
INFO openshift-install gather bootstrap --help    
FATAL failed to wait for bootstrapping to complete: timed out waiting for the condition

**Comment by cgruver** [comment] 2020-07-10 15:41
Double check your DNS and Load Balancer configurations.

It looks like `10.156.202.176` is the IP resolved from `api-int.origindev.gbt.gbtad.com`.  Is that your load-balancer?

Does `api.origindev.gbt.gbtad.com` resolve to the same IP address?

**Comment by sredd128** [comment] 2020-07-10 16:04
No. api.origindev.gbt.gbtad.com. has a different IP. 

i even noticed, in masters in   /etc/kubernetes/kubeconfig  file under the server it is appending  https://api-int.origindev.gbt.gbtad.com:6443

we need to manually edit the kubeconfig file to start the masters

**Comment by cgruver** [comment] 2020-07-10 17:08
Are you following some specific documentation?  My clusters are configured in such a way that api and api-int are resolving to the same load balancer.  If you only have three master nodes that are also schedulable, you need that configuration as well.

`api.origindev.gbt.gbtad.com`, and `api-int.origindev.gbt.gbtad.com` should resolve to your external load balancer, and your load balancer should be configured to round-robin across the three master nodes plus the boot-strap node.

You will remove the boot-strap node from the configuration when boot-strap completes.

**Comment by sredd128** [comment] 2020-07-10 17:12
Im following this https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html 

we did exactly the same setup that you described. 
api.origindev.gbt.gbtad.com & api-int.origindev.gbt.gbtad.com are External LB endpoints and pool members are 3 masters and one bootstrap node.

**Comment by cgruver** [comment] 2020-07-10 17:17
OK, the fact that you are getting a connection refused from: ` https://api-int.origindev.gbt.gbtad.com:6443` but not from ` https://api.origindev.gbt.gbtad.com:6443`, suggests that you might have an issue with the load balancer configuration of `api-int`.

Double check your config and firewall settings.

**Comment by cgruver** [comment] 2020-07-10 17:22
Explain why you are manually editing the `kubeconfig` files.  You should not need to do that.

**Comment by sredd128** [comment] 2020-07-10 17:22
we used two different ip's/VIP's for  api.origindev.gbt.gbtad.com and api-int.origindev.gbt.gbtad.com

and each VIP has its own pool 
api has master and bootstrap  listen on 6443
api-int has master and bootstrap  listen on 22623 

What is the issue in this config ?  or should we use a single IP for both api and api-int ?

**Comment by sredd128** [comment] 2020-07-10 17:24
> Explain why you are manually editing the `kubeconfig` files. You should not need to do that.

we there is https://api-int.origindev.gbt.gbtad.com:6443 in kubeconfig file, as per our setup connection will fail. 

as we set api-int.origindev.gbt.gbtad.com to only listen on 22623

**Comment by vrutkovs** [comment] 2020-07-10 17:25
>api has master and bootstrap listen on 6443
api-int has master and bootstrap listen on 22623

Both endpoints should listen on both 6443 and 22623, see `Network topology requirements` in https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html

**Comment by cgruver** [comment] 2020-07-10 17:26
Ah!  That's the problem.

`api-int` needs to listen on 6443 as well.  22623 is for machine config.

If you have an internal and external load balancer, they need to be configured as follows:

* Internal, Ports: 80, 443, 6443, 22623

* External, Ports: 80, 443, 6443

**Comment by sredd128** [comment] 2020-07-10 17:44
Thank you @cgruver & @vrutkovs 

we will make the changes to our LB and do an install again. and will update the status here.

**Comment by cgruver** [comment] 2020-07-10 17:49
Great.  That should fix it.

**Comment by vrutkovs** [comment] 2020-07-10 18:27
This is a bugtracker not a discussion platform. We could have find the issue sooner if you'd have provided the log bundle, as requested in the description and my previous comments.

**Comment by sredd128** [comment] 2020-07-10 18:31
thats my bad. i've uploaded the log-bundle for beta5. but you recommended to use beta6. we just completed teh setup of beta6 5 hours ago.  so i missed to upload the bundle.

**Comment by Nurlan199206** [comment] 2020-07-14 04:21
help me please too! i'm trying up cluster on my laptop (3 master, 2 worker) .

my full log bundle
[log-bundle-20200713093318.tar.gz](https://github.com/openshift/okd/files/4916512/log-bundle-20200713093318.tar.gz)


```
 Starting cluster-bootstrap...
Jul 13 13:30:29 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: Starting temporary bootstrap control plane...
Jul 13 13:30:29 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: E0713 13:30:29.935455       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:30 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#1] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:30 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#2] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:30 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#3] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:30 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#4] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:30 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#5] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:30 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: E0713 13:30:30.953382       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:31 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#6] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:31 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#7] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:31 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#8] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:31 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#9] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:31 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#10] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:31 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: E0713 13:30:31.955916       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:32 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#11] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:32 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#12] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:32 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#13] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:32 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#14] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:32 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: [#15] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: dial tcp [::1]:6443: connect: connection refused
Jul 13 13:30:32 okd4-bootstrap.lab.okd.local bootkube.sh[5968]: E0713 13:30:32.956949       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
```

**Comment by Nurlan199206** [comment] 2020-07-14 04:34
i need turn off IPv6 on bootstrap node?

**Comment by vrutkovs** [comment] 2020-07-14 07:34
@Nurlan199206 is it reproducible on RC build? Please open a new ticket to track that

**Comment by cgruver** [comment] 2020-07-14 11:18
/close

The original issue has been resolved through discussion.

**Closed** 2020-07-16 07:38 UTC
Labels: triage/needs-information
