### ISSUE TITLE
Installation error on RHV

### ISSUE THREAD

**Issue by baturorkun** [openshift/okd#646] opened 2021-05-23 18:37 UTC
I tried installation OKD 4.7 on RHV many times.

ERROR Attempted to gather debug logs after installation failure: failed to get bootstrap and control plane host addresses from "install/terraform.tfstate": failed to lookup bootstrap ipv4 address: cannot find IPs for vmId: 95d7481d-623d-43a9-851c-4e2c583c5aa6
FATAL Bootstrap failed to complete: failed to wait for bootstrapping to complete: timed out waiting for the condition

Bootstrapping is not completed and I have only 3 master nodes.

**Comment by vrutkovs** [comment] 2021-05-24 07:05
Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting)

**Comment by baturorkun** [comment] 2021-05-24 09:06
@vrutkovs   I tried to. install 4.6 and error again

ERROR Attempted to gather debug logs after installation failure: failed to create SSH client: failed to use the provided keys for authentication: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
FATAL Bootstrap failed to complete: failed to wait for bootstrapping to complete: timed out waiting for the condition

This time bootstrapping is finished API is ok but there are no workers and apps

When I  try to get log

./openshift-install gather bootstrap --dir=install
INFO Pulling debug logs from the bootstrap machine
FATAL failed to create SSH client: failed to use the provided keys for authentication: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain

**Comment by vrutkovs** [comment] 2021-05-24 09:38
>install 4.6 and error again

Is this reproducible in latest OKD 4.7?

**Comment by baturorkun** [comment] 2021-05-24 09:44
ok np . I will install 4.7 again.

**Comment by baturorkun** [comment] 2021-05-24 11:20
The installation was cancelled again

ERROR Attempted to gather debug logs after installation failure: failed to get bootstrap and control plane host addresses from "install/terraform.tfstate": failed to lookup bootstrap ipv4 address: cannot find IPs for vmId: 9a9fe831-7e82-42fa-a6d7-d44c91222045
FATAL Bootstrap failed to complete: failed to wait for bootstrapping to complete: timed out waiting for the condition

When I try to get log

[root@bastion okd]# ./openshift-install gather bootstrap --dir=install
FATAL failed to get bootstrap and control plane host addresses from "install/terraform.tfstate": failed to lookup bootstrap ipv4 address: cannot find IPs for vmId: 9a9fe831-7e82-42fa-a6d7-d44c91222045

@vrutkovs

**Comment by baturorkun** [comment] 2021-05-24 11:31
[bootstrap.log](https://github.com/openshift/okd/files/6532002/bootstrap.log)

i got log via that command

ssh core@192.168.2.128 "journalctl -b  -u release-image.service -u bootkube.service --no-page" > bootstrap.log

**Comment by vrutkovs** [comment] 2021-05-24 11:36
>cannot find IPs for vmId: 9a9fe831-7e82-42fa-a6d7-d44c91222045

Which machine - bootstrap/master - id is that? Did that machine boot? Does it have IPs assigned?

**Comment by baturorkun** [comment] 2021-05-24 12:42
" 9a9fe831-7e82-42fa-a6d7-d44c91222045" is bootstrap instance and got IP from DHCP.

**Comment by baturorkun** [comment] 2021-05-24 13:17
Meanwhile, this bootstrap instance is still running...  i am attaching new log file
[bootstrap1.log](https://github.com/openshift/okd/files/6532554/bootstrap1.log)

Yesterday night, I waited 12 hours for compilation but never.

**Comment by vrutkovs** [comment] 2021-05-24 15:09
>got IP from DHCP.

Did that IP render on vsphere UI? Does this instance run `vmtoolsd.service`?

**Comment by baturorkun** [comment] 2021-05-24 17:36
@vrutkovs  I don't understand your question. My platform is RHV (oVirt) and used the IPI installation method. Actually, I installed OCP on the same RHV platform  2 months ago and running now and 1 month ago I installed OKD 4.6 but I had some problems. Because  I gave an "OKD" as a cluster name in my opinion. Meanwhile,  At first, I tried to install 4.7 before and failed, therefore I decided to install 4.6. Now I could not install either 4.6 or 4.7 :(

**Comment by baturorkun** [comment] 2021-05-24 17:42
The bootstrap service  still running in loop

````
.....
May 24 17:19:17 localhost bootkube.sh[340365]: Skipped "secret-kube-apiserver-to-kubelet-signer.yaml" secrets.v1./kube-apiserver-to-kubelet-signer -n openshift-kube-apiserver-operator as it already exists
May 24 17:19:18 localhost bootkube.sh[340365]: Skipped "secret-loadbalancer-serving-signer.yaml" secrets.v1./loadbalancer-serving-signer -n openshift-kube-apiserver-operator as it already exists
May 24 17:19:18 localhost bootkube.sh[340365]: Skipped "secret-localhost-serving-signer.yaml" secrets.v1./localhost-serving-signer -n openshift-kube-apiserver-operator as it already exists
May 24 17:19:19 localhost bootkube.sh[340365]: Skipped "secret-service-network-serving-signer.yaml" secrets.v1./service-network-serving-signer -n openshift-kube-apiserver-operator as it already exists
May 24 17:38:40 localhost bootkube.sh[340365]: Error: error while checking pod status: timed out waiting for the condition
May 24 17:38:40 localhost bootkube.sh[340365]: Tearing down temporary bootstrap control plane...
May 24 17:38:40 localhost bootkube.sh[340365]: Error: error while checking pod status: timed out waiting for the condition
May 24 17:38:40 localhost podman[340365]: 2021-05-24 17:38:40.793824833 +0000 UTC m=+1207.822227835 container died 07f1cc2d7a6006b4dde6eed10fb1e178eae94ca45ab247679d5a51dd693191d9 (image=quay.io/openshift/okd-content@sha256:99b54b2c35145c3084d773acabbe0ec94425189ae215c639b87055b55625e066, name=interesting_swirles)
May 24 17:38:41 localhost podman[340365]: 2021-05-24 17:38:41.473043034 +0000 UTC m=+1208.501446024 container remove 07f1cc2d7a6006b4dde6eed10fb1e178eae94ca45ab247679d5a51dd693191d9 (image=quay.io/openshift/okd-content@sha256:99b54b2c35145c3084d773acabbe0ec94425189ae215c639b87055b55625e066, name=interesting_swirles, com.redhat.build-host=cpt-1004.osbs.prod.upshift.rdu2.redhat.com, io.openshift.build.name=, io.openshift.release.operator=true, io.openshift.build.commit.message=, io.openshift.expose-services=, architecture=x86_64, io.openshift.build.namespace=, version=v4.0, build-date=2021-01-09T00:40:49.580557, maintainer=Red Hat, Inc., url=https://access.redhat.com/containers/#/registry.access.redhat.com/openshift/ose-base/images/v4.0-202101090039.11723, com.redhat.license_terms=https://www.redhat.com/agreements, io.openshift.build.source-context-dir=, summary=Provides the latest release of Red Hat Universal Base Image 8., io.k8s.display-name=OpenShift Base, vendor=Red Hat, Inc., io.buildah.version=1.16.4, vcs-url=https://github.com/openshift/cluster-bootstrap, io.openshift.tags=base rhel8, vcs-type=git, vcs-ref=6665cae3374c18d466f11c9e0b8e41a61fcb0819, distribution-scope=public, io.openshift.build.source-location=https://github.com/openshift/cluster-bootstrap, io.openshift.build.commit.author=, io.openshift.build.commit.ref=master, name=openshift/ose-base, release=202101090039.11723, description=The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly., io.k8s.description=This is the base image from which all OpenShift images inherit., com.redhat.component=openshift-enterprise-base-container, io.openshift.build.commit.id=6665cae3374c18d466f11c9e0b8e41a61fcb0819, io.openshift.build.commit.date=)
May 24 17:38:41 localhost systemd[1]: bootkube.service: Main process exited, code=exited, status=1/FAILURE
May 24 17:38:41 localhost systemd[1]: bootkube.service: Failed with result 'exit-code'.
May 24 17:38:46 localhost systemd[1]: bootkube.service: Scheduled restart job, restart counter is at 22.
May 24 17:38:46 localhost systemd[1]: Stopped Bootstrap a Kubernetes cluster.
May 24 17:38:46 localhost systemd[1]: Started Bootstrap a Kubernetes cluster.
May 24 17:38:47 localhost podman[354708]: 2021-05-24 17:38:47.004666943 +0000 UTC m=+0.202675520 container create 127672f714c39d60dd8e63e5c72f1b8cca4fc897a1ef80611e3b4ce6732cb47b (image=quay.io/openshift/okd@sha256:301cd36b2ab370027ddb0ec43e540a03a24748a25b69578dec504d130475304b, name=cranky_khayyam, io.openshift.release.base-image-digest=sha256:bdb9d78eef0258d55a2ffac0d7dcb1ac25bc9143d1528b34a0efcca444a52362, io.openshift.release=4.7.0-0.okd-2021-05-22-050008)
May 24 17:38:47 localhost podman[354708]: 2021-05-24 17:38:47.101221462 +0000 UTC m=+0.299230051 container init 127672f714c39d60dd8e63e5c72f1b8cca4fc897a1ef80611e3b4ce6732cb47b (image=quay.io/openshift/okd@sha256:301cd36b2ab370027ddb0ec43e540a03a24748a25b69578dec504d130475304b, name=cranky_khayyam, io.openshift.release.base-image-digest=sha256:bdb9d78eef0258d55a2ffac0d7dcb1ac25bc9143d1528b34a0efcca444a52362, io.openshift.release=4.7.0-0.okd-2021-05-22-050008)
May 24 17:38:47 localhost podman[354708]: 2021-05-24 17:38:47.13621319 +0000 UTC m=+0.334221771 container start 127672f714c39d60dd8e63e5c72f1b8cca4fc897a1ef80611e3b4ce6732cb47b (image=quay.io/openshift/okd@sha256:301cd36b2ab370027ddb0ec43e540a03a24748a25b69578dec504d130475304b, name=cranky_khayyam, io.openshift.release.base-image-digest=sha256:bdb9d78eef0258d55a2ffac0d7dcb1ac25bc9143d1528b34a0efcca444a52362, io.openshift.release=4.7.0-0.okd-2021-05-22-050008)
......
```

**Comment by baturorkun** [comment] 2021-05-25 07:53
Is there any tests on RHV? I am suspect because OCP has a bug and I detected it and created a case one month ago and now Redhat is working on it. And I could install OKD on different platforms easily but RHV. It is interesting because RHV is a Redhat product.

**Comment by vrutkovs** [comment] 2021-05-25 07:58
Oh, sorry, I misread the platform as vsphere instead of ovirt.

I don't think we have oVirt tests for OKD, but we have those for [OCP](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.8-e2e-ovirt/1397003453586214912).

You'd need to figure out why bootstrap is not setting the address on oVirt (and terraform can't record that IP).

**Comment by baturorkun** [comment] 2021-05-25 14:57
@vrutkovs  
I download "openshift-install-linux-4.6.0-0.okd-2020-11-27-200126.tar.gz" and I succeded. It is the first 4.6 version.

I had errors but installation was completed by bootstrap instance and the bootstrap instance is still up, could not be destroyed.
But I can assess the console and OKD is running. I tried the last version of 4.6 yesterday, It has a problem.  I think there is a problem after a specific version 4.6


```
INFO Obtaining RHCOS image file from 'https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20201004.3.0/x86_64/fedora-coreos-32.20201004.3.0-openstack.x86_64.qcow2.xz?sha256=6065c21bf6903bf72cce8c5f57c1a07232e93aa85132834baa5859d56ee4ef9a'
INFO Creating infrastructure resources...
INFO Waiting up to 20m0s for the Kubernetes API at https://api.dev.example.com:6443...
INFO API v1.19.0-rc.2.1077+43983cda8af930-dirty up
INFO Waiting up to 30m0s for bootstrapping to complete...
E0525 09:11:59.926112  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=443&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:00.931310  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=420&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:01.934437  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=562&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:02.936942  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=561&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:03.939854  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=488&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:04.942664  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=415&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:05.946130  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=392&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:06.948573  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=422&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:07.951603  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=416&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:08.953989  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=438&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:09.957156  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=488&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:10.959582  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=579&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:11.962082  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=534&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:12.965246  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=491&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:13.969226  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=597&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:14.972422  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=452&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:15.975852  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=309&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:16.979020  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=427&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:17.981949  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=407&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:18.984698  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=494&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused
E0525 09:12:19.987689  703992 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get "https://api.dev.example.com:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=4171&timeoutSeconds=400&watch=true": dial tcp 192.168.2.48:6443: connect: connection refused



INFO Cluster operator authentication Progressing is Unknown with NoData:
INFO Cluster operator authentication Available is Unknown with NoData:
INFO Cluster operator kube-controller-manager Progressing is True with NodeInstaller: NodeInstallerProgressing: 3 nodes are at revision 0; 0 nodes have achieved new revision 1
INFO Cluster operator kube-controller-manager Available is False with StaticPods_ZeroNodesActive: StaticPodsAvailable: 0 nodes are active; 3 nodes are at revision 0; 0 nodes have achieved new revision 1
INFO Cluster operator machine-config Progressing is True with : Working towards 4.6.0-0.okd-2020-11-27-200126
INFO Cluster operator network Progressing is True with Deploying: DaemonSet "openshift-multus/network-metrics-daemon" is not available (awaiting 3 nodes)
DaemonSet "openshift-multus/multus-admission-controller" is not available (awaiting 3 nodes)
INFO Pulling debug logs from the bootstrap machine
ERROR Attempted to gather debug logs after installation failure: failed to create SSH client: failed to use the provided keys for authentication: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
FATAL Bootstrap failed to complete: failed to wait for bootstrapping to complete: timed out waiting for the condition
````

**Comment by tdemaret** [comment] 2021-05-25 15:46
I have the same problem with my deployment, I fix with : 
## Generate ignition files 
openshift-install create ignition-configs --dir install

## Modify timeouts
sed -i 's/"timeouts":{}/"timeouts":{"httpResponseHeaders":30}/' install/*.ign 

## Create the cluster
openshift-install create cluster --dir=install/  --log-level=debug

For me, it works now.

My 2 cents

**Comment by baturorkun** [comment] 2021-05-25 21:14
hi @tdemaret 
which version did you install?

**Comment by tdemaret** [comment] 2021-05-26 07:29
I have this issue with 4.5 and 4.6, I don't try with 4.7 (just update my cluster).

**Comment by baturorkun** [comment] 2021-05-27 07:34
hi @tdemaret 
I think config JSON was changed for 4.7. There are  no timeouts key in bootstrap.ign

I found that

```
 --runtime-request-timeout=${KUBELET_RUNTIME_REQUEST_TIMEOUT}
````

**Comment by vrutkovs** [comment] 2021-05-27 10:01
So, its a regression in 4.7? Is it reproducible in 4.8 nightlies? Did you get any information where it could be?

**Comment by baturorkun** [comment] 2021-05-27 11:13
@vrutkovs 
This is  the last 4.7

[root@bastion okd]# ./openshift-install version
./openshift-install 4.7.0-0.okd-2021-05-22-050008
built from commit ba1a5fc61dd3be134a24fa6d89ae24012a93385a
release image quay.io/openshift/okd@sha256:301cd36b2ab370027ddb0ec43e540a03a24748a25b69578dec504d130475304b

I  run :
./openshift-install create ignition-configs --dir install

when I check the bootstrap.ign

````
   "contents": "[Unit]\nDescription=Kubernetes Kubelet\nWants=rpc-statd.service crio.service release-image.service\nAfter=crio.service release-image.service\n\n[Service]\nType=notify\nExecStartPre=/bin/mkdir --parents /etc/kubernetes/manifests\nExecStartPre=/bin/mkdir --parents /etc/kubernetes/kubelet-plugins/volume/exec\nExecStartPre=/usr/local/bin/kubelet-pause-image.sh\nEnvironment=KUBELET_RUNTIME_REQUEST_TIMEOUT=10m\nEnvironmentFile=-/etc/kubernetes/kubelet-env\nEnvironmentFile=-/etc/kubernetes/kubelet-pause-image-override\n\nExecStart=/usr/bin/hyperkube \\\n  kubelet \\\n    --anonymous-auth=false \\\n    --container-runtime=remote \\\n    --container-runtime-endpoint=/var/run/crio/crio.sock \\\n    --runtime-request-timeout=${KUBELET_RUNTIME_REQUEST_TIMEOUT} \\\n    --pod-manifest-path=/etc/kubernetes/manifests \\\n    --minimum-container-ttl-duration=6m0s \\\n    --cluster-domain=cluster.local \\\n    --cgroup-driver=systemd \\\n    --serialize-image-pulls=false \\\n    --v=2 \\\n    --volume-plugin-dir=/etc/kubernetes/kubelet-plugins/volume/exec \\\n    --pod-infra-container-image=${MACHINE_CONFIG_INFRA_IMAGE}\n\nRestart=always\nRestartSec=10\n\n[Install]\nWantedBy=multi-user.target\n",
        "enabled": true,
        "name": "kubelet.service"
      },
```

**Comment by baturorkun** [comment] 2021-05-27 11:28
@vrutkovs 
I downloaded 4.8
```
[root@bastion okd]# ./openshift-install version
./openshift-install 4.8.0-0.okd-2021-05-27-020828
built from commit 4b15f0537ad76206c8ba9ba042b404f8c00a295a
release image registry.ci.openshift.org/origin/release@sha256:9a2317e206328b7187420ea1e7561d9191c30bca539b3548f566b17abdd5a036
```
Now, there is no timeouts key in ign files

```
        "contents": "[Unit]\nDescription=Kubernetes Kubelet\nWants=rpc-statd.service crio.service release-image.service\nAfter=crio.service release-image.service\n\n[Service]\nType=notify\nNotifyAccess=all\nExecStartPre=/bin/mkdir --parents /etc/kubernetes/manifests\nExecStartPre=/bin/mkdir --parents /etc/kubernetes/kubelet-plugins/volume/exec\nExecStartPre=/usr/local/bin/kubelet-pause-image.sh\nEnvironment=KUBELET_RUNTIME_REQUEST_TIMEOUT=10m\nEnvironmentFile=-/etc/kubernetes/kubelet-env\nEnvironmentFile=-/etc/kubernetes/kubelet-pause-image-override\n\nExecStart=/usr/local/bin/kubelet.sh\n\nRestart=always\nRestartSec=10\n\n[Install]\nWantedBy=multi-user.target\n",
        "enabled": true,
        "name": "kubelet.service"
      },
```

**Comment by vrutkovs** [comment] 2021-05-27 11:46
Timeouts have absolutely nothing to do with that. The issue is that oVirt can't get bootstrap's IP address. Perhaps we don't start qemu-agent service in 4.7 (fairly certain we do in 4.8)

**Comment by baturorkun** [comment] 2021-05-27 12:46
Meanwhile, I tried to install  4.8 on RHV 4.4

```
INFO Obtaining RHCOS image file from 'https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/34.20210427.3.0/x86_64/fedora-coreos-34.20210427.3.0-openstack.x86_64.qcow2.xz?sha256=55ef751cca6f46cf7a603a18786479b14cf5a8060df4ef03839581ada0f5324c' ***************************************************************************************************************************************************************************************************************************INFO Creating infrastructure resources...         ********************************************************************************************************************************************************************************************ERROR                                              *******************************************************************************************************************************************************************************************ERROR Error: updating the VM (f6267568-21e3-49cb-8c47-57c114a5d273) with auto pinning policy failed! failed to set the auto pinning policy on the VM!, Failed to find StartElement ***********************************************************ERROR                                              *******************************************************************************************************************************************************************************************ERROR   on ../../tmp/openshift-install-619524212/masters/main.tf line 1, in resource "ovirt_vm" "master": ************************************************************************************************************************************ERROR    1: resource "ovirt_vm" "master" {         *******************************************************************************************************************************************************************************************ERROR                                              *******************************************************************************************************************************************************************************************ERROR                                              ********************************************************************************************************************************************
ERROR
ERROR Error: updating the VM (ea3e3209-ffd1-421c-b38e-60764ca9ba83) with auto pinning policy failed! failed to set the auto pinning policy on the VM!, Failed to find StartElement
ERROR
ERROR   on ../../tmp/openshift-install-619524212/masters/main.tf line 1, in resource "ovirt_vm" "master":
ERROR    1: resource "ovirt_vm" "master" {
ERROR
ERROR
ERROR
ERROR Error: updating the VM (21b5194b-694a-42d5-87a8-f23807f426b1) with auto pinning policy failed! failed to set the auto pinning policy on the VM!, Failed to find StartElement
ERROR
ERROR   on ../../tmp/openshift-install-619524212/masters/main.tf line 1, in resource "ovirt_vm" "master":
ERROR    1: resource "ovirt_vm" "master" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
```

**Comment by vrutkovs** [comment] 2021-05-27 14:57
>failed to set the auto pinning policy on the VM

looks like an ovirt error

**Comment by vrutkovs** [comment] 2021-06-02 07:20
Seems we were missing [liburing](https://github.com/openshift/okd-machine-os/commit/66fb534212672fabcc473690fe512a06e8bb5ed1#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2R30) as a new dependency for `qemu-agent` in 4.7. This was fixed in latest [4.7 nightlies](https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/#4.7.0-0.okd) - could you give one of these a try?

**Closed** 2021-06-20 07:25 UTC

**Comment by baturorkun** [comment] 2021-06-20 09:16
hi vadim
The problem continues and I think It is important because RHV is a RedHat product. Today I will try the different version from nightlies. Please do not close this issue.

**Comment by baturorkun** [comment] 2021-07-07 10:54
It is like a joke!!!
OKD is not installing on ovirt/rhv. neither version 4.6 nor version 4.7. Even, version 4.8 can not be started the installation process.
