### ISSUE TITLE
OKD4.7 version 4.7.0-0.okd-2021-03-21-094146 UPI found error on bootstrap node

### ISSUE THREAD

**Issue by squaltum** [openshift/okd#570] opened 2021-03-22 01:07 UTC
**Describe the bug**

**Version**
4.7.0-0.okd-2021-03-21-094146
UPI deployment

**How reproducible**
100% deploy

**Log**
On bootstrap node
journalctl -b -f -u release-image.service -u bootkube.service

Mar 22 01:02:02 bootstrap01 release-image-download.sh[1502]:         * error copying from container: error during bulk transfer for copier.request{Request:"GET", Root:"/", preservedRoot:"/var/lib/containers/storage/overlay/b7917bb68f0ba5ed6223e796d035e31b1a520a9fa243cc72e657dbe26b34b02a/merged", rootPrefix:"/var/lib/containers/storage/overlay/b7917bb68f0ba5ed6223e796d035e31b1a520a9fa243cc72e657dbe26b34b02a/merged", Directory:"/", preservedDirectory:"/var/lib/containers/storage/overlay/b7917bb68f0ba5ed6223e796d035e31b1a520a9fa243cc72e657dbe26b34b02a/merged", Globs:[]string{"/"}, preservedGlobs:[]string{"/var/lib/containers/storage/overlay/b7917bb68f0ba5ed6223e796d035e31b1a520a9fa243cc72e657dbe26b34b02a/merged/."}, StatOptions:copier.StatOptions{CheckForArchives:false, Excludes:[]string(nil)}, GetOptions:copier.GetOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), Excludes:[]string(nil), ExpandArchives:false, ChownDirs:(*idtools.IDPair)(0xc0000438e0), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(0xc0000438f0), ChmodFiles:(*os.FileMode)(nil), StripSetuidBit:false, StripSetgidBit:false, StripStickyBit:false, StripXattrs:false, KeepDirectoryNames:false, Rename:map[string]string(nil)}, PutOptions:copier.PutOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), DefaultDirOwner:(*idtools.IDPair)(nil), DefaultDirMode:(*os.FileMode)(nil), ChownDirs:(*idtools.IDPair)(nil), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(nil), ChmodFiles:(*os.FileMode)(nil), StripXattrs:false, IgnoreXattrErrors:false, IgnoreDevices:false, NoOverwriteDirNonDir:false, Rename:map[string]string(nil)}, MkdirOptions:copier.MkdirOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), ChownNew:(*idtools.IDPair)(nil), ChmodNew:(*os.FileMode)(nil)}}: copier: get: "/"("/"): error copying /extensions/okd/checkpolicy-3.1-3.fc33.x86_64.rpm: write bulk-writer: broken pipe
Mar 22 01:02:02 bootstrap01 release-image-download.sh[1502]: W0322 01:02:02.874992    1502 run.go:44] nice failed: running nice -- ionice -c 3 podman cp 2b77079c7c79fa0e04aa3c9e97bbe199b18bd38a14e6fa07cafb492310e296e0:/ /run/mco-machine-os-content/os-content-910500641 failed: Error: 2 errors occurred:
Mar 22 01:02:02 bootstrap01 release-image-download.sh[1502]:         * error copying to host: error during bulk transfer for copier.request{Request:"PUT", Root:"/", preservedRoot:"/run/mco-machine-os-content", rootPrefix:"/run/mco-machine-os-content", Directory:"/", preservedDirectory:"/run/mco-machine-os-content", Globs:[]string{}, preservedGlobs:[]string{}, StatOptions:copier.StatOptions{CheckForArchives:false, Excludes:[]string(nil)}, GetOptions:copier.GetOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), Excludes:[]string(nil), ExpandArchives:false, ChownDirs:(*idtools.IDPair)(nil), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(nil), ChmodFiles:(*os.FileMode)(nil), StripSetuidBit:false, StripSetgidBit:false, StripStickyBit:false, StripXattrs:false, KeepDirectoryNames:false, Rename:map[string]string(nil)}, PutOptions:copier.PutOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), DefaultDirOwner:(*idtools.IDPair)(nil), DefaultDirMode:(*os.FileMode)(nil), ChownDirs:(*idtools.IDPair)(0xc0004959a0), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(0xc0004959b0), ChmodFiles:(*os.FileMode)(nil), StripXattrs:false, IgnoreXattrErrors:false, IgnoreDevices:false, NoOverwriteDirNonDir:false, Rename:map[string]string(nil)}, MkdirOptions:copier.MkdirOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), ChownNew:(*idtools.IDPair)(nil), ChmodNew:(*os.FileMode)(nil)}}: copier: put: error setting extended attributes on "/extensions/okd/NetworkManager-ovs-1.26.6-1.fc33.x86_64.rpm": error setting value of extended attribute "user.Zif.MdChecksum[1616260662]" on "/extensions/okd/NetworkManager-ovs-1.26.6-1.fc33.x86_64.rpm": operation not supported
Mar 22 01:02:02 bootstrap01 release-image-download.sh[1502]:         * error copying from container: error during bulk transfer for copier.request{Request:"GET", Root:"/", preservedRoot:"/var/lib/containers/storage/overlay/b7917bb68f0ba5ed6223e796d035e31b1a520a9fa243cc72e657dbe26b34b02a/merged", rootPrefix:"/var/lib/containers/storage/overlay/b7917bb68f0ba5ed6223e796d035e31b1a520a9fa243cc72e657dbe26b34b02a/merged", Directory:"/", preservedDirectory:"/var/lib/containers/storage/overlay/b7917bb68f0ba5ed6223e796d035e31b1a520a9fa243cc72e657dbe26b34b02a/merged", Globs:[]string{"/"}, preservedGlobs:[]string{"/var/lib/containers/storage/overlay/b7917bb68f0ba5ed6223e796d035e31b1a520a9fa243cc72e657dbe26b34b02a/merged/."}, StatOptions:copier.StatOptions{CheckForArchives:false, Excludes:[]string(nil)}, GetOptions:copier.GetOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), Excludes:[]string(nil), ExpandArchives:false, ChownDirs:(*idtools.IDPair)(0xc0000438e0), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(0xc0000438f0), ChmodFiles:(*os.FileMode)(nil), StripSetuidBit:false, StripSetgidBit:false, StripStickyBit:false, StripXattrs:false, KeepDirectoryNames:false, Rename:map[string]string(nil)}, PutOptions:copier.PutOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), DefaultDirOwner:(*idtools.IDPair)(nil), DefaultDirMode:(*os.FileMode)(nil), ChownDirs:(*idtools.IDPair)(nil), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(nil), ChmodFiles:(*os.FileMode)(nil), StripXattrs:false, IgnoreXattrErrors:false, IgnoreDevices:false, NoOverwriteDirNonDir:false, Rename:map[string]string(nil)}, MkdirOptions:copier.MkdirOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), ChownNew:(*idtools.IDPair)(nil), ChmodNew:(*os.FileMode)(nil)}}: copier: get: "/"("/"): error copying /extensions/okd/checkpolicy-3.1-3.fc33.x86_64.rpm: write bulk-writer: broken pipe
Mar 22 01:02:02 bootstrap01 release-image-download.sh[1502]: : exit status 125; retrying...

and

-- Logs begin at Mon 2021-03-22 00:57:32 UTC. --
Mar 22 01:12:06 bootstrap01 systemd[1]: Starting Download the OpenShift Release Image...
Mar 22 01:12:06 bootstrap01 release-image-download.sh[777]: Pulling quay.io/openshift/okd@sha256:3396c6a8a98484969ad728ce7b006e854a8f37649f685913b9cea2f1c9dacd26...
Mar 22 01:12:06 bootstrap01 podman[782]: 2021-03-22 01:12:06.576493886 +0000 UTC m=+0.383721712 system refresh
Mar 22 01:12:11 bootstrap01 podman[782]: 2021-03-22 01:12:11.229576888 +0000 UTC m=+5.036804715 image pull  
Mar 22 01:12:11 bootstrap01 release-image-download.sh[782]: ad0fc691d54878e073d94ed672d086aaaa025cae78fec5029665fd168c2e76d9
Mar 22 01:12:11 bootstrap01 systemd[1]: Finished Download the OpenShift Release Image.
Mar 22 01:12:13 bootstrap01 systemd[1]: Dependency failed for Bootstrap a Kubernetes cluster.
Mar 22 01:12:13 bootstrap01 systemd[1]: bootkube.service: Job bootkube.service/start failed with result 'dependency'.

**Comment by vrutkovs** [comment] 2021-03-22 08:14
Dupe of #566 ?

**Comment by spranab** [comment] 2021-03-22 17:53
I am also facing the same issue. I am currently using fedora-coreos-33.20210217.3.0

**Comment by Mahmoud-Ibrahim** [comment] 2021-04-10 23:18
what version of fcos should i use ?

**Comment by Mahmoud-Ibrahim** [comment] 2021-04-10 23:44
https://github.com/openshift/okd/issues/580#issuecomment-812020314

**Closed** 2021-09-08 08:30 UTC
Labels: lifecycle/rotten
