### ISSUE TITLE
No version history at origin-release.ci.openshift.org

### ISSUE THREAD

**Issue by Reamer** [openshift/okd#883] opened 2021-09-20 07:09 UTC
**Describe the bug**
Version comparisons fail at https://origin-release.ci.openshift.org/releasestream/4-stable/release/4.7.0-0.okd-2021-09-19-013247.

**Error-Message**
```
Unable to show full changelog: could not generate a changelog: error: Could not load commits for https://github.com/vrutkovs/machine-config-operator: from commit beac376da79c5573f471f7012de8193423686582 does not exist
```

**Comment by JaimeMagiera** [comment] 2021-09-20 13:42
This is a duplicate of #873, which I've responded to. Please close this one.

**Closed** 2021-09-20 13:54 UTC
