### ISSUE TITLE
OKD 4.6 VMware IPI machine-controller failing due to missing tags

### ISSUE THREAD

**Issue by HaehnleinMar** [openshift/okd#420] opened 2020-12-09 18:05 UTC
**Describe the bug**
After updgrading OKD IPI on VMware from `4.5.0-0.okd-2020-10-15-235428` to `4.6.0-0.okd-2020-11-27-200126` the `machine-controller` container of `machine-api-controllers` is throwing errors that it cannot find Tags in vCenter when creating a new machine.

```
E1209 18:03:20.752571       1 reconciler.go:799] Failed to get tag: GET https://vcenter.example.com/rest/com/vmware/cis/tagging/tag/id:urn:vmomi:InventoryServiceTag:14adb89c-ad73-4e31-bc19-840891648b76:GLOBAL: 404 Not Found
E1209 18:03:20.765072       1 reconciler.go:262] Failed to reconcile region and zone labels: GET https://vcenter.example.com/rest/com/vmware/cis/tagging/tag/id:urn:vmomi:InventoryServiceTag:14adb89c-ad73-4e31-bc19-840891648b76:GLOBAL: 404 Not Found
```

**Version**
OKD 4.6.0-0.okd-2020-11-27-200126 on vSphere 6.7.0.42000 with IPI

**How reproducible**
Install OKD `4.5.0-0.okd-2020-10-15-235428` with IPI on VMware and upgrade to `4.6.0-0.okd-2020-11-27-200126`. Then try to create a new machine.

**Log bundle**
https://fil.email/iCF3FbaP (available until 2020-12-18)

**Comment by vrutkovs** [comment] 2020-12-10 16:49
Dupe of #364

**Closed by vrutkovs** 2020-12-10 16:49 UTC
Labels: platform/vsphere
