### ISSUE TITLE
Error provisioning logging stack in OKD 4.5

### ISSUE THREAD

**Issue by germancamacho** [openshift/okd#327] opened 2020-09-10 16:30 UTC
After configuring the redhat operators and provisionning the logging operator, the fluentD pods cannot start, the events section display the following error: 

"starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/containers/storage/overlay/dbc940e4392d9246161db6b3bb5c60a0e450cdeb6bdc70fe71220066febaae93/merged\\\" at \\\"/var/lib/containers/storage/overlay/dbc940e4392d9246161db6b3bb5c60a0e450cdeb6bdc70fe71220066febaae93/merged/usr/share/zoneinfo/UTC\\\" caused \\\"not a directory\\\"\""

Full error log:
[ErrorLog.txt](https://github.com/openshift/okd/files/5203206/ErrorLog.txt)

Fedora CoreOS 32.20200629.3.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/c/server/coreos/

OKD Version
Client Version: 4.5.0-0.okd-2020-08-12-020541
Server Version: 4.5.0-0.okd-2020-09-04-180756
Kubernetes Version: v1.18.3

Operators used:

Cluster Logging
4.5.0-202008261951.p0 provided by Red Hat, Inc
Elasticsearch Operator
4.5.0-202008310950.p0 provided by Red Hat, Inc

**Comment by vrutkovs** [comment] 2020-09-10 17:07
Dupe of #310

**Closed by vrutkovs** 2020-09-10 17:07 UTC
