### ISSUE TITLE
Can't install cluster due to networking issues

### ISSUE THREAD

**Issue by arcdigital** [openshift/okd#458] opened 2021-01-06 19:54 UTC
**Describe the bug**
The bootstrap node is unable to pull any images from Quay due to a networking issue. 

**Version**
4.6.0-0.okd-2020-12-12-135354 - UPI - DigitalOcean

**How reproducible**
100%

**Log bundle**
I don't have one at the moment, but I can re-create a cluster and grab one if needed.

I'm having issues getting a cluster running. After looking into it, it seems like a strange networking/ipv6 issue after the pivot. 

On first boot, before the droplet automatically restarts, networking works fine and I can ping google:
`rpm-ostree status`
```
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 33.20201214.3.1 (2021-01-05T00:05:03Z)
                    Commit: a64854cbcec13e1c3b3ccbfd3802e377e23c0c136d384c32736addf77e0e2a03
              GPGSignature: Valid signature by 963A2BEB02009608FE67EA4249FD77499570FF31
```

After the droplet restarts, I can't ping google anymore (it says "name or service not known"), dig times out...what's interesting is networking isn't completely broken as I can still SSH in. It pulled the okd image from quay initially before the restart, so it seems whatever okd applies to the machine is breaking networking.

`journalctl -b -f -u release-image.service -u bootkube.service`
```
Jan 06 06:39:22 bootstrap release-image-download.sh[95700]: Error: Error initializing source docker://quay.io/openshift/okd@sha256:01948f4c6bdd85cdd212eb40d96527a53d6382c4489d7da57522864178620a2c: error pinging docker registry quay.io: Get "https://quay.io/v2/": dial tcp: lookup quay.io on [::1]:53: read udp [::1]:48271->[::1]:53: read: connection refused
```

`rpm-ostree status`
```
State: idle
Deployments:
● pivot://quay.io/openshift/okd-content@sha256:95034a94e28949af41a53b9efb2fbb0651454a7c37bab002b0646e73c4721829
              CustomOrigin: Managed by machine-config-operator
                 Timestamp: 2020-12-12T05:05:37Z

  ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 33.20201214.3.1 (2021-01-05T00:05:03Z)
                    Commit: a64854cbcec13e1c3b3ccbfd3802e377e23c0c136d384c32736addf77e0e2a03
              GPGSignature: Valid signature by 963A2BEB02009608FE67EA4249FD77499570FF31
```

(also posted here: https://github.com/dustymabe/digitalocean-okd-install/issues/5)

**Comment by vrutkovs** [comment] 2021-01-06 20:22
Dupe of #440

**Closed by vrutkovs** 2021-01-06 20:22 UTC
