### ISSUE TITLE
Upgrade from     4.6.0-0.okd-2020-11-27-200126 to Update to 4.6.0-0.okd-2020-12-12-135354 fails with MCO

### ISSUE THREAD

**Issue by acsecengtesting** [openshift/okd#461] opened 2021-01-07 11:17 UTC
I am trying to upgrade from  4.6.0-0.okd-2020-11-27-200126 to Update to 4.6.0-0.okd-2020-12-12-135354
Note I had to force the upgrade due to a different issue (https://github.com/openshift/okd/issues/426)

The update progressed up to the point where the MachineConfig operator failed to progress (at this point one master and one worker node were in a scheduling disabled state). I tried re-enabling scheduling but to no avail. 

 Unable to apply 4.6.0-0.okd-2020-12-12-135354: timed out waiting for the condition during syncRequiredMachineConfigPools: pool master has not progressed to latest configuration: controller version mismatch for rendered-master-5a032982847665a0a7261dbf1ad27372 expected eb9778355a9020673e8ce9aee092cb98d80cde5e has 5a9e6b4eedaf72ecc2534355173843e011f19765: 0 (ready 0) out of 3 nodes are updating to latest configuration rendered-master-be834a6a05b0b65e63a1725d4dc447c2, retrying

From the MCS on the node currently in that state
E0107 11:15:39.454062    7146 writer.go:135] Marking Degraded due to: unexpected on-disk state validating against rendered-master-be834a6a05b0b65e63a1725d4dc447c2: expected target osImageURL "quay.io/openshift/okd-content@sha256:95034a94e28949af41a53b9efb2fbb0651454a7c37bab002b0646e73c4721829", have "quay.io/openshift/okd-content@sha256:880f0e1cfb4a5c8c22dd9cbb54c2294bcbbcfef30b126d5c04d3160f84438c6a"

This is a bare metal (Vms) install. I tried re-building the cluster from scratch but ended up in the same situation. 

I have tried marking the nodes as schedulable and restarting them and that has seen 2 of the 3 now progress to the new version 

[root@centosutils log]# oc get nodes --output=wide
NAME                   STATUS   ROLES    AGE   VERSION                     INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION           CONTAINER-RUNTIME
okd4-compute-1         Ready    worker   10d   v1.19.2+7070803-1008        192.168.2.204   <none>        Fedora CoreOS 33.20201209.10.0   5.9.12-200.fc33.x86_64   cri-o://1.19.0
okd4-compute-2         Ready    worker   10d   v1.19.2+7070803-1008        192.168.2.205   <none>        Fedora CoreOS 33.20201209.10.0   5.9.12-200.fc33.x86_64   cri-o://1.19.0
okd4-compute-3         Ready    worker   10d   v1.19.2+7070803-1008        192.168.2.206   <none>        Fedora CoreOS 33.20201209.10.0   5.9.12-200.fc33.x86_64   cri-o://1.19.0
okd4-control-plane-1   Ready    master   10d   v1.19.2+7070803-1008        192.168.2.201   <none>        Fedora CoreOS 33.20201209.10.0   5.9.12-200.fc33.x86_64   cri-o://1.19.0
okd4-control-plane-2   Ready    master   10d   v1.19.2+7070803-1008        192.168.2.202   <none>        Fedora CoreOS 33.20201209.10.0   5.9.12-200.fc33.x86_64   cri-o://1.19.0
okd4-control-plane-3   Ready    master   10d   v1.19.0-rc.2+9f84db3-1075   192.168.2.203   <none>        Fedora CoreOS 33.20201124.10.1   5.9.9-200.fc33.x86_64    cri-o://1.19.0

Must Gather here from before I took any action:   (too large to attach directly)
https://easyupload.io/7h3yvn

**Comment by abaxo** [comment] 2021-01-19 10:42
Hey @acsecengtesting , 

I ran into the same issue and found that it was because I had previously been building my cluster from images from the nightly registry, but tried to do the latest build from the quay.io images. (I'm not 100% sure this is the real cause).

 You can go into the 'MachineConfig' object (rendered-master-5a032982847665a0a7261dbf1ad27372) and update the osImageURL paramater to what it expected (quay.io/openshift/okd-content@sha256:95034a94e28949af41a53b9efb2fbb0651454a7c37bab002b0646e73c4721829)  and it will progress.

Hope this helps.

**Comment by elgalesmana** [comment] 2021-01-20 19:25
@acsecengtesting same issue

```
Unable to apply 4.6.0-0.okd-2021-01-17-185703: timed out waiting for the condition during syncRequiredMachineConfigPools: pool master has not progressed to latest configuration: controller version mismatch for rendered-master-15792a20916ff8d063e5314deb48dc32 expected a72f402cce4a683d4f9ba3956b5dcd297b458a54 has eb9778355a9020673e8ce9aee092cb98d80cde5e: pool is degraded because nodes fail with "1 nodes are reporting degraded status on sync": "Node ip-10-0-188-208.ap-southeast-1.compute.internal is reporting: \"failed to update OS to quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c : with stdout output: : error running rpm-ostree rebase --experimental /run/mco-machine-os-content/os-content-010492184/srv/repo:14eea5296ffb7a28aff80a70c03434e8034422b0d11b47475b29530b93ab4682 --custom-origin-url pivot://quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c --custom-origin-description Managed by machine-config-operator: 0 metadata, 0 content objects imported; 0 bytes content written\\nChecking out tree 14eea52...done\\nEnabled rpm-md repositories: coreos-extensions updates-archive\\nrpm-md repo 'coreos-extensions' (cached); generated: 2021-01-17T11:40:41Z\\nrpm-md repo 'updates-archive' (cached); generated: 2021-01-19T03:51:30Z\\nImporting rpm-md...done\\nResolving dependencies...done\\nChecking out packages...done\\n: exit status 1\"", retrying
```

disable repo and change the osimageURL still not working.

**Comment by vrutkovs** [comment] 2021-01-22 12:06
Dupe of #471

**Closed by vrutkovs** 2021-01-22 12:06 UTC
