### ISSUE TITLE
Current OKD project differences compared to OpenShift 4.3

### ISSUE THREAD

**Issue by jxadro** [openshift/okd#85] opened 2020-02-21 12:10 UTC
Hi.

Is there any documentation about differences between current preview OKD and OCP 4.3?

In this issue https://github.com/openshift/okd/issues/26 I can read:

"OKD4 is currently in Preview mode since CI and release controller jobs are not yet fully setup - and installer doesn't support as many platforms as OCP4."

Any detailed list of differences or projects / features not covered yet in OKD? Thank you.

**Comment by vrutkovs** [comment] 2020-02-21 12:22
That looks like a dupe of #43, see https://github.com/openshift/okd/issues/43#issuecomment-581068658

**Comment by jxadro** [comment] 2020-02-21 12:37
Thank you, that one contains only info about installers. I thought there was also difference about other projects like for example Tekton and Istio.

**Comment by vrutkovs** [comment] 2020-02-21 12:45
That depends on the pull-secret used. In OKD we default Operator Hub settings to "community operators only", but if you have a valid pull secret this can be reversed, enabling you to install operators from registry.redhat.io

**Closed** 2020-03-09 10:18 UTC

**Comment by kai-uwe-rommel** [comment] 2020-07-09 07:48
IMO, very important is also, that documentation is updated properly. Including such things like the enabling of the other operator hub sources. I had do search around a lot to find out about this ...
