### ISSUE TITLE
Unable to apply 4.4.0-0.okd-2020-05-23-055148-beta5: the image may not be safe to use

### ISSUE THREAD

**Issue by sapkra** [openshift/okd#192] opened 2020-05-25 20:15 UTC
**Describe the bug**
I've tried to update from beta 4 to beta 5 using the web console but it is failing with the following message:

![image](https://user-images.githubusercontent.com/8087568/82840914-8f245600-9ed4-11ea-9c0d-70cfae7416e2.png)
![image](https://user-images.githubusercontent.com/8087568/82841019-ede9cf80-9ed4-11ea-91b3-d213f508c405.png)

**Version**
4.4.0-0.okd-2020-04-21-163702-beta4

**Comment by vrutkovs** [comment] 2020-05-25 20:29
Dupe of #138

**Closed by vrutkovs** 2020-05-25 20:29 UTC

**Comment by sapkra** [comment] 2020-05-25 20:34
So the beta's are also not signed? I thought that the issue is just for nightlies.

**Comment by cgruver** [comment] 2020-05-25 23:54
Correct.  I've updated the issue name to avoid confusion.

**Comment by vrutkovs** [comment] 2020-05-26 07:33
Betas are promoted nightlies

**Comment by chriskuipers** [comment] 2020-05-26 11:27
For anyone running into this error from triggering the upgrade from the OKD web interface, I posted a workaround in #138
