### ISSUE TITLE
openshift-installer dependencies not listed

### ISSUE THREAD

**Issue by AndreasDavour** [openshift/okd#701] opened 2021-06-18 08:21 UTC
**Describe the bug**
I decide to spin up a cluster and download the installer, intending to spin it up in a public cloud from my Ubuntu desktop.

When I run the installer, which is downloaded from the Releases as a one file binary, I get this output:
$ openshift-install 
openshift-install: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_4.1.0' not found (required by openshift-install)
openshift-install: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_4.4.0' not found (required by openshift-install)
openshift-install: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_4.5.0' not found (required by openshift-install)

**Version**
openshift-install-linux-4.7.0-0.okd-2021-06-13-090745.tar.gz
$ uname -a
Linux VDL900001 5.4.0-73-generic #82~18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

s$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**How reproducible**
Just download the installer and try to run it.

**Log bundle**
N/A

**Comment by vrutkovs** [comment] 2021-06-18 08:55
Dupe of #535

**Closed by vrutkovs** 2021-06-18 08:55 UTC
