### ISSUE TITLE
OKD 4.6 cluster is up, but the console is still in a unknown state, also the openshift-apiserver and authentication are in a False state

### ISSUE THREAD

**Issue by garethhk** [openshift/okd#481] opened 2021-01-25 04:24 UTC
**Describe the bug**
The problem is the cluster is up, but the console is still in a unknown state, also the openshift-apiserver and authentication are in a False state, I have followed https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee to install OKD 4.6.
[root@okd4-services ~]# openshift-install --dir=install_dir/ wait-for bootstrap-complete --log-level=info
INFO Waiting up to 20m0s for the Kubernetes API at https://api.lab.okd.local:6443... 
INFO API v1.19.2-1019+3b012051f912a6-dirty up     
INFO Waiting up to 30m0s for bootstrapping to complete... 
INFO It is now safe to remove the bootstrap resources 
INFO Time elapsed: 19m37s 

[root@okd4-services ~]# oc get co | grep -v "True.*False.*False"; oc get no
NAME                                       VERSION                         AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                                                             False       False         True       2d17h
console                                    4.6.0-0.okd-2021-01-17-185703   Unknown     True          True       2d11h
image-registry                             4.6.0-0.okd-2021-01-17-185703   True        False         True       2d17h
monitoring                                                                 False       True          True       2d17h
openshift-apiserver                        4.6.0-0.okd-2021-01-17-185703   False       False         False      2d17h
openshift-samples                                                          False       False         False      47h
operator-lifecycle-manager-packageserver   4.6.0-0.okd-2021-01-17-185703   False       True          False      47h
NAME                   STATUS   ROLES    AGE     VERSION
okd4-compute-1         Ready    worker   7m28s   v1.19.2+3b01205-1019
okd4-compute-2         Ready    worker   7m41s   v1.19.2+3b01205-1019
okd4-control-plane-1   Ready    master   2d17h   v1.19.2+3b01205-1019
okd4-control-plane-2   Ready    master   2d17h   v1.19.2+3b01205-1019
okd4-control-plane-3   Ready    master   2d17h   v1.19.2+3b01205-1019

**Version**
UPI on baremetal
CoreOS : fedora-coreos-33.20210104.3.0
OKD version: 4.6.0-0.okd-2021-01-17-185703

**How reproducible**
reproducible - 100%

install-config.yaml, named.conf.local, named.conf, db.okd.local, db.192.168.1, haproxy.cfg from: (i didnt make any change except the ssh-key)
git clone https://github.com/cragr/okd4_files.git 
following https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee

===install-config.yaml===
apiVersion: v1
baseDomain: okd.local
metadata:
  name: lab

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"fake":{"auth": "bar"}}}' 
sshKey: 'ssh-rsa'

**Log bundle**
https://drive.google.com/file/d/1wbWSyAKd5SJby16BWllbmISKCpm6SwwF/view?usp=sharing
[root@okd4-services ~]# oc adm must-gather
[must-gather      ] OUT imagestreams.image.openshift.io "must-gather" not found
[must-gather      ] OUT
[must-gather      ] OUT Using must-gather plugin-in image: quay.io/openshift/origin-must-gather:latest
[must-gather      ] OUT namespace/openshift-must-gather-l7csj created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-xclf4 created
[must-gather      ] OUT pod for plug-in image quay.io/openshift/origin-must-gather:latest created
[must-gather-hdqbl] POD Error from server (ServiceUnavailable): the server is currently unable to handle the request (get routes.route.openshift.io)
[must-gather-hdqbl] POD Error from server (ServiceUnavailable): the server is currently unable to handle the request (get imagestreams.image.openshift.io)
[must-gather-hdqbl] POD Error from server (ServiceUnavailable): the server is currently unable to handle the request (get builds.build.openshift.io)
[must-gather-hdqbl] POD Error from server (ServiceUnavailable): the server is currently unable to handle the request (get deploymentconfigs.apps.openshift.io)
[must-gather-hdqbl] POD Error from server (ServiceUnavailable): the server is currently unable to handle the request (get builds.build.openshift.io)
[must-gather-hdqbl] POD Error from server (ServiceUnavailable): the server is currently unable to handle the request (get buildconfigs.build.openshift.io)
[must-gather-hdqbl] POD Error from server (ServiceUnavailable): the server is currently unable to handle the request (get imagestreams.image.openshift.io)
[must-gather-hdqbl] POD Gathering data for ns/openshift-cluster-version...
[must-gather-hdqbl] POD Gathering data for ns/default...
[must-gather-hdqbl] POD Gathering data for ns/openshift...
[must-gather-hdqbl] POD Gathering data for ns/kube-system...
[must-gather-hdqbl] POD Gathering data for ns/openshift-etcd...
[must-gather-hdqbl] POD Gathering data for ns/openshift-kni-infra...
[must-gather-hdqbl] POD Wrote inspect data to must-gather.
[must-gather-hdqbl] POD error: errors ocurred while gathering data:
[must-gather-hdqbl] POD     the server doesn't have a resource type "deploymentconfigs"
[must-gather-hdqbl] POD Gathering data for ns/openshift-config...
[must-gather-hdqbl] POD Gathering data for ns/openshift-config-managed...
[must-gather-hdqbl] POD Gathering data for ns/openshift-authentication...
[must-gather-hdqbl] POD Gathering data for ns/openshift-authentication-operator...
[must-gather-hdqbl] POD Gathering data for ns/openshift-ingress...
[must-gather-hdqbl] POD Gathering data for ns/openshift-oauth-apiserver...
[must-gather-hdqbl] POD Gathering data for ns/openshift-cloud-credential-operator...
[must-gather-hdqbl] POD Gathering data for ns/openshift-machine-api...
[must-gather-hdqbl] OUT gather logs unavailable: http2: server sent GOAWAY and closed the connection; LastStreamID=21, ErrCode=NO_ERROR, debug=""
[must-gather-hdqbl] OUT waiting for gather to complete

[must-gather-hdqbl] OUT gather never finished: timed out waiting for the condition
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-xclf4 deleted
[must-gather      ] OUT namespace/openshift-must-gather-l7csj deleted
error: gather never finished for pod must-gather-hdqbl: timed out waiting for the condition

**Comment by vrutkovs** [comment] 2021-01-25 08:22
Does `oc adm must-gather` consistently throwing this error?

**Comment by garethhk** [comment] 2021-01-26 03:56
yes, do you think it is because the openshift-apiserver is not yet start?

**Comment by vrutkovs** [comment] 2021-01-26 06:39
oh wait,

>networkType: OpenShiftSDN

Dupe of #430

**Closed by vrutkovs** 2021-01-26 06:39 UTC
