### ISSUE TITLE
4.6.0-0.okd-2021-02-14-205305: UPI - Fresh install not possible (console fails to start); OVNKubernetes

### ISSUE THREAD

**Issue by borbul2007** [openshift/okd#513] opened 2021-02-17 11:09 UTC
**Describe the bug**

Cluster deployment cannot be completed because the console does not start:

![image](https://user-images.githubusercontent.com/78852894/108194104-44fc9800-7127-11eb-8138-41445262e491.png)

**Version**

UPI - VMware ESXi, 6.7.0, 17167734
OKD - 4.6.0-0.okd-2021-02-14-205305
FCOS - 33.20210117.3.2

**How reproducible**

100% Provision a cluster on UPI using versions above

**Log bundle**

https://cloud.mail.ru/public/YFoT/BZiBTJ8fh

![image](https://user-images.githubusercontent.com/78852894/108194202-62316680-7127-11eb-90d4-0c716c1c5271.png)

![image](https://user-images.githubusercontent.com/78852894/108194381-9e64c700-7127-11eb-806f-a602ddb10348.png)

**Comment by vrutkovs** [comment] 2021-02-17 11:24
Dupe of #508

**Closed by vrutkovs** 2021-02-17 11:24 UTC
