### ISSUE TITLE
Bootstrap process stuck with error: "99_openshift-machineconfig_99-master-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-master-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"

### ISSUE THREAD

**Issue by mkelnermishal** [openshift/okd#81] opened 2020-02-11 12:54 UTC
openshift-install version
openshift-install v4.3.0
built from commit 2055609f95b19322ee6cfdd0bea73399297c4a3e
release image quay.io/openshift-release-dev/ocp-release@sha256:3a516480dfd68e0f87f702b4d7bdd6f6a0acfdac5cd2e9767b838ceede34d70d

UPI vsphere.
Bootstrap process hangs, printing the above error endlessly.
We need a workaround or a fix as soon as possible.

I ran must-gather, it hands, prints only:
oc adm must-gather
[must-gather      ] OUT the server could not find the requested resource (get imagestreams.image.openshift.io must-gather)
[must-gather      ] OUT
[must-gather      ] OUT Using must-gather plugin-in image: quay.io/openshift/origin-must-gather:latest
[must-gather      ] OUT namespace/openshift-must-gather-lphq9 created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-prnwv created
[must-gather      ] OUT pod for plug-in image quay.io/openshift/origin-must-gather:latest created

**Comment by vrutkovs** [comment] 2020-02-11 13:00
>openshift-install v4.3.0

Oh, its probably a dupe of https://github.com/openshift/okd/issues/42

Could you try 4.4 payloads?

**Comment by mkelnermishal** [comment] 2020-02-11 15:27
Hey, I have no idea how to use 4.4 payload. can you please describe ? thanks

**Comment by vrutkovs** [comment] 2020-02-11 15:31
See https://github.com/openshift/okd#getting-started

**Comment by sgreene570** [comment] 2020-02-13 19:02
@vrutkovs I am seeing this on 4.4 payload baremetal UPI. The following error is displayed over and over. Might not be related to #42. 
```
Feb 13 18:58:35 okd4-bootstrap bootkube.sh[659]: [#501] failed to create some manifests:
Feb 13 18:58:35 okd4-bootstrap bootkube.sh[659]: "99_openshift-machineconfig_99-master-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-master-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"
Feb 13 18:58:35 okd4-bootstrap bootkube.sh[659]: "99_openshift-machineconfig_99-worker-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-worker-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"
```
Must gather doesn't have the error as far as I can tell (since its coming from `bootkube.sh`?
Didn't see anything major in must gather yet.
Link to must gather (rh only):
https://drive.google.com/file/d/1cgPu3bQOTfTMuxujo7Lrn83E9Tfh9W5U/view?usp=sharing

**Comment by vrutkovs** [comment] 2020-02-13 20:00
"no matches for kind" is expected (for some time) - it just means masters didn't start `machine-config` operator yet and the type has not been registered

**Comment by CountPickering** [comment] 2020-02-29 04:47
Having the same issue with 4.4.0-0.okd-2020-02-28-211838

**Comment by cragr** [comment] 2020-03-02 18:34
> "no matches for kind" is expected (for some time) - it just means masters didn't start `machine-config` operator yet and the type has not been registered

So this isn't really an issue, it will clear up on its own?

**Comment by vrutkovs** [comment] 2020-03-02 18:44
Yes, it would go away as soon as CRD definition would be created (by `machine-config` operator).

I see there are various issues with the same symptom mentioned here, so lets split these in separate issues with `must-gather` archives instead

**Closed by vrutkovs** 2020-03-02 18:44 UTC
Labels: triage/needs-information

**Comment by majorinche** [comment] 2020-06-12 03:13
try using must-gather,but seems cannot schedule

[root@localhost ~]# oc --kubeconfig=/opt/openshift/auth/kubeconfig-loopback adm must-gather --image=quay.io/openshift/okd-content@sha256:a273f5ac7f1ad8f7ffab45205ac36c8dff92d9107ef3ae429eeb135fa8057b8b
[must-gather      ] OUT Using must-gather plugin-in image: quay.io/openshift/okd-content@sha256:a273f5ac7f1ad8f7ffab45205ac36c8dff92d9107ef3ae429eeb135fa8057b8b
[must-gather      ] OUT namespace/openshift-must-gather-d64dg created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-7wc5x created
[must-gather      ] OUT pod for plug-in image quay.io/openshift/okd-content@sha256:a273f5ac7f1ad8f7ffab45205ac36c8dff92d9107ef3ae429eeb135fa8057b8b created


[root@localhost ~]# oc --kubeconfig=/opt/openshift/auth/kubeconfig-loopback get events -n openshift-must-gather-scpm5
LAST SEEN   TYPE      REASON             OBJECT                  MESSAGE
<unknown>   Warning   FailedScheduling   pod/must-gather-fr2nq   no nodes available to schedule pods
<unknown>   Warning   FailedScheduling   pod/must-gather-fr2nq   no nodes available to schedule pods
<unknown>   Warning   FailedScheduling   pod/must-gather-fr2nq   no nodes available to schedule pods
