### ISSUE TITLE
Bootstrap stuck on clean baremetal installation with version 4.7.0-0.okd-2021-04-11-124433

### ISSUE THREAD

**Issue by myg0v** [openshift/okd#600] opened 2021-04-17 18:25 UTC
**Describe the bug**
After trying to install a new cluster with version 4.7.0-0.okd-2021-04-11-124433, the bootstrap machine will not start completely.

The bootstrap service show the following log:
```
[core@k8s-bootstrap-1-01 ~]$ journalctl -b -f -u release-image.service -u bootkube.service
-- Logs begin at Sat 2021-04-17 17:49:15 UTC. --
Apr 17 17:51:36 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]:         * error copying from container: error during bulk transfer for copier.request{Request:"GET", Root:"/", preservedRoot:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", rootPrefix:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", Directory:"/", preservedDirectory:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", Globs:[]string{"/"}, preservedGlobs:[]string{"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged/."}, StatOptions:copier.StatOptions{CheckForArchives:false, Excludes:[]string(nil)}, GetOptions:copier.GetOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), Excludes:[]string{"dev", "proc", "sys"}, ExpandArchives:false, ChownDirs:(*idtools.IDPair)(0xc000043550), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(0xc000043560), ChmodFiles:(*os.FileMode)(nil), StripSetuidBit:false, StripSetgidBit:false, StripStickyBit:false, StripXattrs:false, KeepDirectoryNames:false, Rename:map[string]string(nil), NoDerefSymlinks:false, IgnoreUnreadable:false}, PutOptions:copier.PutOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), DefaultDirOwner:(*idtools.IDPair)(nil), DefaultDirMode:(*os.FileMode)(nil), ChownDirs:(*idtools.IDPair)(nil), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(nil), ChmodFiles:(*os.FileMode)(nil), StripXattrs:false, IgnoreXattrErrors:false, IgnoreDevices:false, NoOverwriteDirNonDir:false, Rename:map[string]string(nil)}, MkdirOptions:copier.MkdirOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), ChownNew:(*idtools.IDPair)(nil), ChmodNew:(*os.FileMode)(nil)}}: copier: get: "/"("/"): error copying /extensions/okd/perl-PathTools-3.78-458.fc33.x86_64.rpm: write bulk-writer: broken pipe
Apr 17 17:51:36 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: : exit status 125; retrying...
Apr 17 17:52:16 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: I0417 17:52:16.336699    1821 run.go:18] Running: nice -- ionice -c 3 podman cp baf71618a5514ab11e21e9042c06e1f3a3bee4749b57340259a3b14776ee16c9:/ /run/mco-machine-os-content/os-content-983218098
Apr 17 17:52:17 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: Error: 2 errors occurred:
Apr 17 17:52:17 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]:         * error copying to host: error during bulk transfer for copier.request{Request:"PUT", Root:"/", preservedRoot:"/run/mco-machine-os-content/os-content-983218098", rootPrefix:"/run/mco-machine-os-content/os-content-983218098", Directory:"/", preservedDirectory:"/run/mco-machine-os-content/os-content-983218098", Globs:[]string{}, preservedGlobs:[]string{}, StatOptions:copier.StatOptions{CheckForArchives:false, Excludes:[]string(nil)}, GetOptions:copier.GetOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), Excludes:[]string(nil), ExpandArchives:false, ChownDirs:(*idtools.IDPair)(nil), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(nil), ChmodFiles:(*os.FileMode)(nil), StripSetuidBit:false, StripSetgidBit:false, StripStickyBit:false, StripXattrs:false, KeepDirectoryNames:false, Rename:map[string]string(nil), NoDerefSymlinks:false, IgnoreUnreadable:false}, PutOptions:copier.PutOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), DefaultDirOwner:(*idtools.IDPair)(nil), DefaultDirMode:(*os.FileMode)(nil), ChownDirs:(*idtools.IDPair)(0xc0005a8770), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(0xc0005a8780), ChmodFiles:(*os.FileMode)(nil), StripXattrs:false, IgnoreXattrErrors:false, IgnoreDevices:true, NoOverwriteDirNonDir:false, Rename:map[string]string(nil)}, MkdirOptions:copier.MkdirOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), ChownNew:(*idtools.IDPair)(nil), ChmodNew:(*os.FileMode)(nil)}}: copier: put: error setting extended attributes on "/extensions/okd/perl-Errno-1.30-468.fc33_1.30-469.fc33.x86_64.drpm": error setting value of extended attribute "user.Zif.MdChecksum[1617881158]" on "/extensions/okd/perl-Errno-1.30-468.fc33_1.30-469.fc33.x86_64.drpm": operation not supported
Apr 17 17:52:17 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]:         * error copying from container: error during bulk transfer for copier.request{Request:"GET", Root:"/", preservedRoot:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", rootPrefix:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", Directory:"/", preservedDirectory:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", Globs:[]string{"/"}, preservedGlobs:[]string{"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged/."}, StatOptions:copier.StatOptions{CheckForArchives:false, Excludes:[]string(nil)}, GetOptions:copier.GetOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), Excludes:[]string{"dev", "proc", "sys"}, ExpandArchives:false, ChownDirs:(*idtools.IDPair)(0xc0005015c0), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(0xc0005015d0), ChmodFiles:(*os.FileMode)(nil), StripSetuidBit:false, StripSetgidBit:false, StripStickyBit:false, StripXattrs:false, KeepDirectoryNames:false, Rename:map[string]string(nil), NoDerefSymlinks:false, IgnoreUnreadable:false}, PutOptions:copier.PutOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), DefaultDirOwner:(*idtools.IDPair)(nil), DefaultDirMode:(*os.FileMode)(nil), ChownDirs:(*idtools.IDPair)(nil), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(nil), ChmodFiles:(*os.FileMode)(nil), StripXattrs:false, IgnoreXattrErrors:false, IgnoreDevices:false, NoOverwriteDirNonDir:false, Rename:map[string]string(nil)}, MkdirOptions:copier.MkdirOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), ChownNew:(*idtools.IDPair)(nil), ChmodNew:(*os.FileMode)(nil)}}: copier: get: "/"("/"): error copying /extensions/okd/perl-PathTools-3.78-458.fc33.x86_64.rpm: write bulk-writer: broken pipe
Apr 17 17:52:17 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: W0417 17:52:17.367410    1821 run.go:44] nice failed: running nice -- ionice -c 3 podman cp baf71618a5514ab11e21e9042c06e1f3a3bee4749b57340259a3b14776ee16c9:/ /run/mco-machine-os-content/os-content-983218098 failed: Error: 2 errors occurred:
Apr 17 17:52:17 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]:         * error copying to host: error during bulk transfer for copier.request{Request:"PUT", Root:"/", preservedRoot:"/run/mco-machine-os-content/os-content-983218098", rootPrefix:"/run/mco-machine-os-content/os-content-983218098", Directory:"/", preservedDirectory:"/run/mco-machine-os-content/os-content-983218098", Globs:[]string{}, preservedGlobs:[]string{}, StatOptions:copier.StatOptions{CheckForArchives:false, Excludes:[]string(nil)}, GetOptions:copier.GetOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), Excludes:[]string(nil), ExpandArchives:false, ChownDirs:(*idtools.IDPair)(nil), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(nil), ChmodFiles:(*os.FileMode)(nil), StripSetuidBit:false, StripSetgidBit:false, StripStickyBit:false, StripXattrs:false, KeepDirectoryNames:false, Rename:map[string]string(nil), NoDerefSymlinks:false, IgnoreUnreadable:false}, PutOptions:copier.PutOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), DefaultDirOwner:(*idtools.IDPair)(nil), DefaultDirMode:(*os.FileMode)(nil), ChownDirs:(*idtools.IDPair)(0xc0005a8770), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(0xc0005a8780), ChmodFiles:(*os.FileMode)(nil), StripXattrs:false, IgnoreXattrErrors:false, IgnoreDevices:true, NoOverwriteDirNonDir:false, Rename:map[string]string(nil)}, MkdirOptions:copier.MkdirOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), ChownNew:(*idtools.IDPair)(nil), ChmodNew:(*os.FileMode)(nil)}}: copier: put: error setting extended attributes on "/extensions/okd/perl-Errno-1.30-468.fc33_1.30-469.fc33.x86_64.drpm": error setting value of extended attribute "user.Zif.MdChecksum[1617881158]" on "/extensions/okd/perl-Errno-1.30-468.fc33_1.30-469.fc33.x86_64.drpm": operation not supported
Apr 17 17:52:17 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]:         * error copying from container: error during bulk transfer for copier.request{Request:"GET", Root:"/", preservedRoot:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", rootPrefix:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", Directory:"/", preservedDirectory:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", Globs:[]string{"/"}, preservedGlobs:[]string{"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged/."}, StatOptions:copier.StatOptions{CheckForArchives:false, Excludes:[]string(nil)}, GetOptions:copier.GetOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), Excludes:[]string{"dev", "proc", "sys"}, ExpandArchives:false, ChownDirs:(*idtools.IDPair)(0xc0005015c0), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(0xc0005015d0), ChmodFiles:(*os.FileMode)(nil), StripSetuidBit:false, StripSetgidBit:false, StripStickyBit:false, StripXattrs:false, KeepDirectoryNames:false, Rename:map[string]string(nil), NoDerefSymlinks:false, IgnoreUnreadable:false}, PutOptions:copier.PutOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), DefaultDirOwner:(*idtools.IDPair)(nil), DefaultDirMode:(*os.FileMode)(nil), ChownDirs:(*idtools.IDPair)(nil), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(nil), ChmodFiles:(*os.FileMode)(nil), StripXattrs:false, IgnoreXattrErrors:false, IgnoreDevices:false, NoOverwriteDirNonDir:false, Rename:map[string]string(nil)}, MkdirOptions:copier.MkdirOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), ChownNew:(*idtools.IDPair)(nil), ChmodNew:(*os.FileMode)(nil)}}: copier: get: "/"("/"): error copying /extensions/okd/perl-PathTools-3.78-458.fc33.x86_64.rpm: write bulk-writer: broken pipe
Apr 17 17:52:17 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: : exit status 125; retrying...
Apr 17 17:53:37 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: I0417 17:53:37.368463    1821 run.go:18] Running: nice -- ionice -c 3 podman cp baf71618a5514ab11e21e9042c06e1f3a3bee4749b57340259a3b14776ee16c9:/ /run/mco-machine-os-content/os-content-983218098
Apr 17 17:53:38 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: Error: 2 errors occurred:
Apr 17 17:53:38 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]:         * error copying to host: error during bulk transfer for copier.request{Request:"PUT", Root:"/", preservedRoot:"/run/mco-machine-os-content/os-content-983218098", rootPrefix:"/run/mco-machine-os-content/os-content-983218098", Directory:"/", preservedDirectory:"/run/mco-machine-os-content/os-content-983218098", Globs:[]string{}, preservedGlobs:[]string{}, StatOptions:copier.StatOptions{CheckForArchives:false, Excludes:[]string(nil)}, GetOptions:copier.GetOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), Excludes:[]string(nil), ExpandArchives:false, ChownDirs:(*idtools.IDPair)(nil), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(nil), ChmodFiles:(*os.FileMode)(nil), StripSetuidBit:false, StripSetgidBit:false, StripStickyBit:false, StripXattrs:false, KeepDirectoryNames:false, Rename:map[string]string(nil), NoDerefSymlinks:false, IgnoreUnreadable:false}, PutOptions:copier.PutOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), DefaultDirOwner:(*idtools.IDPair)(nil), DefaultDirMode:(*os.FileMode)(nil), ChownDirs:(*idtools.IDPair)(0xc0000f58e0), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(0xc0000f58f0), ChmodFiles:(*os.FileMode)(nil), StripXattrs:false, IgnoreXattrErrors:false, IgnoreDevices:true, NoOverwriteDirNonDir:false, Rename:map[string]string(nil)}, MkdirOptions:copier.MkdirOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), ChownNew:(*idtools.IDPair)(nil), ChmodNew:(*os.FileMode)(nil)}}: copier: put: error setting extended attributes on "/extensions/okd/perl-Errno-1.30-468.fc33_1.30-469.fc33.x86_64.drpm": error setting value of extended attribute "user.Zif.MdChecksum[1617881158]" on "/extensions/okd/perl-Errno-1.30-468.fc33_1.30-469.fc33.x86_64.drpm": operation not supported
Apr 17 17:53:38 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]:         * error copying from container: error during bulk transfer for copier.request{Request:"GET", Root:"/", preservedRoot:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", rootPrefix:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", Directory:"/", preservedDirectory:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", Globs:[]string{"/"}, preservedGlobs:[]string{"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged/."}, StatOptions:copier.StatOptions{CheckForArchives:false, Excludes:[]string(nil)}, GetOptions:copier.GetOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), Excludes:[]string{"dev", "proc", "sys"}, ExpandArchives:false, ChownDirs:(*idtools.IDPair)(0xc000179a40), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(0xc000179a50), ChmodFiles:(*os.FileMode)(nil), StripSetuidBit:false, StripSetgidBit:false, StripStickyBit:false, StripXattrs:false, KeepDirectoryNames:false, Rename:map[string]string(nil), NoDerefSymlinks:false, IgnoreUnreadable:false}, PutOptions:copier.PutOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), DefaultDirOwner:(*idtools.IDPair)(nil), DefaultDirMode:(*os.FileMode)(nil), ChownDirs:(*idtools.IDPair)(nil), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(nil), ChmodFiles:(*os.FileMode)(nil), StripXattrs:false, IgnoreXattrErrors:false, IgnoreDevices:false, NoOverwriteDirNonDir:false, Rename:map[string]string(nil)}, MkdirOptions:copier.MkdirOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), ChownNew:(*idtools.IDPair)(nil), ChmodNew:(*os.FileMode)(nil)}}: copier: get: "/"("/"): error copying /extensions/okd/perl-PathTools-3.78-458.fc33.x86_64.rpm: write bulk-writer: broken pipe
Apr 17 17:53:38 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: W0417 17:53:38.086555    1821 run.go:44] nice failed: running nice -- ionice -c 3 podman cp baf71618a5514ab11e21e9042c06e1f3a3bee4749b57340259a3b14776ee16c9:/ /run/mco-machine-os-content/os-content-983218098 failed: Error: 2 errors occurred:
Apr 17 17:53:38 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]:         * error copying to host: error during bulk transfer for copier.request{Request:"PUT", Root:"/", preservedRoot:"/run/mco-machine-os-content/os-content-983218098", rootPrefix:"/run/mco-machine-os-content/os-content-983218098", Directory:"/", preservedDirectory:"/run/mco-machine-os-content/os-content-983218098", Globs:[]string{}, preservedGlobs:[]string{}, StatOptions:copier.StatOptions{CheckForArchives:false, Excludes:[]string(nil)}, GetOptions:copier.GetOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), Excludes:[]string(nil), ExpandArchives:false, ChownDirs:(*idtools.IDPair)(nil), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(nil), ChmodFiles:(*os.FileMode)(nil), StripSetuidBit:false, StripSetgidBit:false, StripStickyBit:false, StripXattrs:false, KeepDirectoryNames:false, Rename:map[string]string(nil), NoDerefSymlinks:false, IgnoreUnreadable:false}, PutOptions:copier.PutOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), DefaultDirOwner:(*idtools.IDPair)(nil), DefaultDirMode:(*os.FileMode)(nil), ChownDirs:(*idtools.IDPair)(0xc0000f58e0), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(0xc0000f58f0), ChmodFiles:(*os.FileMode)(nil), StripXattrs:false, IgnoreXattrErrors:false, IgnoreDevices:true, NoOverwriteDirNonDir:false, Rename:map[string]string(nil)}, MkdirOptions:copier.MkdirOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), ChownNew:(*idtools.IDPair)(nil), ChmodNew:(*os.FileMode)(nil)}}: copier: put: error setting extended attributes on "/extensions/okd/perl-Errno-1.30-468.fc33_1.30-469.fc33.x86_64.drpm": error setting value of extended attribute "user.Zif.MdChecksum[1617881158]" on "/extensions/okd/perl-Errno-1.30-468.fc33_1.30-469.fc33.x86_64.drpm": operation not supported
Apr 17 17:53:38 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]:         * error copying from container: error during bulk transfer for copier.request{Request:"GET", Root:"/", preservedRoot:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", rootPrefix:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", Directory:"/", preservedDirectory:"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged", Globs:[]string{"/"}, preservedGlobs:[]string{"/var/lib/containers/storage/overlay/825f827872569c38c4a95e111b8fedf2d6c01675e6e7532a53b5ca17fdb9350d/merged/."}, StatOptions:copier.StatOptions{CheckForArchives:false, Excludes:[]string(nil)}, GetOptions:copier.GetOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), Excludes:[]string{"dev", "proc", "sys"}, ExpandArchives:false, ChownDirs:(*idtools.IDPair)(0xc000179a40), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(0xc000179a50), ChmodFiles:(*os.FileMode)(nil), StripSetuidBit:false, StripSetgidBit:false, StripStickyBit:false, StripXattrs:false, KeepDirectoryNames:false, Rename:map[string]string(nil), NoDerefSymlinks:false, IgnoreUnreadable:false}, PutOptions:copier.PutOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), DefaultDirOwner:(*idtools.IDPair)(nil), DefaultDirMode:(*os.FileMode)(nil), ChownDirs:(*idtools.IDPair)(nil), ChmodDirs:(*os.FileMode)(nil), ChownFiles:(*idtools.IDPair)(nil), ChmodFiles:(*os.FileMode)(nil), StripXattrs:false, IgnoreXattrErrors:false, IgnoreDevices:false, NoOverwriteDirNonDir:false, Rename:map[string]string(nil)}, MkdirOptions:copier.MkdirOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), ChownNew:(*idtools.IDPair)(nil), ChmodNew:(*os.FileMode)(nil)}}: copier: get: "/"("/"): error copying /extensions/okd/perl-PathTools-3.78-458.fc33.x86_64.rpm: write bulk-writer: broken pipe
Apr 17 17:53:38 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: : exit status 125; retrying...
Apr 17 17:53:38 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: I0417 17:53:38.086654    1821 rpm-ostree.go:261] Running captured: chcon -R -t var_run_t /run/mco-machine-os-content/os-content-983218098
Apr 17 17:53:38 k8s-bootstrap-1-01.okd.basedomain.com podman[2578]: 2021-04-17 17:53:38.347844226 +0000 UTC m=+0.117265187 container remove baf71618a5514ab11e21e9042c06e1f3a3bee4749b57340259a3b14776ee16c9 (image=quay.io/openshift/okd-content@sha256:16da407404e6cedf64b0b6680ddac2bc2e2a3cc6b761fb8ff92d23ef55c7cfdb, name=ostree-container-pivot-cce7ce42-119d-427d-8725-d5fa85dcb925, io.openshift.build.version-display-names=machine-os=Fedora CoreOS, io.openshift.build.name=machine-os-content, io.openshift.build.commit.ref=release-4.7, version=34.20210406.10.0, id-machine-config-operator-rpms=sha256:3d734a0fc058388e8bdc244c9b96ff22761828532e9bdee71243a1577d9fcd7d, io.openshift.build.commit.date=Mon Mar 29 15:36:42 2021 +0000, io.openshift.build.namespace=ci-op-3b4279f7, io.openshift.build.commit.author=OpenShift Merge Robot <openshift-merge-robot@users.noreply.github.com>, io.openshift.release.operator=true, io.openshift.build.commit.message=Merge pull request #112 from vrutkovs/4.7-no-xattrs, io.openshift.build.source-location=https://github.com/openshift/okd-machine-os, id-artifacts=sha256:291c1695e7c02d77695c75b6ff7999eb35065bcb87b1eac20a680a4f5481b126, io.openshift.build.versions=machine-os=34.20210406.10, io.buildah.version=1.16.4, io.openshift.build.commit.id=570737f3da52045a7082d24effea2f95272524ef)
Apr 17 17:53:38 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: I0417 17:53:38.354295    1821 rpm-ostree.go:261] Running captured: rpm-ostree status --json
Apr 17 17:53:40 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: I0417 17:53:40.137802    1821 rpm-ostree.go:184] Current origin is not custom
Apr 17 17:53:41 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: I0417 17:53:41.754836    1821 rpm-ostree.go:216] No com.coreos.ostree-commit label found in metadata! Inspecting...
Apr 17 17:53:41 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: I0417 17:53:41.754907    1821 rpm-ostree.go:261] Running captured: ostree refs --repo /run/mco-machine-os-content/os-content-983218098/srv/repo
Apr 17 17:53:42 k8s-bootstrap-1-01.okd.basedomain.com podman[3100]: 2021-04-17 17:53:42.680388518 +0000 UTC m=+0.837324567 image remove 6452c626a971168f1a0abe2a86c0f65665288be0d6fa82ef713e8a960bf4cc3c quay.io/openshift/okd-content@sha256:16da407404e6cedf64b0b6680ddac2bc2e2a3cc6b761fb8ff92d23ef55c7cfdb
Apr 17 17:53:42 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: error: error running ostree refs --repo /run/mco-machine-os-content/os-content-983218098/srv/repo: error: opening repo: opendir(/run/mco-machine-os-content/os-content-983218098/srv/repo): No such file or directory
Apr 17 17:53:42 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[1821]: : exit status 1
Apr 17 17:53:42 k8s-bootstrap-1-01.okd.basedomain.com systemd[1]: release-image.service: Main process exited, code=exited, status=1/FAILURE
Apr 17 17:53:42 k8s-bootstrap-1-01.okd.basedomain.com systemd[1]: release-image.service: Failed with result 'exit-code'.
Apr 17 17:53:42 k8s-bootstrap-1-01.okd.basedomain.com systemd[1]: Failed to start Download the OpenShift Release Image.
Apr 17 17:53:42 k8s-bootstrap-1-01.okd.basedomain.com systemd[1]: Dependency failed for Bootstrap a Kubernetes cluster.
Apr 17 17:53:42 k8s-bootstrap-1-01.okd.basedomain.com systemd[1]: bootkube.service: Job bootkube.service/start failed with result 'dependency'.
Apr 17 17:53:53 k8s-bootstrap-1-01.okd.basedomain.com systemd[1]: Starting Download the OpenShift Release Image...
Apr 17 17:53:53 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[3264]: Pulling quay.io/openshift/okd@sha256:4414db9e8945504d1d5423ec11d64df9fa8b4aa60d978f8b4bdb3d0720800741...
Apr 17 17:53:55 k8s-bootstrap-1-01.okd.basedomain.com podman[3265]: 2021-04-17 17:53:55.119125606 +0000 UTC m=+1.741208032 image pull  
Apr 17 17:53:55 k8s-bootstrap-1-01.okd.basedomain.com release-image-download.sh[3265]: f388ece1e5537b735eb48b61164eb15a9784f8192c4637b51ceb01b7971505fa
Apr 17 17:53:55 k8s-bootstrap-1-01.okd.basedomain.com systemd[1]: Finished Download the OpenShift Release Image.

```

**Version**
FedoraCoreOS version = 33.20210328.3.0
OKD version = 4.7.0-0.okd-2021-04-11-124433

**Log bundle**
It is not possible to provide must-gather in this state.

**Comment by myg0v** [comment] 2021-04-17 19:32
The bootstrap seems to boot normally with FedoraCoreOS version 33.20210217.3.0. So it is maybe a FedoraCoreOS specific issue?

**Comment by vrutkovs** [comment] 2021-04-18 07:44
Seems to be dupe of 566 indeed

**Closed by vrutkovs** 2021-04-18 07:44 UTC
