### ISSUE TITLE
OKD Version 4.9.0-0.okd-2021-11-28-035710 - Master Nodes have the 4.7 client.

### ISSUE THREAD

**Issue by cgruver** [openshift/okd#1019] opened 2021-12-14 16:06 UTC
OKD Version 4.9.0-0.okd-2021-11-28-035710

The embedded oc client on the master nodes is really old:

```
Client Version: 4.7.0
Server Version: 4.9.0-0.okd-2021-11-28-035710
Kubernetes Version: v1.22.1-1820+4dd1b5a1afc832-dirty
```

**Comment by vrutkovs** [comment] 2022-02-20 12:02
Dupe of https://github.com/openshift/okd/issues/447

**Closed by vrutkovs** 2022-02-20 12:02 UTC
