### ISSUE TITLE
 okd 4.4 cluster on Digital Ocean bootstrap fail 

### ISSUE THREAD

**Issue by milan-dikkumburage** [openshift/okd#258] opened 2020-07-14 16:48 UTC
Hi Team,

we are trying install okd 4.4 cluster on Digital Ocean.
Following the https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html 

But we stuck into the step of bootstrap of fcos step. It seems that we setup the https server to download the raw image and verify the connectivity. The connection works fine. But after we provide the kernel edit steps mentioned in the docs and we noticed it was not downloading the fcos raw image. any idea on this ?

Note:- we are using latest fcos version .

• received below connection refused ERROR 
[root@linux home]# openshift-install --dir=installation_directory/ wait-for bootstrap-complete --log-level=info
INFO Waiting up to 20m0s for the Kubernetes API at https://api.okd4.mydomain:6443...
ERROR Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: Get https://api.okd4.mydomain:6443/apis/config.openshift.io/v1/clusteroperators: dial tcp 138.485.284.394:6443: connect: connection refused

let me know if you need any additional info?

**Comment by vrutkovs** [comment] 2020-07-14 17:21
Dupe of #257

**Closed by vrutkovs** 2020-07-14 17:21 UTC
