### ISSUE TITLE
[FCOS] Azure: No workers created if a custom image is used

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#54] opened 2020-01-29 18:47 UTC
Hi,

I manually uploaded the decompressed FCOS image to a Azure storage blob in a resourcegroup and let Terraform create an fcos image from that. I had to patch openshift-install that I can do that in /data/data/azure/main.tf

The idea is that all my OKD cluster VMs use this image and I don't have to upload it every time I create a new cluster becaue in my case thats very slow (more than 25 minutes following a timeout).

The k8s control plane comes up this way but no workers are created.

I debugged that and saw that in the machineset for the workers still the "original" fcos image is referenced and not my own image which is in a different resource group.

The image for the machineset is defined in:

/pkg/asset/machines/azure/machines.go

I would like to create a parameter in the Azure installer where I can ask for the storage blob where the fcos vhd file is stored.

What do you think about this idea?

Greetings,

Josef

**Comment by jomeier** [comment] 2020-01-29 18:58
@vrutkovs:
I would prepare a PR for this feature:
* openshift-install create cluster
* select: Azure
* enter service account credentials as usual
* ask for storage blob URL where previously uploaded VHD file is stored. Default is the one which is used already.

Do you think that this makes sense?

**Comment by jomeier** [comment] 2020-01-29 22:14
Hi,

I managed to create a cluster which creates three worker VMs automatically. 

But they aren't available. 

```
oc get nodes 
```

does not show workers.

```
oc get csr
```

neither.

Greetings,

Josef

**Comment by jomeier** [comment] 2020-01-29 22:16
[must-gather.local.8055467149608392733.tar.gz](https://github.com/openshift/okd/files/4131000/must-gather.local.8055467149608392733.tar.gz)

**Comment by jomeier** [comment] 2020-01-29 22:17
Because of a network bug in the fcos image I restarted each worker VM once so they get an internet connection.

**Comment by LorbusChris** [comment] 2020-01-29 22:22
I assume you mean this part: https://github.com/openshift/installer/blob/master/pkg/asset/machines/azure/machines.go#L103

To me it sounds like a valid use-case to make this config'able and a PR to the installer would be welcomed, given that default behaviour wouldn't change.

**Comment by jomeier** [comment] 2020-01-29 22:33
Hi Christian,

it could be best solved here:

https://github.com/openshift/installer/blob/master/data/data/azure/main.tf

azurerm_storage_blob should only be called if we don‘t manually upload the Image.

Also the Image URL used for the creation of the image in the main.tf should reference the storage blob container where we manually uploaded the VHD file.

**Comment by jomeier** [comment] 2020-01-29 22:35
What me concerns is that the workers don’t get available for the cluster.

But that’s maybe a different issue because the fcos image still gets created as usual in the resource group of the cluster. Should make no difference to the vhd upload by the installer.

**Comment by vrutkovs** [comment] 2020-01-29 22:42
must gather shows that there are 3 worker machine object created: `c1-okd4-s8hdq-worker-westeurope1-pd9sd` etc. Each failing with `failed to create vm c1-okd4-s8hdq-worker-westeurope1-pd9sd : failed to create or get machine: compute.VirtualMachinesCreateOrUpdateFuture: asynchronous operation has not completed`

**Comment by jomeier** [comment] 2020-01-29 23:31
I also saw that.

Later it says that VMs have been created and that they get patched.

Don’t understand what’s the problem.

**Comment by jomeier** [comment] 2020-01-30 05:01
Running workers are the last step for OKD working on Azure.

Has Someone an idea where I could debug into to find the root cause of the problem?

**Comment by jomeier** [comment] 2020-01-31 06:42
May be the problem that I rebooted the workers manually after the got created? I did this because of the fcos bug where on Azure there is no internet connection until the first reboot.

**Comment by vrutkovs** [comment] 2020-02-02 17:21
I see, it appears to create VMs:
>Machine "c1-okd4-s8hdq-worker-westeurope3-lqx25" going into phase "Provisioned"

But they never join as nodes.

Does Azure console show these VMs? Are they booting? Can you ssh on them? What's the output of `journalctl -b -u kubelet` from them?

**Comment by jomeier** [comment] 2020-02-02 22:12
It's working now. I had to reboot also the workers several times manually to get them working.

I will close this issue.

**Comment by vrutkovs** [comment] 2020-02-02 22:43
No, rebooting workers to make them join the cluster is not acceptable. Even if it turns out to be a dupe of #50 lets keep it open for tracking

**Comment by jomeier** [comment] 2020-02-03 07:49
Absolutely.

**Comment by jomeier** [comment] 2020-03-25 18:00
This one will be fixed if the brand new FCOS image from here: 

https://github.com/coreos/fedora-coreos-tracker/issues/356 

gets released.

**Closed** 2020-05-08 15:14 UTC
Labels: installer, platform/azure
