### ISSUE TITLE
4.6.0-0.okd-2021-01-17-185703 upgrade fails running rpm-ostree rebase

### ISSUE THREAD

**Issue by abaxo** [openshift/okd#470] opened 2021-01-19 11:11 UTC
**Describe the bug**
Upgrade from `4.6.0-0.okd-2020-12-12-135354` to `4.6.0-0.okd-2021-01-17-18570` fails with the error:

```
lastSyncError: >-
      pool master has not progressed to latest configuration: controller version
      mismatch for rendered-master-edbc4256a515942f11fe1d8b38e9c424 expected
      a72f402cce4a683d4f9ba3956b5dcd297b458a54 has
      eb9778355a9020673e8ce9aee092cb98d80cde5e: pool is degraded because nodes
      fail with "1 nodes are reporting degraded status on sync": "Node
      green-56w99-master-0 is reporting: \"failed to update OS to
      quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c
      : with stdout output: : error running rpm-ostree rebase --experimental
      /run/mco-machine-os-content/os-content-108702483/srv/repo:14eea5296ffb7a28aff80a70c03434e8034422b0d11b47475b29530b93ab4682
      --custom-origin-url
      pivot://quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c
      --custom-origin-description Managed by machine-config-operator: 0
      metadata, 0 content objects imported; 0 bytes content written\\nChecking
      out tree 14eea52...done\\nEnabled rpm-md repositories:
      fedora-cisco-openh264 updates fedora coreos-extensions
      updates-archive\\nrpm-md repo 'fedora-cisco-openh264' (cached); generated:
      2020-08-25T19:10:34Z\\nrpm-md repo 'updates' (cached); generated:
      2021-01-18T01:24:53Z\\nrpm-md repo 'fedora' (cached); generated:
      2020-10-19T23:27:19Z\\nrpm-md repo 'coreos-extensions' (cached);
      generated: 2021-01-17T11:40:41Z\\nrpm-md repo 'updates-archive' (cached);
      generated: 2021-01-18T02:18:57Z\\nImporting rpm-md...done\\nResolving
      dependencies...done\\nChecking out packages...done\\n: exit status 1\"",
      retrying
    master: >-
      pool is degraded because nodes fail with "1 nodes are reporting degraded
      status on sync": "Node green-56w99-master-0 is reporting: \"failed to
      update OS to
      quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c
      : with stdout output: : error running rpm-ostree rebase --experimental
      /run/mco-machine-os-content/os-content-108702483/srv/repo:14eea5296ffb7a28aff80a70c03434e8034422b0d11b47475b29530b93ab4682
      --custom-origin-url
      pivot://quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c
      --custom-origin-description Managed by machine-config-operator: 0
      metadata, 0 content objects imported; 0 bytes content written\\nChecking
      out tree 14eea52...done\\nEnabled rpm-md repositories:
      fedora-cisco-openh264 updates fedora coreos-extensions
      updates-archive\\nrpm-md repo 'fedora-cisco-openh264' (cached); generated:
      2020-08-25T19:10:34Z\\nrpm-md repo 'updates' (cached); generated:
      2021-01-18T01:24:53Z\\nrpm-md repo 'fedora' (cached); generated:
      2020-10-19T23:27:19Z\\nrpm-md repo 'coreos-extensions' (cached);
      generated: 2021-01-17T11:40:41Z\\nrpm-md repo 'updates-archive' (cached);
      generated: 2021-01-18T02:18:57Z\\nImporting rpm-md...done\\nResolving
      dependencies...done\\nChecking out packages...done\\n: exit status 1\""
    worker: >-
      pool is degraded because nodes fail with "1 nodes are reporting degraded
      status on sync": "Node green-56w99-worker-rl7z6 is reporting: \"failed to
      update OS to
      quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c
      : with stdout output: : error running rpm-ostree rebase --experimental
      /run/mco-machine-os-content/os-content-202334466/srv/repo:14eea5296ffb7a28aff80a70c03434e8034422b0d11b47475b29530b93ab4682
      --custom-origin-url
      pivot://quay.io/openshift/okd-content@sha256:2fe2fd4d99c953d5bcf0d53b420a2012aae7fd12986dac8e757ad68f7b97030c
      --custom-origin-description Managed by machine-config-operator: 1475
      metadata, 4793 content objects imported; 1.3?GB content written\\nWriting
      objects: 116...done\\nChecking out tree 14eea52...done\\nEnabled rpm-md
      repositories: fedora-cisco-openh264 updates fedora coreos-extensions
      updates-archive\\nrpm-md repo 'fedora-cisco-openh264' (cached); generated:
      2020-08-25T19:10:34Z\\nUpdating metadata for 'updates'...done\\nrpm-md
      repo 'updates'; generated: 2021-01-18T01:24:53Z\\nrpm-md repo 'fedora'
      (cached); generated: 2020-10-19T23:27:19Z\\nrpm-md repo
      'coreos-extensions' (cached); generated: 2021-01-17T11:40:41Z\\nUpdating
      metadata for 'updates-archive'...done\\nrpm-md repo 'updates-archive';
      generated: 2021-01-18T02:18:57Z\\nImporting rpm-md...done\\nResolving
      dependencies...done\\nWill download: 1 package (783.2?kB)\\nDownloading
      from 'updates'...done\\nImporting
      packages...done\\nRelabeling...done\\nChecking out packages...done\\n:
      exit status 1\""
```

**Version**
4.6.0-0.okd-2021-01-17-185703

**How reproducible**
Unsure, not attempted to reproduce in another environment.

**Comment by vrutkovs** [comment] 2021-01-19 11:14
Dupe of #398

**Closed by vrutkovs** 2021-01-19 11:14 UTC

**Comment by abaxo** [comment] 2021-01-19 11:48
Thanks, disabling the repos did the trick!
