### ISSUE TITLE
Update Status Error on 4.5

### ISSUE THREAD

**Issue by baturorkun** [openshift/okd#748] opened 2021-07-08 07:17 UTC
I am using RHV and i could not install 4.6 or 4.7. So I had to install 4.5 and I am planning an upgrade. But now I have an upgrade problem.
My version is 4.5.0-0.okd-2020-10-15-235428

![Screen Shot 2021-07-08 at 10 12 37](https://user-images.githubusercontent.com/5508317/124879239-b2756c00-dfd5-11eb-91da-16ddbbf02d83.png)

**Comment by vrutkovs** [comment] 2021-07-08 07:42
Dupe of #674

**Closed by vrutkovs** 2021-07-08 07:42 UTC

**Comment by baturorkun** [comment] 2021-07-08 12:33
ok thanks
