### ISSUE TITLE
fresh deploy of OKD 4.9 2022-01-29 on vSphere UPI fails to initialize MCO

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#1085] opened 2022-01-29 18:05 UTC
**Describe the bug**
fresh deploy of OKD 4.9 2022-01-29 on vSphere UPI fails to initialize MCO
It stays eternally at:
`machine-config False True  True  52m Cluster not available for 4.9.0-0.okd-2022-01-29-035536`
The MCO constantly logs
`E0129 18:01:03.910726       1 sync.go:598] Error syncing Required MachineConfigPools: "error pool master is not ready, retrying. Status: (pool degraded: true total: 3, ready 0, updated: 0, unavailable: 3)"`
The log of the MC controller looks OK.

**Version**
OKD 4.9 2022-01-29 on vSphere UPI

**How reproducible**
first installation and failed.

**Log bundle**
https://domino.ars.de/file/log-bundle-20220129180041.tar.gz

**Comment by kai-uwe-rommel** [comment] 2022-01-29 18:07
```
>oc get mcp
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master                                                      False     True       True       3              0                   0                     3                      63m
worker   rendered-worker-5f9bf818227894869011ea29254f48e1   True      False      False      3              3                   3                     0                      63m
```

**Comment by kai-uwe-rommel** [comment] 2022-01-29 18:08
```
>oc get mc
NAME                                               GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
00-master                                          2909118923c2e01690115e9bf27c7aba779dd01c   3.2.0             60m
00-worker                                          2909118923c2e01690115e9bf27c7aba779dd01c   3.2.0             60m
01-master-container-runtime                        2909118923c2e01690115e9bf27c7aba779dd01c   3.2.0             60m
01-master-kubelet                                  2909118923c2e01690115e9bf27c7aba779dd01c   3.2.0             60m
01-worker-container-runtime                        2909118923c2e01690115e9bf27c7aba779dd01c   3.2.0             60m
01-worker-kubelet                                  2909118923c2e01690115e9bf27c7aba779dd01c   3.2.0             60m
99-master-generated-registries                     2909118923c2e01690115e9bf27c7aba779dd01c   3.2.0             60m
99-master-okd-extensions                                                                      3.2.0             77m
99-master-ssh                                                                                 3.2.0             77m
99-okd-master-disable-mitigations                                                             3.2.0             76m
99-okd-worker-disable-mitigations                                                             3.2.0             76m
99-worker-generated-registries                     2909118923c2e01690115e9bf27c7aba779dd01c   3.2.0             60m
99-worker-okd-extensions                                                                      3.2.0             76m
99-worker-ssh                                                                                 3.2.0             77m
rendered-master-ed8994ee142b0ac376e160fa73510609   2909118923c2e01690115e9bf27c7aba779dd01c   3.2.0             60m
rendered-worker-5f9bf818227894869011ea29254f48e1   2909118923c2e01690115e9bf27c7aba779dd01c   3.2.0             60m
```

**Comment by vrutkovs** [comment] 2022-01-29 19:11
>Node master-01.dmz-kurs.ars-computer.de is reporting: \"machineconfig.machineconfiguration.openshift.io \\\"rendered-master-29b1fdce3e860283fe98e14d3e4fa83e\\\" not found

Dupe of #963

**Closed by vrutkovs** 2022-01-29 19:11 UTC

**Comment by kai-uwe-rommel** [comment] 2022-01-29 20:04
Oops. Dupe of my own previous issue. :-)
