### ISSUE TITLE
Hostname falls to fedora on fresh install

### ISSUE THREAD

**Issue by nevidanniu** [openshift/okd#425] opened 2020-12-12 20:50 UTC
**Describe the bug**

When perform fresh install machine boots with correct name from dns, but during bootstraping falls to 'fedora'.
At the same time host flushes ssh keys, so you are not able to ssh to host.
As a result cluster cannot be created (only one node becomes availiable, with name fedora)

**Version**

Client Version: 4.6.0-0.okd-2020-12-12-135354
Kubernetes Version: v1.19.2-1008+70708036fc2657-dirty
fedora-coreos-32.20201104.3.0-live.x86_64
UPI install. VMs are on ESXi version:7.0.0

**How reproducible**

Always

**Steps to reproduce**
- create vms in ESXi 7
- generate and publish config 
```
openshift-install create manifests --dir=install_dir/
openshift-install create ignition-configs --dir=install_dir/
```

- create vm and boot into livecd
- init install with command
```
sudo coreos-installer install /dev/sda --image-url=http://192.168.0.200:8080/okd4/fcos.raw.xz --ignition-url=http://192.168.0.200:8080/okd4/bootstrap.ign --insecure=true --insecure-ignition=true --append-karg="ip=192.168.0.101::192.168.0.1:255.255.255.0::ens192:none:192.168.0.200"
```
- reboot after install complete 
- during bootstrap vm get correct name and ip, but later takes 'fedora' hostname and reject the key.

at the same time it still continue bootstrap process itself, bootstrap nodes get online and i'm able to bootstrap master nodes, but they fall to get into cluster because they all have same name.

**Log bundle**

[openshift_install.log](https://github.com/openshift/okd/files/5684750/openshift_install.log)

made two log bundles.
this one just after masters completely reloaded with 'fedora' name: [log-bundle-20201213123605.tar.gz](https://github.com/openshift/okd/files/5684760/log-bundle-20201213123605.tar.gz)
another was collected after installer failed with timeout. its too large for gitlab, thats why [google drive link](https://drive.google.com/file/d/1MgBHTes1ybO5S_I8rnV5-4TiAUlJKRMw/view?usp=sharing)

machine boot options:
![image](https://user-images.githubusercontent.com/16690291/101994151-231f0900-3cd1-11eb-8503-4044b52d4adb.png)
video with process [rec.zip](https://github.com/openshift/okd/files/5683742/rec.zip):
timing
0-2:23 - initial install via coreos-installer
2:59 - os loads with ip and correct hostname
5:44 - os loads with ip and fedora hostname

**Comment by vrutkovs** [comment] 2020-12-12 22:04
Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installing-getting-debug-information_installing-troubleshooting).

You're passing a static IP config, but doe you have a PTR record or set it in the vSphere VM metadata?

**Comment by nevidanniu** [comment] 2020-12-12 22:36
yes. config worked for 4.5 perfectly
reverse zone
```
$ttl 38400
0.168.192.in-addr.arpa.	IN	SOA	ns1.xix.support. kendepp.xix.support. (
			1598914225
			10800
			3600
			604800
			38400 )
0.168.192.in-addr.arpa.	IN	NS	ns1.xix.support.
200.0.168.192.in-addr.arpa.	IN	PTR	ns1.dev.xix.support.
101.0.168.192.in-addr.arpa.	IN	PTR	bootstrap.okd.dev.xix.support.
20.0.168.192.in-addr.arpa.	IN	PTR	master1.okd.dev.xix.support.
21.0.168.192.in-addr.arpa.	IN	PTR	master2.okd.dev.xix.support.
22.0.168.192.in-addr.arpa.	IN	PTR	master3.okd.dev.xix.support.
30.0.168.192.in-addr.arpa.	IN	PTR	worker1.okd.dev.xix.support.
31.0.168.192.in-addr.arpa.	IN	PTR	worker2.okd.dev.xix.support.
32.0.168.192.in-addr.arpa.	IN	PTR	worker3.okd.dev.xix.support.
200.0.168.192.in-addr.arpa.	IN	PTR	api.okd.dev.digial.rt.ru.
200.0.168.192.in-addr.arpa.	IN	PTR	api-int.okd.dev.digial.rt.ru.
```

primary zone
```
$ttl 38400
dev.xix.support.	IN	SOA	ns1.xix.support. kendepp.xix.support. (
			1598913819
			10800
			3600
			604800
			38400 )
dev.xix.support.	IN	NS	ns1.dev.xix.support.
ns1.dev.xix.support.	IN	A	192.168.0.200
bootstrap.okd.dev.xix.support.	IN	A	192.168.0.101
master1.okd.dev.xix.support.	IN	A	192.168.0.20
master2.okd.dev.xix.support.	IN	A	192.168.0.21
master3.okd.dev.xix.support.	IN	A	192.168.0.22
worker1.okd.dev.xix.support.	IN	A	192.168.0.30
worker2.okd.dev.xix.support.	IN	A	192.168.0.31
worker3.okd.dev.xix.support.	IN	A	192.168.0.32
api.okd.dev.xix.support.	IN	A	192.168.0.200
api-int.okd.dev.xix.support.	IN	A	192.168.0.200
*.apps.okd.dev.xix.support.	IN	A	192.168.0.200
etcd-0.okd.dev.xix.support.	IN	A	192.168.0.20
etcd-1.okd.dev.xix.support.	IN	A	192.168.0.21
etcd-2.okd.dev.xix.support.	IN	A	192.168.0.22
_etcd-server-ssl._tcp.okd.dev.xix.support.	IN	SRV	0 10 2380 etcd-0.okd.dev.xix.support.
_etcd-server-ssl._tcp.okd.dev.xix.support.	IN	SRV	0 10 2380 etcd-1.okd.dev.xix.support.
_etcd-server-ssl._tcp.okd.dev.xix.support.	IN	SRV	0 10 2380 etcd-2.okd.dev.xix.support.

```

192.168.0.200 - haproxy host for okd and nginx for storing IGNs

**Comment by nevidanniu** [comment] 2020-12-12 23:35
updated fisrt post with log bundle

**Comment by nevidanniu** [comment] 2020-12-13 09:30
just tried to install bootstrap node on hyper-v. Same hostname fall to fedora.

**Comment by vrutkovs** [comment] 2020-12-13 10:01
That's installer log, not the log bundle generated by installer

**Comment by nevidanniu** [comment] 2020-12-13 10:27
this is the only log i have 
```
└─> # ls -alh install_dir/
total 308K
drwxr-xr-x  3 root root 4.0K Dec 13 09:05 .
dr-xr-x--- 25 root root 4.0K Dec 13 09:04 ..
drwxr-x---  2 root root 4.0K Dec 12 16:55 auth
-rw-r-----  1 root root 278K Dec 12 16:56 bootstrap.ign
-rw-r-----  1 root root 1.7K Dec 12 16:55 master.ign
-rw-r-----  1 root root   94 Dec 12 16:56 metadata.json
-rw-r--r--  1 root root 1.1K Dec 13 09:07 .openshift_install.log
-rw-r-----  1 root root 1.7K Dec 12 16:55 worker.ign

```
i perform upi installation and cannot ssh into hosts to gather info.

**Comment by nevidanniu** [comment] 2020-12-13 11:10
> [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installing-getting-debug-information_installing-troubleshooting).

as i said, it brokes ssh and i cannot gather bundle

```
└─> # openshift-install gather bootstrap --dir=install_dir --bootstrap 192.168.0.101 --master 192.168.0.20 --master 192.168.0.21 --master 192.168.0.22
INFO Pulling debug logs from the bootstrap machine
FATAL failed to create SSH client: failed to use pre-existing agent, make sure the appropriate keys exist in the agent for authentication: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

```
└─> # ssh 192.168.0.101
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```
_ssh key is correct_

**Comment by vrutkovs** [comment] 2020-12-13 11:12
>it brokes ssh

Might be related - https://dev.to/bowmanjd/upgrade-ssh-client-keys-and-remote-servers-after-fedora-33-s-new-crypto-policy-47ag

**Comment by nevidanniu** [comment] 2020-12-13 14:56
> > it brokes ssh
> 
> Might be related - https://dev.to/bowmanjd/upgrade-ssh-client-keys-and-remote-servers-after-fedora-33-s-new-crypto-policy-47ag

thanks! regenerated keys in ed25519 and ssh works now.
updated first post with new install_log and log-bundles

**Comment by nevidanniu** [comment] 2020-12-16 10:01
added hostname to cmd now it works.
```
--append-karg="ip=192.168.0.101::192.168.0.1:255.255.255.0::ens192:none:192.168.0.200"
````
changed to 
```
--append-karg="ip=192.168.0.101::192.168.0.1:255.255.255.0:myfqdn.host.localname:ens192:none:192.168.0.200"
```
Looks like if i set static ip, it tries to find hostname in that config and fail as it was none. for previous versions it looked for ptr.
May be duplicate of #394 issue.
Please close, if it is.

**Comment by vrutkovs** [comment] 2020-12-24 09:49
Yup, looks like a dupe of #394 indeed, closing

**Closed by vrutkovs** 2020-12-24 09:49 UTC
Labels: triage/needs-information
